Repository input-output-hk/catalyst-voices, pull requests merged in 2023-12, with the labels that each got.

#173 feat(docs): Integrate Rust docs to our general mkDocs
  catalyst-gateway/.cargo/config.toml
  catalyst-gateway/Earthfile
  catalyst-gateway/bin/Cargo.toml
  catalyst-gateway/clippy.toml
  docs/Earthfile
  docs/src/.pages
  docs/src/api/.pages
  docs/src/api/catalyst-gateway.md
  docs/src/api/index.md
  docs/src/appendix/important/.pages
  docs/src/architecture/.pages
  docs/src/catalyst-standards/index.md
Labels: documentation, review me

#186 fix: Rust builder bug
  catalyst-gateway/.cargo/config.toml
  catalyst-gateway/Earthfile
  catalyst-gateway/bin/src/settings.rs
  catalyst-gateway/deny.toml
Labels: review me

#188 feat: Tests structure
  catalyst-gateway/.cargo/config.toml
  catalyst-gateway/Cargo.lock
  catalyst-gateway/Cargo.toml
  catalyst-gateway/Earthfile
  catalyst-gateway/tests/Cargo.toml
  catalyst-gateway/tests/Earthfile
  catalyst-gateway/tests/integration/catalyst_gateway_event_db.rs
  catalyst-gateway/tests/integration/docker-compose.yml
  catalyst-gateway/tests/integration/main.rs
Labels: review me

#197 feat: Handle DB schema version mismatch
  catalyst-gateway/bin/src/service/api/health/ready_get.rs
  catalyst-gateway/bin/src/state/mod.rs
Labels: do not merge yet
