Repository input-output-hk/catalyst-voices, pull requests merged in 2024-06, with the labels that each got.

#463 chore: refactor event-db queries to do batch inserts and updates
  catalyst-gateway/bin/src/cardano/mod.rs
  catalyst-gateway/bin/src/event_db/cardano/chain_state/insert_slot_index.sql
  catalyst-gateway/bin/src/event_db/cardano/chain_state/mod.rs
  catalyst-gateway/bin/src/event_db/cardano/cip36_registration/insert_cip36_registration.sql
  catalyst-gateway/bin/src/event_db/cardano/cip36_registration/mod.rs
  catalyst-gateway/bin/src/event_db/cardano/utxo/insert_txn_index.sql
  catalyst-gateway/bin/src/event_db/cardano/utxo/insert_utxo.sql
  catalyst-gateway/bin/src/event_db/cardano/utxo/mod.rs
  catalyst-gateway/bin/src/event_db/cardano/utxo/update_utxo.sql
Labels: review me

#523 feat: cardano wallet api example
  .config/dictionaries/project.dic
  catalyst_voices/pubspec.yaml
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/example/.gitignore
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/example/.metadata
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/example/README.md
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/example/analysis_options.yaml
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/example/lib/main.dart
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/example/pubspec.yaml
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/example/web/favicon.png
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/example/web/icons/Icon-192.png
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/example/web/icons/Icon-512.png
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/example/web/icons/Icon-maskable-192.png
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/example/web/icons/Icon-maskable-512.png
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/example/web/index.html
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/example/web/manifest.json
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/lib/catalyst_cardano.dart
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_web/pubspec.yaml
Labels: review me, dart

#521 fix: `cat-voice` flutter builder ci
  .earthlyignore
  catalyst_voices/Earthfile
  catalyst_voices/packages/catalyst_voices_services/lib/generated/catalyst_gateway/cat_gateway_api.enums.swagger.dart
  catalyst_voices/packages/catalyst_voices_services/lib/generated/catalyst_gateway/cat_gateway_api.models.swagger.dart
  catalyst_voices/packages/catalyst_voices_services/lib/generated/catalyst_gateway/cat_gateway_api.models.swagger.g.dart
  catalyst_voices/packages/catalyst_voices_services/lib/generated/catalyst_gateway/cat_gateway_api.swagger.dart
  catalyst_voices/test_driver/Earthfile
  catalyst_voices/test_driver/scripts/install-chrome-linux64.sh
  catalyst_voices/test_driver/scripts/install-edge-linux64.sh
  catalyst_voices/test_driver/scripts/install-firefox-linux64.sh
Labels: do not merge yet, review me

#522 feat: cardano wallet api
  .config/dictionaries/project.dic
  catalyst_voices/lib/app/view/app_page.dart
  catalyst_voices/pubspec.yaml
  catalyst_voices/web/index.html
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/CHANGELOG.md
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/README.md
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/example/.gitignore
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/example/.metadata
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/example/README.md
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/example/analysis_options.yaml
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/example/lib/main.dart
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/example/pubspec.yaml
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/example/web/favicon.png
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/example/web/icons/Icon-192.png
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/example/web/icons/Icon-512.png
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/example/web/icons/Icon-maskable-192.png
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/example/web/icons/Icon-maskable-512.png
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/example/web/index.html
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/example/web/manifest.json
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/lib/catalyst_cardano.dart
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/lib/src/catalyst_cardano.dart
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/pubspec.yaml
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_platform_interface/CHANGELOG.md
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_platform_interface/lib/catalyst_cardano_platform_interface.dart
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_platform_interface/lib/src/cardano_wallet.dart
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_platform_interface/lib/src/catalyst_cardano_platform.dart
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_platform_interface/lib/src/exceptions.dart
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_platform_interface/pubspec.yaml
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_web/CHANGELOG.md
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_web/assets/js/catalyst_cardano.js
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_web/lib/catalyst_cardano_web.dart
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_web/lib/src/interop/catalyst_cardano_interop.dart
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_web/lib/src/interop/catalyst_cardano_wallet_proxy.dart
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_web/pubspec.yaml
  catalyst_voices_packages/catalyst_cardano_serialization/README.md
  catalyst_voices_packages/catalyst_cardano_serialization/example/main.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/address.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/transaction.dart
  catalyst_voices_packages/catalyst_cardano_serialization/test/address_test.dart
  catalyst_voices_packages/catalyst_cardano_serialization/test/transaction_test.dart
Labels: review me, dart

#515 chore: upgrade flutter to 3.22.1
  .earthlyignore
  catalyst_voices/Earthfile
  catalyst_voices/README.md
  catalyst_voices/android/app/build.gradle
  catalyst_voices/android/app/src/main/java/io/flutter/app/FlutterMultiDexApplication.java
  catalyst_voices/android/build.gradle
  catalyst_voices/android/gradle/wrapper/gradle-wrapper.properties
  catalyst_voices/android/settings.gradle
  catalyst_voices/ios/Podfile.lock
  catalyst_voices/ios/Runner.xcodeproj/project.pbxproj
  catalyst_voices/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  catalyst_voices/packages/catalyst_voices_assets/example/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_assets/example/web/index.html
  catalyst_voices/packages/catalyst_voices_assets/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_blocs/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_brands/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_localization/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_models/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_repositories/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_services/lib/generated/catalyst_gateway/cat_gateway_api.enums.swagger.dart
  catalyst_voices/packages/catalyst_voices_services/lib/generated/catalyst_gateway/cat_gateway_api.models.swagger.dart
  catalyst_voices/packages/catalyst_voices_services/lib/generated/catalyst_gateway/cat_gateway_api.models.swagger.g.dart
  catalyst_voices/packages/catalyst_voices_services/lib/generated/catalyst_gateway/cat_gateway_api.swagger.dart
  catalyst_voices/packages/catalyst_voices_services/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_shared/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_view_models/pubspec.yaml
  catalyst_voices/pubspec.yaml
  catalyst_voices/test_driver/Earthfile
  catalyst_voices/test_driver/scripts/install-chrome-linux64.sh
  catalyst_voices/test_driver/scripts/install-edge-linux64.sh
  catalyst_voices/test_driver/scripts/install-firefox-linux64.sh
  catalyst_voices/web/index.html
  catalyst_voices_packages/catalyst_analysis/example/pubspec.yaml
  catalyst_voices_packages/catalyst_analysis/pubspec.yaml
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/example/pubspec.yaml
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/example/web/index.html
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/pubspec.yaml
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_platform_interface/pubspec.yaml
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_web/pubspec.yaml
  catalyst_voices_packages/catalyst_cardano_serialization/README.md
  catalyst_voices_packages/catalyst_cardano_serialization/pubspec.yaml
  melos.yaml
  utilities/catalyst_voices_remote_widgets/example/android/settings.gradle
  utilities/catalyst_voices_remote_widgets/example/web/index.html
  utilities/catalyst_voices_remote_widgets/pubspec.yaml
Labels: review me

#531 feat: Add VoicesAppBar
  .config/dictionaries/project.dic
  catalyst_voices/lib/pages/widgets/voices_app_bar/actions/connecting_status.dart
  catalyst_voices/lib/pages/widgets/voices_app_bar/actions/finish_account_button.dart
  catalyst_voices/lib/pages/widgets/voices_app_bar/actions/get_started_button.dart
  catalyst_voices/lib/pages/widgets/voices_app_bar/actions/notifications_indicator.dart
  catalyst_voices/lib/pages/widgets/voices_app_bar/actions/role_picker.dart
  catalyst_voices/lib/pages/widgets/voices_app_bar/actions/search_button.dart
  catalyst_voices/lib/pages/widgets/voices_app_bar/actions/unlock_button.dart
  catalyst_voices/lib/pages/widgets/voices_app_bar/actions/user_profile_button.dart
  catalyst_voices/lib/pages/widgets/voices_app_bar/actions/voices_app_bar_actions.dart
  catalyst_voices/lib/pages/widgets/voices_app_bar/voices_app_bar.dart
  catalyst_voices/packages/catalyst_voices_assets/assets/colors/colors.xml
  catalyst_voices/packages/catalyst_voices_assets/internal_resources/fonts/CatalystVoicesIcons.ttf
  catalyst_voices/packages/catalyst_voices_assets/lib/generated/colors.gen.dart
  catalyst_voices/packages/catalyst_voices_assets/lib/src/catalyst_voices_assets.dart
  catalyst_voices/packages/catalyst_voices_assets/lib/src/catalyst_voices_icons.dart
  catalyst_voices/packages/catalyst_voices_assets/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_brands/lib/src/catalyst_voices_brands.dart
  catalyst_voices/packages/catalyst_voices_brands/lib/src/theme_extensions/theme_extensions.dart
  catalyst_voices/packages/catalyst_voices_brands/lib/src/theme_extensions/voices_color_scheme.dart
  catalyst_voices/packages/catalyst_voices_brands/lib/src/themes/catalyst.dart
  catalyst_voices/packages/catalyst_voices_brands/test/src/catalyst_voices_brands_test.dart
  catalyst_voices/packages/catalyst_voices_localization/lib/generated/catalyst_voices_localizations.dart
  catalyst_voices/packages/catalyst_voices_localization/lib/generated/catalyst_voices_localizations_en.dart
  catalyst_voices/packages/catalyst_voices_localization/lib/generated/catalyst_voices_localizations_es.dart
  catalyst_voices/packages/catalyst_voices_localization/lib/l10n/intl_en.arb
  catalyst_voices/pubspec.yaml
Labels: review me

#536 fix: Fix .earthlyignore excluded directories/files
  .earthlyignore
Labels: review me

#537 fix: catalyst cardano support for NFTs
  .gitignore
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/README.md
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/example/lib/main.dart
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_platform_interface/lib/src/cardano_wallet.dart
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_web/lib/src/interop/catalyst_cardano_wallet_proxy.dart
  catalyst_voices_packages/catalyst_cardano_serialization/README.md
  catalyst_voices_packages/catalyst_cardano_serialization/example/main.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/address.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/builders/transaction_builder.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/builders/witness_builder.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/exceptions.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/fees.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/transaction.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/types.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/utils/numbers.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/witness.dart
  catalyst_voices_packages/catalyst_cardano_serialization/pubspec.yaml
  catalyst_voices_packages/catalyst_cardano_serialization/test/test_utils/test_data.dart
  catalyst_voices_packages/catalyst_cardano_serialization/test/types_test.dart
Labels: review me, dart

#538 feat: cardano wallet cip 95
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/example/lib/main.dart
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_platform_interface/lib/src/cardano_wallet.dart
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_platform_interface/lib/src/exceptions.dart
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_platform_interface/pubspec.yaml
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_web/lib/src/interop/catalyst_cardano_interop.dart
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_web/lib/src/interop/catalyst_cardano_wallet_proxy.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/catalyst_cardano_serialization.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/cip95/drep.dart
Labels: review me, dart

#548 docs: add common issues docs
  catalyst_voices/README.md
Labels: documentation, review me

#541 fix: Schemathesis cache
  catalyst-gateway/tests/schemathesis_tests/Earthfile
Labels: review me

#553 fix(ci): Increase schemathesis max response time
  catalyst-gateway/tests/schemathesis_tests/Earthfile
Labels: review me

#486 fix: Remove unneeded `raw_metadata` field.
  catalyst-gateway/bin/src/cardano/cip36_registration/mod.rs
  catalyst-gateway/bin/src/event_db/cardano/cip36_registration/mod.rs
Labels: review me

#549 feat: frontend features
  .config/dictionaries/project.dic
  .earthlyignore
  .gitignore
  catalyst_voices/README.md
  catalyst_voices/lib/pages/widgets/voices_app_bar/actions/connecting_status.dart
  catalyst_voices/lib/pages/widgets/voices_app_bar/actions/finish_account_button.dart
  catalyst_voices/lib/pages/widgets/voices_app_bar/actions/get_started_button.dart
  catalyst_voices/lib/pages/widgets/voices_app_bar/actions/notifications_indicator.dart
  catalyst_voices/lib/pages/widgets/voices_app_bar/actions/role_picker.dart
  catalyst_voices/lib/pages/widgets/voices_app_bar/actions/search_button.dart
  catalyst_voices/lib/pages/widgets/voices_app_bar/actions/unlock_button.dart
  catalyst_voices/lib/pages/widgets/voices_app_bar/actions/user_profile_button.dart
  catalyst_voices/lib/pages/widgets/voices_app_bar/actions/voices_app_bar_actions.dart
  catalyst_voices/lib/pages/widgets/voices_app_bar/voices_app_bar.dart
  catalyst_voices/packages/catalyst_voices_assets/assets/colors/colors.xml
  catalyst_voices/packages/catalyst_voices_assets/internal_resources/fonts/CatalystVoicesIcons.ttf
  catalyst_voices/packages/catalyst_voices_assets/lib/generated/colors.gen.dart
  catalyst_voices/packages/catalyst_voices_assets/lib/src/catalyst_voices_assets.dart
  catalyst_voices/packages/catalyst_voices_assets/lib/src/catalyst_voices_icons.dart
  catalyst_voices/packages/catalyst_voices_assets/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_brands/lib/src/catalyst_voices_brands.dart
  catalyst_voices/packages/catalyst_voices_brands/lib/src/theme_extensions/theme_extensions.dart
  catalyst_voices/packages/catalyst_voices_brands/lib/src/theme_extensions/voices_color_scheme.dart
  catalyst_voices/packages/catalyst_voices_brands/lib/src/themes/catalyst.dart
  catalyst_voices/packages/catalyst_voices_brands/test/src/catalyst_voices_brands_test.dart
  catalyst_voices/packages/catalyst_voices_localization/lib/generated/catalyst_voices_localizations.dart
  catalyst_voices/packages/catalyst_voices_localization/lib/generated/catalyst_voices_localizations_en.dart
  catalyst_voices/packages/catalyst_voices_localization/lib/generated/catalyst_voices_localizations_es.dart
  catalyst_voices/packages/catalyst_voices_localization/lib/l10n/intl_en.arb
  catalyst_voices/pubspec.yaml
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/README.md
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/example/lib/main.dart
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_platform_interface/lib/src/cardano_wallet.dart
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_platform_interface/lib/src/exceptions.dart
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_platform_interface/pubspec.yaml
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_web/lib/src/interop/catalyst_cardano_interop.dart
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_web/lib/src/interop/catalyst_cardano_wallet_proxy.dart
  catalyst_voices_packages/catalyst_cardano_serialization/README.md
  catalyst_voices_packages/catalyst_cardano_serialization/example/main.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/catalyst_cardano_serialization.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/address.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/builders/transaction_builder.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/builders/witness_builder.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/cip95/drep.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/exceptions.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/fees.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/transaction.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/types.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/utils/numbers.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/witness.dart
  catalyst_voices_packages/catalyst_cardano_serialization/pubspec.yaml
  catalyst_voices_packages/catalyst_cardano_serialization/test/test_utils/test_data.dart
  catalyst_voices_packages/catalyst_cardano_serialization/test/types_test.dart
Labels: review me

#557 feat: uikit example
  catalyst_voices/lib/app/view/app_content.dart
  catalyst_voices/lib/pages/widgets/voices_app_bar/actions/notifications_indicator.dart
  catalyst_voices/lib/pages/widgets/voices_app_bar/voices_app_bar.dart
  catalyst_voices/uikit_example/.gitignore
  catalyst_voices/uikit_example/.metadata
  catalyst_voices/uikit_example/README.md
  catalyst_voices/uikit_example/analysis_options.yaml
  catalyst_voices/uikit_example/lib/examples/voices_app_bar_example.dart
  catalyst_voices/uikit_example/lib/main.dart
  catalyst_voices/uikit_example/pubspec.yaml
  catalyst_voices/uikit_example/web/favicon.png
  catalyst_voices/uikit_example/web/icons/Icon-192.png
  catalyst_voices/uikit_example/web/icons/Icon-512.png
  catalyst_voices/uikit_example/web/icons/Icon-maskable-192.png
  catalyst_voices/uikit_example/web/icons/Icon-maskable-512.png
  catalyst_voices/uikit_example/web/index.html
  catalyst_voices/uikit_example/web/manifest.json
  melos.yaml
Labels: review me, dart

#527 feat(dev cluster): Basic Cluster Setup and all necessary default services installed and running.
  .config/dictionaries/project.dic
  .vscode/extensions.json
  .vscode/settings.recommended.json
  catalyst-gateway/.gitignore
  catalyst-gateway/Earthfile
  catalyst-gateway/deny.toml
  catalyst-gateway/event-db/Earthfile
  docs/Earthfile
  utilities/local-cluster/.gitignore
  utilities/local-cluster/Earthfile
  utilities/local-cluster/Readme.md
  utilities/local-cluster/Vagrantfile
  utilities/local-cluster/justfile
  utilities/local-cluster/manifests/cat-voices-docs.yml
  utilities/local-cluster/scripts/check-cluster-dns.py
  utilities/local-cluster/shared/extra.hosts
  utilities/local-cluster/shared/k3s/cert-manager/self-signed-issuer.yaml
  utilities/local-cluster/shared/k3s/grafana-prometheus/alert-manager-ingress.yaml
  utilities/local-cluster/shared/k3s/grafana-prometheus/grafana-ingress.yaml
  utilities/local-cluster/shared/k3s/grafana-prometheus/prometheus-ingress.yaml
  utilities/local-cluster/shared/k3s/grafana-prometheus/prometheus-values.yaml
  utilities/local-cluster/shared/k3s/grafana-prometheus/traefik-dashboard.yaml
  utilities/local-cluster/shared/k3s/grafana-prometheus/traefik-service-monitor.yaml
  utilities/local-cluster/shared/k3s/longhorn/ingress.yaml
  utilities/local-cluster/shared/k3s/longhorn/storage-classes.yaml
  utilities/local-cluster/shared/k3s/registries.yaml
  utilities/local-cluster/shared/k3s/registry/registry-service.yaml
  utilities/local-cluster/shared/k3s/registry/registry-ui.yaml
  utilities/local-cluster/shared/k3s/scylladb/load-balancer.yaml
  utilities/local-cluster/shared/k3s/scylladb/values.cluster.yaml
  utilities/local-cluster/shared/k3s/scylladb/values.manager.yaml
  utilities/local-cluster/shared/k3s/scylladb/values.operator.yaml
  utilities/local-cluster/shared/k3s/server/manifests/traefik-dashboard-helmconfig.yml
  utilities/local-cluster/shared/k3s/server/manifests/traefik-dashboard-ingress.yaml
  utilities/local-cluster/shared/k3s/server/manifests/traefik-dashboard-service.yaml
Labels: review me

#558 feat: uikit example firebase deploy
  .github/workflows/flutter-uikit-example-firebase-deploy.yml
  catalyst_voices/uikit_example/Earthfile
  catalyst_voices/uikit_example/firebase.json
Labels: do not merge yet, do not review yet

#568 feat: UIKit chip component
  .config/dictionaries/project.dic
  catalyst_voices/integration_test/scenarios/robots/login_robot.dart
  catalyst_voices/lib/pages/login/login_form.dart
  catalyst_voices/lib/widgets/chips/voices_chip.dart
  catalyst_voices/lib/widgets/email_input.dart
  catalyst_voices/lib/widgets/menu/voices_expandable_list_tile.dart
  catalyst_voices/lib/widgets/menu/voices_list_tile.dart
  catalyst_voices/lib/widgets/password_input.dart
  catalyst_voices/lib/widgets/voices_app_bar/actions/connecting_status.dart
  catalyst_voices/lib/widgets/voices_app_bar/actions/finish_account_button.dart
  catalyst_voices/lib/widgets/voices_app_bar/actions/get_started_button.dart
  catalyst_voices/lib/widgets/voices_app_bar/actions/notifications_indicator.dart
  catalyst_voices/lib/widgets/voices_app_bar/actions/role_picker.dart
  catalyst_voices/lib/widgets/voices_app_bar/actions/search_button.dart
  catalyst_voices/lib/widgets/voices_app_bar/actions/unlock_button.dart
  catalyst_voices/lib/widgets/voices_app_bar/actions/user_profile_button.dart
  catalyst_voices/lib/widgets/voices_app_bar/actions/voices_app_bar_actions.dart
  catalyst_voices/lib/widgets/voices_app_bar/voices_app_bar.dart
  catalyst_voices/lib/widgets/voices_drawer/voices_drawer.dart
  catalyst_voices/lib/widgets/widgets.dart
  catalyst_voices/packages/catalyst_voices_assets/assets/colors/colors.xml
  catalyst_voices/packages/catalyst_voices_assets/lib/generated/colors.gen.dart
  catalyst_voices/packages/catalyst_voices_brands/lib/src/theme_extensions/voices_color_scheme.dart
  catalyst_voices/packages/catalyst_voices_brands/lib/src/themes/catalyst.dart
  catalyst_voices/uikit_example/lib/examples/voices_chip_example.dart
  catalyst_voices/uikit_example/lib/examples/voices_navigation_example.dart
  catalyst_voices/uikit_example/lib/main.dart
Labels: review me, dart

#569 feat: add theme mode switcher
  catalyst_voices/uikit_example/lib/examples_list.dart
  catalyst_voices/uikit_example/lib/main.dart
Labels: review me, dart

#564 feat: add sentry
  .github/workflows/build-flutter-web.yml
  .vscode/launch.recommended.json
  catalyst_voices/Earthfile
  catalyst_voices/README.md
  catalyst_voices/lib/configs/bootstrap.dart
  catalyst_voices/lib/configs/sentry_service.dart
  catalyst_voices/lib/routes/app_router.dart
  catalyst_voices/packages/catalyst_voices_shared/lib/src/catalyst_voices_shared.dart
  catalyst_voices/packages/catalyst_voices_shared/lib/src/common/build_config.dart
  catalyst_voices/packages/catalyst_voices_shared/lib/src/common/build_environment.dart
  catalyst_voices/pubspec.yaml
Labels: review me

#543 feat: Add wallet automation test plan
  .config/dictionaries/project.dic
  docs/src/architecture/10_quality/testplans/flutter_cardano_integration.md
Labels: review me

#577 feat: add macos target
  .config/dictionaries/project.dic
  .vscode/launch.recommended.json
  catalyst_voices/.metadata
  catalyst_voices/catalyst_voices.iml
  catalyst_voices/macos/.gitignore
  catalyst_voices/macos/Flutter/Flutter-Debug.xcconfig
  catalyst_voices/macos/Flutter/Flutter-Release.xcconfig
  catalyst_voices/macos/Flutter/GeneratedPluginRegistrant.swift
  catalyst_voices/macos/Podfile
  catalyst_voices/macos/Podfile.lock
  catalyst_voices/macos/Runner.xcodeproj/project.pbxproj
  catalyst_voices/macos/Runner.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  catalyst_voices/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  catalyst_voices/macos/Runner.xcworkspace/contents.xcworkspacedata
  catalyst_voices/macos/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  catalyst_voices/macos/Runner/AppDelegate.swift
  catalyst_voices/macos/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json
  catalyst_voices/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_1024.png
  catalyst_voices/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_128.png
  catalyst_voices/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_16.png
  catalyst_voices/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_256.png
  catalyst_voices/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_32.png
  catalyst_voices/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_512.png
  catalyst_voices/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_64.png
  catalyst_voices/macos/Runner/Base.lproj/MainMenu.xib
  catalyst_voices/macos/Runner/Configs/AppInfo.xcconfig
  catalyst_voices/macos/Runner/Configs/Debug.xcconfig
  catalyst_voices/macos/Runner/Configs/Release.xcconfig
  catalyst_voices/macos/Runner/Configs/Warnings.xcconfig
  catalyst_voices/macos/Runner/DebugProfile.entitlements
  catalyst_voices/macos/Runner/Info.plist
  catalyst_voices/macos/Runner/MainFlutterWindow.swift
  catalyst_voices/macos/Runner/Release.entitlements
  catalyst_voices/macos/RunnerTests/RunnerTests.swift
Labels: review me

#580 fix: chips light/dark icons
  catalyst_voices/lib/widgets/chips/voices_chip.dart
Labels: review me, dart

#582 feat: add check for publishable packages
  catalyst_voices/Earthfile
  catalyst_voices/uikit_example/Earthfile
Labels: review me

#581 fix: issues before publishing catalyst-cardano
  catalyst_voices/Earthfile
  catalyst_voices/packages/catalyst_voices_assets/example/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_assets/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_blocs/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_brands/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_localization/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_repositories/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_services/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_shared/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_view_models/pubspec.yaml
  catalyst_voices/pubspec.yaml
  catalyst_voices/uikit_example/Earthfile
  catalyst_voices/uikit_example/pubspec.yaml
  catalyst_voices_packages/catalyst_analysis/.gitignore
  catalyst_voices_packages/catalyst_analysis/LICENSE
  catalyst_voices_packages/catalyst_analysis/example/melos_example.iml
  catalyst_voices_packages/catalyst_analysis/melos_catalyst_analysis.iml
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/LICENSE
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/example/pubspec.yaml
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/pubspec.yaml
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_platform_interface/LICENSE
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_platform_interface/pubspec.yaml
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_web/LICENSE
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_web/pubspec.yaml
  catalyst_voices_packages/catalyst_cardano_serialization/LICENSE
  melos.yaml
  pubspec.yaml
  utilities/catalyst_voices_remote_widgets/pubspec.yaml
Labels: review me

#583 chore(release): publish packages
  .markdownlint-cli2.jsonc
  CHANGELOG.md
  catalyst_voices_packages/catalyst_analysis/CHANGELOG.md
  catalyst_voices_packages/catalyst_analysis/pubspec.yaml
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/CHANGELOG.md
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/pubspec.yaml
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_platform_interface/CHANGELOG.md
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_platform_interface/pubspec.yaml
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_web/CHANGELOG.md
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_web/pubspec.yaml
  catalyst_voices_packages/catalyst_cardano_serialization/CHANGELOG.md
  catalyst_voices_packages/catalyst_cardano_serialization/pubspec.yaml
Labels: review me
