Repository input-output-hk/catalyst-voices, pull requests merged in 2024-04, with the labels that each got.

#359 feat: Add `/cardano/sync_state` endpoint, refactor
  catalyst-gateway/Cargo.lock
  catalyst-gateway/Cargo.toml
  catalyst-gateway/Earthfile
  catalyst-gateway/bin/src/event_db/config.rs
  catalyst-gateway/bin/src/event_db/error.rs
  catalyst-gateway/bin/src/event_db/follower.rs
  catalyst-gateway/bin/src/event_db/legacy/queries/event/ballot.rs
  catalyst-gateway/bin/src/event_db/legacy/queries/event/mod.rs
  catalyst-gateway/bin/src/event_db/legacy/queries/event/proposal.rs
  catalyst-gateway/bin/src/event_db/legacy/queries/registration.rs
  catalyst-gateway/bin/src/event_db/legacy/queries/search.rs
  catalyst-gateway/bin/src/event_db/legacy/queries/vit_ss/fund.rs
  catalyst-gateway/bin/src/event_db/utxo.rs
  catalyst-gateway/bin/src/follower.rs
  catalyst-gateway/bin/src/service/api/cardano/mod.rs
  catalyst-gateway/bin/src/service/api/cardano/staked_ada_get.rs
  catalyst-gateway/bin/src/service/api/cardano/sync_state_get.rs
  catalyst-gateway/bin/src/service/api/health/ready_get.rs
  catalyst-gateway/bin/src/service/api/mod.rs
  catalyst-gateway/bin/src/service/api/utxo/staked_ada_get.rs
  catalyst-gateway/bin/src/service/common/objects/cardano/mod.rs
  catalyst-gateway/bin/src/service/common/objects/cardano/network.rs
  catalyst-gateway/bin/src/service/common/objects/cardano/stake_address.rs
  catalyst-gateway/bin/src/service/common/objects/cardano/stake_amount.rs
  catalyst-gateway/bin/src/service/common/objects/cardano/sync_state.rs
  catalyst-gateway/bin/src/service/common/objects/mod.rs
  catalyst-gateway/bin/src/service/common/responses/resp_5xx.rs
  catalyst-gateway/bin/src/service/common/tags.rs
  catalyst-gateway/deny.toml
  catalyst-gateway/tests/Earthfile
  catalyst_voices/packages/catalyst_voices_services/lib/generated/catalyst_gateway/cat_gateway_api.enums.swagger.dart
  catalyst_voices/packages/catalyst_voices_services/lib/generated/catalyst_gateway/cat_gateway_api.models.swagger.dart
  catalyst_voices/packages/catalyst_voices_services/lib/generated/catalyst_gateway/cat_gateway_api.models.swagger.g.dart
  catalyst_voices/packages/catalyst_voices_services/lib/generated/catalyst_gateway/cat_gateway_api.swagger.chopper.dart
  catalyst_voices/packages/catalyst_voices_services/lib/generated/catalyst_gateway/cat_gateway_api.swagger.dart
Labels: review me

#372 feat: index and capture registration data cip36
  .config/dictionaries/project.dic
  catalyst-gateway/Cargo.lock
  catalyst-gateway/Earthfile
  catalyst-gateway/bin/Cargo.toml
  catalyst-gateway/bin/src/event_db/legacy/types/event.rs
  catalyst-gateway/bin/src/event_db/voter_registration.rs
  catalyst-gateway/bin/src/follower.rs
  catalyst-gateway/bin/src/main.rs
  catalyst-gateway/bin/src/registration/61284.cddl
  catalyst-gateway/bin/src/registration/61285.cddl
  catalyst-gateway/bin/src/registration/cip36.cddl
  catalyst-gateway/bin/src/registration/mod.rs
  catalyst-gateway/bin/src/service/mod.rs
  catalyst-gateway/event-db/Earthfile
  catalyst-gateway/event-db/migrations/V6__registration.sql
  catalyst-gateway/event-db/queries/voter_registration/insert_voter_registration.sql
  cspell.json
Labels: review me

#376 feat: Add CatalystDataGatewayRepository
  catalyst_voices/packages/catalyst_voices_repositories/README.md
  catalyst_voices/packages/catalyst_voices_repositories/lib/src/catalyst_data_gateway_repository.dart
  catalyst_voices/packages/catalyst_voices_repositories/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_repositories/test/src/catalyst_data_gateway_repository/catalyst_data_gateway_repository_test.dart
  catalyst_voices/packages/catalyst_voices_repositories/test/src/catalyst_data_gateway_repository/catalyst_data_gateway_repository_test.mocks.dart
  catalyst_voices/pubspec.yaml
Labels: review me

#365 feat: Full UTXO integration test against db-sync/snapshot_tool data
  .config/dictionaries/project.dic
  Earthfile
  catalyst-gateway/Earthfile
  catalyst-gateway/bin/src/event_db/error.rs
  catalyst-gateway/bin/src/event_db/utxo.rs
  catalyst-gateway/bin/src/event_db/voter_registration.rs
  catalyst-gateway/bin/src/follower.rs
  catalyst-gateway/bin/src/service/api/cardano/mod.rs
  catalyst-gateway/bin/src/service/api/cardano/staked_ada_get.rs
  catalyst-gateway/bin/src/service/common/objects/cardano/mod.rs
  catalyst-gateway/bin/src/service/common/objects/cardano/stake_info.rs
  catalyst-gateway/bin/src/util.rs
  catalyst-gateway/event-db/Earthfile
  catalyst-gateway/event-db/migrations/V1__config_tables.sql
  catalyst-gateway/event-db/migrations/V6__registration.sql
  catalyst-gateway/event-db/queries/utxo/insert_txn_index.sql
  catalyst-gateway/event-db/queries/utxo/insert_utxo.sql
  catalyst-gateway/event-db/queries/utxo/select_total_utxo_amount.sql
  catalyst-gateway/event-db/queries/utxo/update_utxo.sql
  catalyst-gateway/mithril_snapshot_loader/Earthfile
  catalyst-gateway/mithril_snapshot_loader/loader.py
  catalyst-gateway/tests/api_tests/Earthfile
  catalyst-gateway/tests/api_tests/api_tests/__init__.py
  catalyst-gateway/tests/api_tests/api_tests/test_utils.py
  catalyst-gateway/tests/api_tests/api_tests/test_utxo.py
  catalyst-gateway/tests/api_tests/api_tests/utils.py
  catalyst-gateway/tests/api_tests/docker-compose.yml
  catalyst-gateway/tests/api_tests/poetry.lock
  catalyst-gateway/tests/api_tests/pyproject.toml
  catalyst-gateway/tests/api_tests/snapshot_tool-56364174.json
  catalyst_voices/packages/catalyst_voices_services/lib/generated/catalyst_gateway/cat_gateway_api.models.swagger.dart
  catalyst_voices/packages/catalyst_voices_services/lib/generated/catalyst_gateway/cat_gateway_api.models.swagger.g.dart
  catalyst_voices/packages/catalyst_voices_services/lib/generated/catalyst_gateway/cat_gateway_api.swagger.chopper.dart
  catalyst_voices/packages/catalyst_voices_services/lib/generated/catalyst_gateway/cat_gateway_api.swagger.dart
  docs/Earthfile
Labels: review me

#398 perf: Optimize media query usage to avoid redundant rebuilds
  catalyst_voices/packages/catalyst_voices_shared/lib/src/responsive/responsive_builder.dart
Labels: review me

#387 feat: Get slot number by provided date-time endpoint
  Earthfile
  catalyst-gateway/Cargo.lock
  catalyst-gateway/Cargo.toml
  catalyst-gateway/Earthfile
  catalyst-gateway/bin/Cargo.toml
  catalyst-gateway/bin/src/event_db/follower.rs
  catalyst-gateway/bin/src/event_db/follower/insert_slot_index.sql
  catalyst-gateway/bin/src/event_db/follower/insert_update_state.sql
  catalyst-gateway/bin/src/event_db/follower/mod.rs
  catalyst-gateway/bin/src/event_db/follower/select_slot_info_by_datetime.sql.hbs
  catalyst-gateway/bin/src/event_db/follower/select_update_state.sql
  catalyst-gateway/bin/src/event_db/utxo.rs
  catalyst-gateway/bin/src/follower.rs
  catalyst-gateway/bin/src/service/api/cardano/date_time_to_slot_number_get.rs
  catalyst-gateway/bin/src/service/api/cardano/mod.rs
  catalyst-gateway/bin/src/service/api/cardano/staked_ada_get.rs
  catalyst-gateway/bin/src/service/api/cardano/sync_state_get.rs
  catalyst-gateway/bin/src/service/common/objects/cardano/mod.rs
  catalyst-gateway/bin/src/service/common/objects/cardano/network.rs
  catalyst-gateway/bin/src/service/common/objects/cardano/slot_info.rs
  catalyst-gateway/bin/src/service/common/objects/cardano/sync_state.rs
  catalyst-gateway/event-db/Earthfile
  catalyst-gateway/tests/Earthfile
  catalyst-gateway/tests/api_tests/Earthfile
  catalyst-gateway/tests/api_tests/api_tests/__init__.py
  catalyst-gateway/tests/api_tests/api_tests/test_slot_info.py
  catalyst-gateway/tests/api_tests/api_tests/test_utxo.py
  catalyst_voices/packages/catalyst_voices_services/lib/generated/catalyst_gateway/cat_gateway_api.models.swagger.dart
  catalyst_voices/packages/catalyst_voices_services/lib/generated/catalyst_gateway/cat_gateway_api.models.swagger.g.dart
  catalyst_voices/packages/catalyst_voices_services/lib/generated/catalyst_gateway/cat_gateway_api.swagger.chopper.dart
  catalyst_voices/packages/catalyst_voices_services/lib/generated/catalyst_gateway/cat_gateway_api.swagger.dart
  docs/Earthfile
Labels: review me

#332 feat: RBAC Documentation Drafting
  .config/dictionaries/project.dic
  .vscode/extensions.json
  cspell.json
  docs/src/architecture/08_concepts/.pages
  docs/src/catalyst-standards/cbor_tags/ulid.md
  docs/src/catalyst-standards/draft-cips/c509-plutus-restricted-certificate/c509-cert-plutus-restricted.cddl
  docs/src/catalyst-standards/draft-cips/c509-plutus-restricted-certificate/cip-509C.md
  docs/src/catalyst-standards/draft-cips/catalyst-vote-signing-cip30-extension/cip-xxxx.md
  docs/src/catalyst-standards/draft-cips/images/x509-roles-complete.d2
  docs/src/catalyst-standards/draft-cips/images/x509-roles-complete.svg
  docs/src/catalyst-standards/draft-cips/project-catalyst-x509-role-defintions/.meta.yml
  docs/src/catalyst-standards/draft-cips/project-catalyst-x509-role-defintions/cip-catalyst-roles.md
  docs/src/catalyst-standards/draft-cips/project-catalyst-x509-role-defintions/images/certificate-chain.d2
  docs/src/catalyst-standards/draft-cips/project-catalyst-x509-role-defintions/images/certificate-chain.svg
  docs/src/catalyst-standards/draft-cips/rbac-cip30-extension/cip-xxxx.md
  docs/src/catalyst-standards/draft-cips/role-registration/cip-xxxx.md
  docs/src/catalyst-standards/draft-cips/x509-envelope-metadata/.meta.yml
  docs/src/catalyst-standards/draft-cips/x509-envelope-metadata/cip-509A.md
  docs/src/catalyst-standards/draft-cips/x509-envelope-metadata/images/metadata-envelope-process.d2
  docs/src/catalyst-standards/draft-cips/x509-envelope-metadata/images/metadata-envelope-process.svg
  docs/src/catalyst-standards/draft-cips/x509-envelope-metadata/images/metadata-envelope-structure.d2
  docs/src/catalyst-standards/draft-cips/x509-envelope-metadata/images/metadata-envelope-structure.svg
  docs/src/catalyst-standards/draft-cips/x509-envelope-metadata/x509-envelope.cddl
  docs/src/catalyst-standards/draft-cips/x509-rbac-signing-with-cip30/.meta.yml
  docs/src/catalyst-standards/draft-cips/x509-rbac-signing-with-cip30/cip-x509D.md
  docs/src/catalyst-standards/draft-cips/x509-rbac-signing-with-cip30/images/cardano-transaction.d2
  docs/src/catalyst-standards/draft-cips/x509-rbac-signing-with-cip30/images/cardano-transaction.svg
  docs/src/catalyst-standards/draft-cips/x509-role-registration-metadata/.meta.yml
  docs/src/catalyst-standards/draft-cips/x509-role-registration-metadata/cip-509B.md
  docs/src/catalyst-standards/draft-cips/x509-role-registration-metadata/images/x509-roles.d2
  docs/src/catalyst-standards/draft-cips/x509-role-registration-metadata/images/x509-roles.svg
  docs/src/catalyst-standards/draft-cips/x509-role-registration-metadata/x509-roles.cddl
Labels: documentation, do not merge yet, draft, review me

#414 refactor: update schema_validation check
  catalyst-gateway/bin/src/cli.rs
  catalyst-gateway/bin/src/event_db/error.rs
  catalyst-gateway/bin/src/event_db/mod.rs
  catalyst-gateway/bin/src/service/api/cardano/date_time_to_slot_number_get.rs
  catalyst-gateway/bin/src/service/api/cardano/registration_get.rs
  catalyst-gateway/bin/src/service/api/cardano/staked_ada_get.rs
  catalyst-gateway/bin/src/service/api/cardano/sync_state_get.rs
  catalyst-gateway/bin/src/service/api/health/ready_get.rs
  catalyst-gateway/bin/src/service/mod.rs
  catalyst-gateway/bin/src/service/utilities/middleware/schema_validation.rs
  catalyst-gateway/bin/src/state/mod.rs
  catalyst-gateway/tests/api_tests/api_tests/__init__.py
Labels: review me

#425 refactor: Update error handling in `cat-gateway`
  catalyst-gateway/bin/src/cli.rs
  catalyst-gateway/bin/src/event_db/config.rs
  catalyst-gateway/bin/src/event_db/error.rs
  catalyst-gateway/bin/src/event_db/follower/mod.rs
  catalyst-gateway/bin/src/event_db/legacy/queries/event/ballot.rs
  catalyst-gateway/bin/src/event_db/legacy/queries/event/mod.rs
  catalyst-gateway/bin/src/event_db/legacy/queries/event/objective.rs
  catalyst-gateway/bin/src/event_db/legacy/queries/event/proposal.rs
  catalyst-gateway/bin/src/event_db/legacy/queries/event/review.rs
  catalyst-gateway/bin/src/event_db/legacy/queries/registration.rs
  catalyst-gateway/bin/src/event_db/legacy/queries/search.rs
  catalyst-gateway/bin/src/event_db/legacy/queries/vit_ss/fund.rs
  catalyst-gateway/bin/src/event_db/mod.rs
  catalyst-gateway/bin/src/event_db/schema_check.rs
  catalyst-gateway/bin/src/event_db/utxo.rs
  catalyst-gateway/bin/src/event_db/voter_registration/mod.rs
  catalyst-gateway/bin/src/follower.rs
  catalyst-gateway/bin/src/main.rs
  catalyst-gateway/bin/src/registration/mod.rs
  catalyst-gateway/bin/src/service/api/cardano/date_time_to_slot_number_get.rs
  catalyst-gateway/bin/src/service/api/cardano/registration_get.rs
  catalyst-gateway/bin/src/service/api/cardano/staked_ada_get.rs
  catalyst-gateway/bin/src/service/api/cardano/sync_state_get.rs
  catalyst-gateway/bin/src/service/api/health/ready_get.rs
  catalyst-gateway/bin/src/service/common/responses/resp_5xx.rs
  catalyst-gateway/bin/src/service/mod.rs
  catalyst-gateway/bin/src/service/poem_service.rs
  catalyst-gateway/bin/src/state/mod.rs
Labels: review me

#438 refactor: move dependency injection to catalyst_voices_shared package
  catalyst_voices/lib/app/view/app_page.dart
  catalyst_voices/lib/dependency/dependencies.dart
  catalyst_voices/packages/catalyst_voices_blocs/lib/src/catalyst_voices_blocs.dart
  catalyst_voices/packages/catalyst_voices_blocs/lib/src/dependency/dependency_provider.dart
  catalyst_voices/packages/catalyst_voices_blocs/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_shared/lib/src/catalyst_voices_shared.dart
  catalyst_voices/packages/catalyst_voices_shared/lib/src/dependency/dependency_provider.dart
  catalyst_voices/packages/catalyst_voices_shared/pubspec.yaml
Labels: review me

#441 feat: cardano multiplatform lib plugin structure
  .config/dictionaries/project.dic
  .gitignore
  catalyst_voices/Earthfile
  catalyst_voices/melos_catalyst_voices.iml
  catalyst_voices/packages/catalyst_voices_models/melos_catalyst_voices_models.iml
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/CHANGELOG.md
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/README.md
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/analysis_options.yaml
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/lib/catalyst_cardano.dart
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/lib/src/catalyst_cardano.dart
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/pubspec.yaml
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_platform_interface/CHANGELOG.md
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_platform_interface/README.md
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_platform_interface/analysis_options.yaml
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_platform_interface/lib/catalyst_cardano_platform_interface.dart
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_platform_interface/lib/src/catalyst_cardano_platform.dart
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_platform_interface/pubspec.yaml
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_web/CHANGELOG.md
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_web/README.md
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_web/analysis_options.yaml
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_web/lib/catalyst_cardano_web.dart
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_web/pubspec.yaml
  melos.yaml
  melos_catalyst_voices.iml
Labels: review me

#442 refactor: Refactor Cardano follower code, add a simple db queries performance logs
  catalyst-gateway/bin/src/cardano/mod.rs
  catalyst-gateway/bin/src/cli.rs
  catalyst-gateway/bin/src/event_db/cardano/follower/mod.rs
  catalyst-gateway/bin/src/service/api/cardano/sync_state_get.rs
Labels: review me

#445 fix: OpenAPI lint
  catalyst-gateway/bin/src/service/common/objects/cardano/registration_info.rs
  catalyst-gateway/tests/.spectral.yml
  catalyst-gateway/tests/Earthfile
  catalyst-gateway/tests/api_tests/api_tests/test_voter_registration.py
  catalyst_voices/packages/catalyst_voices_services/lib/generated/catalyst_gateway/cat_gateway_api.models.swagger.dart
  catalyst_voices/packages/catalyst_voices_services/lib/generated/catalyst_gateway/cat_gateway_api.models.swagger.g.dart
Labels: bug, review me

#450 refactor: Small improving of the cip36 parsing
  catalyst-gateway/bin/src/cardano/cip36_registration/cip36_registration.cddl
  catalyst-gateway/bin/src/cardano/cip36_registration/cip36_witness.cddl
  catalyst-gateway/bin/src/cardano/cip36_registration/mod.rs
  catalyst-gateway/bin/src/cardano/mod.rs
  catalyst-gateway/bin/src/event_db/cardano/cip36_registration/mod.rs
Labels: review me

#455 chore: update catalyst_voices earthly file to always take source files from artifact
  catalyst_voices/Earthfile
  catalyst_voices/packages/catalyst_voices_services/lib/generated/catalyst_gateway/cat_gateway_api.models.swagger.g.dart
Labels: review me

#458 feat: Quality docs
  .config/dictionaries/project.dic
  docs/src/architecture/01_introduction_and_goals.md
  docs/src/architecture/10_quality_requirements.md
Labels: review me
