Repository input-output-hk/catalyst-voices, pull requests merged in 2024-07, with the labels that each got.

#585 fix: readme versioning for catalyst packages
  catalyst_voices/pubspec.yaml
  catalyst_voices_packages/catalyst_analysis/README.md
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/README.md
  catalyst_voices_packages/catalyst_cardano_serialization/README.md
Labels: review me, dart

#586 chore(release): publish packages
  CHANGELOG.md
  catalyst_voices_packages/catalyst_analysis/CHANGELOG.md
  catalyst_voices_packages/catalyst_analysis/pubspec.yaml
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/CHANGELOG.md
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/pubspec.yaml
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_platform_interface/CHANGELOG.md
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_platform_interface/pubspec.yaml
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_web/CHANGELOG.md
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_web/pubspec.yaml
  catalyst_voices_packages/catalyst_cardano_serialization/CHANGELOG.md
  catalyst_voices_packages/catalyst_cardano_serialization/pubspec.yaml
Labels: review me

#587 fix: missing chromium version
  catalyst_voices/Earthfile
  catalyst_voices/uikit_example/Earthfile
Labels: review me

#593 feat: automate melos release
  .github/workflows/flutter-publish-packages.yml
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/pubspec.yaml
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_platform_interface/example/main.dart
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_web/example/main.dart
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_web/pubspec.yaml
  catalyst_voices_packages/catalyst_cardano_serialization/pubspec.yaml
  melos.yaml
Labels: review me, dart

#595 feat: automate melos publish
  .github/workflows/flutter-publish-packages.yml
Labels: review me

#592 fix: update cat-ci version to 3.1.13
  Earthfile
  catalyst-gateway/Earthfile
  catalyst-gateway/deny.toml
  catalyst-gateway/event-db/Earthfile
  catalyst-gateway/tests/Earthfile
  catalyst-gateway/tests/api_tests/Earthfile
  catalyst_voices/Earthfile
  catalyst_voices/uikit_example/Earthfile
  docs/Earthfile
Labels: review me

#605 feat: add required signers to catalyst_cardano_serialization
  catalyst_voices_packages/catalyst_cardano_serialization/README.md
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/builders/transaction_builder.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/transaction.dart
  catalyst_voices_packages/catalyst_cardano_serialization/test/fees_test.dart
  catalyst_voices_packages/catalyst_cardano_serialization/test/test_utils/test_data.dart
  catalyst_voices_packages/catalyst_cardano_serialization/test/transaction_test.dart
Labels: review me, dart

#601 feat: adds time-triggered GitHub action to run ci nightly
  .github/workflows/nightly-ci.yml
  catalyst-gateway/Earthfile
Labels: do not merge yet, review me

#604 feat: C509 `Name` type
  catalyst-gateway-crates/c509-certificate/Cargo.toml
  catalyst-gateway-crates/c509-certificate/src/c509_attributes/attribute.rs
  catalyst-gateway-crates/c509-certificate/src/c509_attributes/data.rs
  catalyst-gateway-crates/c509-certificate/src/c509_attributes/mod.rs
  catalyst-gateway-crates/c509-certificate/src/c509_general_names/data.rs
  catalyst-gateway-crates/c509-certificate/src/c509_general_names/general_name.rs
  catalyst-gateway-crates/c509-certificate/src/c509_name/mod.rs
  catalyst-gateway-crates/c509-certificate/src/c509_name/rdn.rs
  catalyst-gateway-crates/c509-certificate/src/lib.rs
Labels: documentation, enhancement, review me

#610 feat: C509 `AlgorithmIdentifier` for `subjectPublicKeyAlgorithm` and `issuerSignatureAlgorithm`
  catalyst-gateway-crates/c509-certificate/src/c509_algo_identifier.rs
  catalyst-gateway-crates/c509-certificate/src/c509_issuer_sig_algo/data.rs
  catalyst-gateway-crates/c509-certificate/src/c509_issuer_sig_algo/mod.rs
  catalyst-gateway-crates/c509-certificate/src/c509_subject_pub_key_algo/data.rs
  catalyst-gateway-crates/c509-certificate/src/c509_subject_pub_key_algo/mod.rs
  catalyst-gateway-crates/c509-certificate/src/lib.rs
Labels: documentation, enhancement, review me

#609 feat: C509 Implement type `Time` and `~biguint`
  catalyst-gateway-crates/c509-certificate/src/c509_big_uint.rs
  catalyst-gateway-crates/c509-certificate/src/c509_time.rs
  catalyst-gateway-crates/c509-certificate/src/lib.rs
Labels: documentation, enhancement, review me

#614 fix: update cat-ci to 3.1.16
  Earthfile
  catalyst-gateway-crates/c509-certificate/Earthfile
  catalyst-gateway/Earthfile
  catalyst-gateway/event-db/Earthfile
  catalyst-gateway/tests/Earthfile
  catalyst-gateway/tests/api_tests/Earthfile
  catalyst_voices/Earthfile
  catalyst_voices/uikit_example/Earthfile
  docs/Earthfile
Labels: review me

#622 fix: Update cat-ci version to v3.1.17
  Earthfile
  catalyst-gateway-crates/c509-certificate/Earthfile
  catalyst-gateway/Earthfile
  catalyst-gateway/event-db/Earthfile
  catalyst-gateway/tests/Earthfile
  catalyst-gateway/tests/api_tests/Earthfile
  catalyst_voices/Earthfile
  catalyst_voices/uikit_example/Earthfile
  docs/Earthfile
Labels: review me

#623 fix: report folder name, trigger manual
  .github/workflows/nightly-ci.yml
Labels: review me

#619 feat: rbac metadata
  catalyst_voices_packages/catalyst_cardano_serialization/README.md
  catalyst_voices_packages/catalyst_cardano_serialization/example/main.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/catalyst_cardano_serialization.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/builders/transaction_builder.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/builders/witness_builder.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/certificate.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/hashes.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/rbac/role_based_access_control.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/transaction.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/witness.dart
  catalyst_voices_packages/catalyst_cardano_serialization/test/hashes_test.dart
  catalyst_voices_packages/catalyst_cardano_serialization/test/rbac/role_based_access_control_test.dart
  catalyst_voices_packages/catalyst_cardano_serialization/test/test_utils/test_data.dart
  catalyst_voices_packages/catalyst_cardano_serialization/test/witness_test.dart
Labels: review me, dart

#615 feat: C509 craft a tbs certificate and sign the certificate
  catalyst-gateway-crates/c509-certificate/Cargo.toml
  catalyst-gateway-crates/c509-certificate/src/c509.rs
  catalyst-gateway-crates/c509-certificate/src/c509_algo_identifier.rs
  catalyst-gateway-crates/c509-certificate/src/c509_attributes/mod.rs
  catalyst-gateway-crates/c509-certificate/src/c509_big_uint.rs
  catalyst-gateway-crates/c509-certificate/src/c509_extensions/mod.rs
  catalyst-gateway-crates/c509-certificate/src/c509_general_names/mod.rs
  catalyst-gateway-crates/c509-certificate/src/c509_general_names/other_name_hw_module.rs
  catalyst-gateway-crates/c509-certificate/src/c509_issuer_sig_algo/data.rs
  catalyst-gateway-crates/c509-certificate/src/c509_name/mod.rs
  catalyst-gateway-crates/c509-certificate/src/c509_name/rdn.rs
  catalyst-gateway-crates/c509-certificate/src/c509_oid.rs
  catalyst-gateway-crates/c509-certificate/src/c509_subject_pub_key_algo/data.rs
  catalyst-gateway-crates/c509-certificate/src/c509_time.rs
  catalyst-gateway-crates/c509-certificate/src/lib.rs
  catalyst-gateway-crates/c509-certificate/src/signing.rs
  catalyst-gateway-crates/c509-certificate/src/tbs_cert.rs
Labels: documentation, enhancement

#626 feat: catalyst compression - brotli/zstd
  catalyst_voices/pubspec.yaml
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/example/pubspec.yaml
  catalyst_voices_packages/catalyst_compression/catalyst_compression/CHANGELOG.md
  catalyst_voices_packages/catalyst_compression/catalyst_compression/LICENSE
  catalyst_voices_packages/catalyst_compression/catalyst_compression/README.md
  catalyst_voices_packages/catalyst_compression/catalyst_compression/analysis_options.yaml
  catalyst_voices_packages/catalyst_compression/catalyst_compression/example/main.dart
  catalyst_voices_packages/catalyst_compression/catalyst_compression/lib/catalyst_compression.dart
  catalyst_voices_packages/catalyst_compression/catalyst_compression/lib/src/catalyst_compression.dart
  catalyst_voices_packages/catalyst_compression/catalyst_compression/pubspec.yaml
  catalyst_voices_packages/catalyst_compression/catalyst_compression_platform_interface/CHANGELOG.md
  catalyst_voices_packages/catalyst_compression/catalyst_compression_platform_interface/LICENSE
  catalyst_voices_packages/catalyst_compression/catalyst_compression_platform_interface/README.md
  catalyst_voices_packages/catalyst_compression/catalyst_compression_platform_interface/analysis_options.yaml
  catalyst_voices_packages/catalyst_compression/catalyst_compression_platform_interface/example/main.dart
  catalyst_voices_packages/catalyst_compression/catalyst_compression_platform_interface/lib/catalyst_compression_platform_interface.dart
  catalyst_voices_packages/catalyst_compression/catalyst_compression_platform_interface/lib/src/catalyst_compression_platform.dart
  catalyst_voices_packages/catalyst_compression/catalyst_compression_platform_interface/lib/src/catalyst_compressor.dart
  catalyst_voices_packages/catalyst_compression/catalyst_compression_platform_interface/pubspec.yaml
  catalyst_voices_packages/catalyst_compression/catalyst_compression_web/CHANGELOG.md
  catalyst_voices_packages/catalyst_compression/catalyst_compression_web/LICENSE
  catalyst_voices_packages/catalyst_compression/catalyst_compression_web/README.md
  catalyst_voices_packages/catalyst_compression/catalyst_compression_web/analysis_options.yaml
  catalyst_voices_packages/catalyst_compression/catalyst_compression_web/assets/js/catalyst_compression.js
  catalyst_voices_packages/catalyst_compression/catalyst_compression_web/example/main.dart
  catalyst_voices_packages/catalyst_compression/catalyst_compression_web/lib/catalyst_compression_web.dart
  catalyst_voices_packages/catalyst_compression/catalyst_compression_web/lib/src/interop/catalyst_compression_interop.dart
  catalyst_voices_packages/catalyst_compression/catalyst_compression_web/pubspec.yaml
Labels: review me, dart

#631 chore: update ci to v3.1.18
  Earthfile
  catalyst-gateway-crates/c509-certificate/Earthfile
  catalyst-gateway/Earthfile
  catalyst-gateway/event-db/Earthfile
  catalyst-gateway/tests/Earthfile
  catalyst-gateway/tests/api_tests/Earthfile
  catalyst_voices/Earthfile
  catalyst_voices/uikit_example/Earthfile
  docs/Earthfile
Labels: review me

#634 chore: update README
  catalyst_voices_packages/README.md
Labels: documentation

#636 fix: catalyst cardano integration with Typhoon wallet
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/README.md
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/example/lib/main.dart
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/example/lib/sign_and_submit_rbac_tx.dart
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/example/lib/sign_and_submit_tx.dart
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_platform_interface/lib/src/cardano_wallet.dart
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_web/assets/js/catalyst_cardano.js
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_web/lib/src/interop/catalyst_cardano_interop.dart
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_web/lib/src/interop/catalyst_cardano_wallet_proxy.dart
Labels: review me, dart

#637 chore(release): publish packages
  CHANGELOG.md
  catalyst_voices/pubspec.yaml
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/CHANGELOG.md
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/example/pubspec.yaml
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/pubspec.yaml
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_platform_interface/CHANGELOG.md
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_platform_interface/pubspec.yaml
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_web/CHANGELOG.md
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_web/pubspec.yaml
  catalyst_voices_packages/catalyst_cardano_serialization/CHANGELOG.md
  catalyst_voices_packages/catalyst_cardano_serialization/pubspec.yaml
  catalyst_voices_packages/catalyst_compression/catalyst_compression/CHANGELOG.md
  catalyst_voices_packages/catalyst_compression/catalyst_compression/pubspec.yaml
  catalyst_voices_packages/catalyst_compression/catalyst_compression_platform_interface/CHANGELOG.md
  catalyst_voices_packages/catalyst_compression/catalyst_compression_platform_interface/pubspec.yaml
  catalyst_voices_packages/catalyst_compression/catalyst_compression_web/CHANGELOG.md
  catalyst_voices_packages/catalyst_compression/catalyst_compression_web/pubspec.yaml
Labels: review me

#638 docs: add packages to readme
  catalyst_voices_packages/README.md
Labels: review me

#625 feat: C509 lib CLI example
  catalyst-gateway-crates/c509-certificate/Cargo.toml
  catalyst-gateway-crates/c509-certificate/Earthfile
  catalyst-gateway-crates/c509-certificate/examples/cli/data/cert_sample_1.json
  catalyst-gateway-crates/c509-certificate/examples/cli/main.rs
  catalyst-gateway-crates/c509-certificate/src/c509.rs
  catalyst-gateway-crates/c509-certificate/src/c509_algo_identifier.rs
  catalyst-gateway-crates/c509-certificate/src/c509_attributes/attribute.rs
  catalyst-gateway-crates/c509-certificate/src/c509_big_uint.rs
  catalyst-gateway-crates/c509-certificate/src/c509_extensions/alt_name.rs
  catalyst-gateway-crates/c509-certificate/src/c509_extensions/extension/mod.rs
  catalyst-gateway-crates/c509-certificate/src/c509_extensions/mod.rs
  catalyst-gateway-crates/c509-certificate/src/c509_general_names/general_name.rs
  catalyst-gateway-crates/c509-certificate/src/c509_general_names/mod.rs
  catalyst-gateway-crates/c509-certificate/src/c509_general_names/other_name_hw_module.rs
  catalyst-gateway-crates/c509-certificate/src/c509_issuer_sig_algo/mod.rs
  catalyst-gateway-crates/c509-certificate/src/c509_name/mod.rs
  catalyst-gateway-crates/c509-certificate/src/c509_name/rdn.rs
  catalyst-gateway-crates/c509-certificate/src/c509_oid.rs
  catalyst-gateway-crates/c509-certificate/src/c509_subject_pub_key_algo/mod.rs
  catalyst-gateway-crates/c509-certificate/src/c509_time.rs
  catalyst-gateway-crates/c509-certificate/src/lib.rs
  catalyst-gateway-crates/c509-certificate/src/signing.rs
  catalyst-gateway-crates/c509-certificate/src/tbs_cert.rs
Labels: enhancement, review me

#640 fix!: X509 registration metadata encoding
  .config/dictionaries/project.dic
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/example/lib/sign_and_submit_rbac_tx.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/catalyst_cardano_serialization.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/hashes.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/rbac/registration_data.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/rbac/x509_metadata_envelope.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/signature.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/transaction.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/utils/cbor.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/utils/uuid.dart
  catalyst_voices_packages/catalyst_cardano_serialization/test/hashes_test.dart
  catalyst_voices_packages/catalyst_cardano_serialization/test/utils/uuid_test.dart
Labels: review me, dart

#628 feat: c509 wasm binding js
  .config/dictionaries/project.dic
  catalyst-gateway-crates/c509-certificate/Cargo.toml
  catalyst-gateway-crates/c509-certificate/Earthfile
  catalyst-gateway-crates/c509-certificate/examples/web/index.html
  catalyst-gateway-crates/c509-certificate/examples/web/index.js
  catalyst-gateway-crates/c509-certificate/src/lib.rs
  catalyst-gateway-crates/c509-certificate/src/signing.rs
  catalyst-gateway-crates/c509-certificate/src/wasm_binding.rs
Labels: documentation, enhancement

#642 chore: update ci to v3.1.20
  Earthfile
  catalyst-gateway-crates/c509-certificate/Earthfile
  catalyst-gateway/Earthfile
  catalyst-gateway/event-db/Earthfile
  catalyst-gateway/tests/Earthfile
  catalyst-gateway/tests/api_tests/Earthfile
  catalyst_voices/Earthfile
  catalyst_voices/uikit_example/Earthfile
  docs/Earthfile
Labels: review me

#647 fix!: signData return type should be DataSignature, not VkeyWitness
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano/example/lib/sign_data.dart
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_platform_interface/lib/src/cardano_wallet.dart
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_web/lib/src/interop/catalyst_cardano_interop.dart
  catalyst_voices_packages/catalyst_cardano/catalyst_cardano_web/lib/src/interop/catalyst_cardano_wallet_proxy.dart
Labels: review me, dart

#643 feat!: update transactions inputs hash size
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/hashes.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/rbac/x509_metadata_envelope.dart
  catalyst_voices_packages/catalyst_cardano_serialization/test/hashes_test.dart
Labels: review me, dart
