Repository input-output-hk/catalyst-voices, pull requests merged in 2024-05, with the labels that each got.

#431 feat: Add initial brand support
  catalyst_voices/packages/catalyst_voices_blocs/lib/src/brand/brand.dart
  catalyst_voices/packages/catalyst_voices_blocs/lib/src/brand/brand_bloc.dart
  catalyst_voices/packages/catalyst_voices_blocs/lib/src/brand/brand_event.dart
  catalyst_voices/packages/catalyst_voices_blocs/lib/src/brand/brand_state.dart
  catalyst_voices/packages/catalyst_voices_blocs/lib/src/catalyst_voices_blocs.dart
  catalyst_voices/packages/catalyst_voices_blocs/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_brands/.gitignore
  catalyst_voices/packages/catalyst_voices_brands/README.md
  catalyst_voices/packages/catalyst_voices_brands/analysis_options.yaml
  catalyst_voices/packages/catalyst_voices_brands/lib/catalyst_voices_brands.dart
  catalyst_voices/packages/catalyst_voices_brands/lib/src/brands/brands.dart
  catalyst_voices/packages/catalyst_voices_brands/lib/src/catalyst_voices_brands.dart
  catalyst_voices/packages/catalyst_voices_brands/lib/src/theme_builder/theme_builder.dart
  catalyst_voices/packages/catalyst_voices_brands/lib/src/themes/catalyst.dart
  catalyst_voices/packages/catalyst_voices_brands/lib/src/themes/fallback.dart
  catalyst_voices/packages/catalyst_voices_brands/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_brands/test/src/catalyst_voices_brands_test.dart
Labels: review me

#460 fix: add sig check
  catalyst-gateway/bin/Cargo.toml
  catalyst-gateway/bin/src/cardano/cip36_registration/mod.rs
  catalyst-gateway/bin/src/cardano/util.rs
  catalyst-gateway/bin/src/event_db/cardano/cip36_registration/mod.rs
  catalyst-gateway/tests/api_tests/snapshot_tool-56364174.json
Labels: review me

#466 feat: Testcase and testplan templates
  .config/dictionaries/project.dic
  .github/ISSUE_TEMPLATE/test_case.yml
  .github/ISSUE_TEMPLATE/test_plan.yml
  docs/src/architecture/.pages
  docs/src/architecture/10_quality/.pages
  docs/src/architecture/10_quality/index.md
  docs/src/architecture/10_quality/quality_requirements.md
  docs/src/architecture/10_quality/test_reports.md
  docs/src/architecture/10_quality/testplans/template.md
  docs/src/index.md
Labels: review me

#474 feat: Bump pallas version
  catalyst-gateway/Cargo.lock
  catalyst-gateway/Cargo.toml
Labels: review me

#473 docs(CIPs): Move CIPs and submit them for review
  .config/dictionaries/project.dic
  docs/src/catalyst-standards/draft-cips/c509-plutus-restricted-certificate/cip-509C.md
  docs/src/catalyst-standards/draft-cips/project-catalyst-x509-role-defintions/cip-catalyst-roles.md
  docs/src/catalyst-standards/draft-cips/x509-envelope-metadata/cip-509A.md
  docs/src/catalyst-standards/draft-cips/x509-rbac-signing-with-cip30/cip-x509D.md
  docs/src/catalyst-standards/draft-cips/x509-role-registration-metadata/cip-509B.md
Labels: review me

#487 feat: lock specific flutter version on ci
  catalyst_voices/Earthfile
Labels: review me

#478 feat: add shelley address & cardano serialization lib
  .config/dictionaries/project.dic
  catalyst_voices/pubspec.yaml
  catalyst_voices_packages/catalyst_cardano_serialization/CHANGELOG.md
  catalyst_voices_packages/catalyst_cardano_serialization/README.md
  catalyst_voices_packages/catalyst_cardano_serialization/analysis_options.yaml
  catalyst_voices_packages/catalyst_cardano_serialization/lib/catalyst_cardano_serialization.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/address.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/exceptions.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/fees.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/hashes.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/transaction.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/types.dart
  catalyst_voices_packages/catalyst_cardano_serialization/pubspec.yaml
  catalyst_voices_packages/catalyst_cardano_serialization/test/address_test.dart
  catalyst_voices_packages/catalyst_cardano_serialization/test/fees_test.dart
  catalyst_voices_packages/catalyst_cardano_serialization/test/hashes_test.dart
  catalyst_voices_packages/catalyst_cardano_serialization/test/transaction_test.dart
  catalyst_voices_packages/catalyst_cardano_serialization/test/types_test.dart
  catalyst_voices_packages/catalyst_cardano_serialization/test/utils/test_data.dart
  melos.yaml
Labels: review me

#479 feat: Add Catalyst Brand M3 Theme definition
  .config/dictionaries/project.dic
  catalyst_voices/lib/pages/coming_soon/description.dart
  catalyst_voices/lib/pages/coming_soon/logo.dart
  catalyst_voices/lib/pages/coming_soon/title.dart
  catalyst_voices/lib/pages/home/home_page.dart
  catalyst_voices/packages/catalyst_voices_assets/assets/colors/colors.xml
  catalyst_voices/packages/catalyst_voices_assets/example/lib/src/main.dart
  catalyst_voices/packages/catalyst_voices_assets/lib/generated/colors.gen.dart
  catalyst_voices/packages/catalyst_voices_brands/lib/src/theme_builder/theme_builder.dart
  catalyst_voices/packages/catalyst_voices_brands/lib/src/themes/catalyst.dart
  catalyst_voices/packages/catalyst_voices_brands/lib/src/themes/fallback.dart
  catalyst_voices/packages/catalyst_voices_brands/lib/src/themes/voices_color_scheme.dart
  catalyst_voices/packages/catalyst_voices_brands/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_brands/test/src/catalyst_voices_brands_test.dart
Labels: review me

#490 feat: catalyst cardano witnesses management
  .config/dictionaries/project.dic
  catalyst_voices_packages/catalyst_cardano_serialization/lib/catalyst_cardano_serialization.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/exceptions.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/hashes.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/transaction.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/types.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/utils/cbor.dart
  catalyst_voices_packages/catalyst_cardano_serialization/lib/src/witness.dart
  catalyst_voices_packages/catalyst_cardano_serialization/test/address_test.dart
  catalyst_voices_packages/catalyst_cardano_serialization/test/fees_test.dart
  catalyst_voices_packages/catalyst_cardano_serialization/test/hashes_test.dart
  catalyst_voices_packages/catalyst_cardano_serialization/test/test_utils/test_data.dart
  catalyst_voices_packages/catalyst_cardano_serialization/test/transaction_test.dart
  catalyst_voices_packages/catalyst_cardano_serialization/test/utils/cbor_test.dart
  catalyst_voices_packages/catalyst_cardano_serialization/test/witness_test.dart
Labels: review me

#464 fix: Missing `Content-Type` header in responses issue,
  catalyst-gateway/Cargo.toml
  catalyst-gateway/bin/Cargo.toml
  catalyst-gateway/bin/src/cardano/util.rs
  catalyst-gateway/bin/src/cli.rs
  catalyst-gateway/bin/src/service/api/cardano/date_time_to_slot_number_get.rs
  catalyst-gateway/bin/src/service/api/cardano/mod.rs
  catalyst-gateway/bin/src/service/api/cardano/registration_get.rs
  catalyst-gateway/bin/src/service/api/cardano/staked_ada_get.rs
  catalyst-gateway/bin/src/service/api/cardano/sync_state_get.rs
  catalyst-gateway/bin/src/service/api/health/live_get.rs
  catalyst-gateway/bin/src/service/api/health/mod.rs
  catalyst-gateway/bin/src/service/api/health/ready_get.rs
  catalyst-gateway/bin/src/service/api/health/started_get.rs
  catalyst-gateway/bin/src/service/api/legacy/registration/mod.rs
  catalyst-gateway/bin/src/service/api/legacy/v0/message_post.rs
  catalyst-gateway/bin/src/service/api/legacy/v0/plans_get.rs
  catalyst-gateway/bin/src/service/api/legacy/v1/account_votes_get.rs
  catalyst-gateway/bin/src/service/api/legacy/v1/fragments_post.rs
  catalyst-gateway/bin/src/service/api/legacy/v1/fragments_statuses.rs
  catalyst-gateway/bin/src/service/api/mod.rs
  catalyst-gateway/bin/src/service/api/test_endpoints/mod.rs
  catalyst-gateway/bin/src/service/api/test_endpoints/test_get.rs
  catalyst-gateway/bin/src/service/api/test_endpoints/test_post.rs
  catalyst-gateway/bin/src/service/common/objects/cardano/slot_info.rs
  catalyst-gateway/bin/src/service/common/objects/mod.rs
  catalyst-gateway/bin/src/service/common/objects/server_error.rs
  catalyst-gateway/bin/src/service/common/objects/validation_error.rs
  catalyst-gateway/bin/src/service/common/responses/mod.rs
  catalyst-gateway/bin/src/service/common/responses/resp_2xx.rs
  catalyst-gateway/bin/src/service/common/responses/resp_4xx.rs
  catalyst-gateway/bin/src/service/common/responses/resp_5xx.rs
  catalyst-gateway/bin/src/service/common/tags.rs
  catalyst-gateway/bin/src/service/mod.rs
  catalyst-gateway/bin/src/service/utilities/catch_panic.rs
  catalyst-gateway/bin/src/service/utilities/middleware/schema_validation.rs
  catalyst-gateway/bin/src/service/utilities/mod.rs
  catalyst-gateway/tests/Earthfile
  catalyst-gateway/tests/api_tests/api_tests/__init__.py
  catalyst-gateway/tests/api_tests/docker-compose.yml
  catalyst-gateway/tests/schemathesis-docker-compose.yml
  catalyst_voices/packages/catalyst_voices_services/lib/generated/catalyst_gateway/cat_gateway_api.enums.swagger.dart
  catalyst_voices/packages/catalyst_voices_services/lib/generated/catalyst_gateway/cat_gateway_api.models.swagger.dart
  catalyst_voices/packages/catalyst_voices_services/lib/generated/catalyst_gateway/cat_gateway_api.models.swagger.g.dart
  catalyst_voices/packages/catalyst_voices_services/lib/generated/catalyst_gateway/cat_gateway_api.swagger.chopper.dart
  catalyst_voices/packages/catalyst_voices_services/lib/generated/catalyst_gateway/cat_gateway_api.swagger.dart
Labels: review me

#500 fix(wallet-tester): missing configurable aux hash and network ID
  utilities/wallet-tester/src/common/components/TxBuilder.tsx
  utilities/wallet-tester/src/common/helpers/buildUnsignedTx.ts
  utilities/wallet-tester/src/common/helpers/getCardano.ts
Labels: bug, review me

#498 feat: Add svg support to flutter
  catalyst_voices/lib/pages/coming_soon/logo.dart
  catalyst_voices/packages/catalyst_voices_assets/assets/images/catalyst_logo.svg
  catalyst_voices/packages/catalyst_voices_assets/assets/images/logo.webp
  catalyst_voices/packages/catalyst_voices_assets/lib/generated/assets.gen.dart
  catalyst_voices/packages/catalyst_voices_assets/lib/src/catalyst_image.dart
  catalyst_voices/packages/catalyst_voices_assets/lib/src/catalyst_svg_picture.dart
  catalyst_voices/packages/catalyst_voices_assets/lib/src/catalyst_voices_assets.dart
  catalyst_voices/packages/catalyst_voices_assets/pubspec.yaml
Labels: review me

#507 feat: catalyst cardano documentation
  catalyst_voices_packages/catalyst_cardano_serialization/README.md
Labels: review me

#517 feat: Add brand specific assets
  catalyst_voices/packages/catalyst_voices_assets/assets/images/catalyst_logo_icon.svg
  catalyst_voices/packages/catalyst_voices_assets/assets/images/catalyst_logo_icon_white.svg
  catalyst_voices/packages/catalyst_voices_assets/assets/images/catalyst_logo_white.svg
  catalyst_voices/packages/catalyst_voices_assets/assets/images/fallback_logo.svg
  catalyst_voices/packages/catalyst_voices_assets/assets/images/fallback_logo_icon.svg
  catalyst_voices/packages/catalyst_voices_assets/lib/generated/assets.gen.dart
  catalyst_voices/packages/catalyst_voices_assets/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_brands/lib/src/theme_extensions/brand_assets.dart
  catalyst_voices/packages/catalyst_voices_brands/lib/src/theme_extensions/voices_color_scheme.dart
  catalyst_voices/packages/catalyst_voices_brands/lib/src/themes/catalyst.dart
  catalyst_voices/packages/catalyst_voices_brands/lib/src/themes/fallback.dart
  catalyst_voices/packages/catalyst_voices_brands/test/src/catalyst_voices_brands_test.dart
Labels: review me

#476 feat: Selectable db query performance logging
  .config/dictionaries/project.dic
  catalyst-gateway/Cargo.toml
  catalyst-gateway/bin/Cargo.toml
  catalyst-gateway/bin/src/cli.rs
  catalyst-gateway/bin/src/event_db/cardano/chain_state/mod.rs
  catalyst-gateway/bin/src/event_db/cardano/cip36_registration/mod.rs
  catalyst-gateway/bin/src/event_db/cardano/config/mod.rs
  catalyst-gateway/bin/src/event_db/cardano/utxo/mod.rs
  catalyst-gateway/bin/src/event_db/legacy/queries/event/ballot.rs
  catalyst-gateway/bin/src/event_db/legacy/queries/event/mod.rs
  catalyst-gateway/bin/src/event_db/legacy/queries/event/objective.rs
  catalyst-gateway/bin/src/event_db/legacy/queries/event/proposal.rs
  catalyst-gateway/bin/src/event_db/legacy/queries/event/review.rs
  catalyst-gateway/bin/src/event_db/legacy/queries/registration.rs
  catalyst-gateway/bin/src/event_db/legacy/queries/search.rs
  catalyst-gateway/bin/src/event_db/legacy/queries/vit_ss/fund.rs
  catalyst-gateway/bin/src/event_db/mod.rs
  catalyst-gateway/bin/src/event_db/schema_check/mod.rs
  catalyst-gateway/bin/src/logger.rs
  catalyst-gateway/bin/src/main.rs
  catalyst-gateway/bin/src/service/api/health/inspection_get.rs
  catalyst-gateway/bin/src/service/api/health/mod.rs
  catalyst-gateway/bin/src/service/common/responses/mod.rs
  catalyst-gateway/bin/src/settings.rs
  catalyst-gateway/bin/src/state/mod.rs
  catalyst-gateway/tests/api_tests/api_tests/__init__.py
  catalyst_voices/Earthfile
  catalyst_voices/packages/catalyst_voices_services/lib/generated/catalyst_gateway/cat_gateway_api.enums.swagger.dart
  catalyst_voices/packages/catalyst_voices_services/lib/generated/catalyst_gateway/cat_gateway_api.models.swagger.dart
  catalyst_voices/packages/catalyst_voices_services/lib/generated/catalyst_gateway/cat_gateway_api.swagger.chopper.dart
  catalyst_voices/packages/catalyst_voices_services/lib/generated/catalyst_gateway/cat_gateway_api.swagger.dart
Labels: enhancement, review me
