Repository input-output-hk/catalyst-voices, pull requests merged in 2024-02, with the labels that each got.

#230 feat: add platform detection
  catalyst_voices/ios/Flutter/AppFrameworkInfo.plist
  catalyst_voices/ios/Podfile.lock
  catalyst_voices/lib/routes/app_router.dart
  catalyst_voices/packages/catalyst_voices_shared/lib/src/catalyst_voices_shared.dart
  catalyst_voices/packages/catalyst_voices_shared/lib/src/platform/catalyst_platform.dart
  catalyst_voices/packages/catalyst_voices_shared/lib/src/platform/io_platform.dart
  catalyst_voices/packages/catalyst_voices_shared/lib/src/platform/stub_platform.dart
  catalyst_voices/packages/catalyst_voices_shared/lib/src/platform/web_platform.dart
  catalyst_voices/packages/catalyst_voices_shared/pubspec.yaml
Labels: review me

#231 chore: flutter, dart bump, fix crash caused localization context
  catalyst_voices/lib/app/view/app_content.dart
  catalyst_voices/packages/catalyst_voices_assets/example/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_assets/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_blocs/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_localization/lib/generated/catalyst_voices_localizations_es.dart
  catalyst_voices/packages/catalyst_voices_localization/lib/l10n/intl_es.arb
  catalyst_voices/packages/catalyst_voices_localization/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_models/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_repositories/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_services/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_shared/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_view_models/pubspec.yaml
  catalyst_voices/pubspec.yaml
  melos.yaml
  pubspec.yaml
Labels: review me

#236 fix: get server for Openapi specification
  .config/dictionaries/project.dic
  catalyst-gateway/Cargo.lock
  catalyst-gateway/Cargo.toml
  catalyst-gateway/bin/Cargo.toml
  catalyst-gateway/bin/src/cli.rs
  catalyst-gateway/bin/src/service/api/mod.rs
  catalyst-gateway/bin/src/service/mod.rs
  catalyst-gateway/bin/src/service/poem_service.rs
  catalyst-gateway/bin/src/settings.rs
Labels: documentation, enhancement

#229 fix: openapi specification
  catalyst-gateway/bin/src/event_db/types/ballot.rs
  catalyst-gateway/bin/src/service/api/health/live_get.rs
  catalyst-gateway/bin/src/service/api/health/ready_get.rs
  catalyst-gateway/bin/src/service/api/health/started_get.rs
  catalyst-gateway/bin/src/service/api/registration/mod.rs
  catalyst-gateway/bin/src/service/api/test_endpoints/mod.rs
  catalyst-gateway/bin/src/service/api/test_endpoints/test_get.rs
  catalyst-gateway/bin/src/service/api/test_endpoints/test_post.rs
  catalyst-gateway/bin/src/service/api/v0/mod.rs
  catalyst-gateway/bin/src/service/api/v0/plans_get.rs
  catalyst-gateway/bin/src/service/api/v1/account_votes_get.rs
  catalyst-gateway/bin/src/service/api/v1/fragments_post.rs
  catalyst-gateway/bin/src/service/api/v1/fragments_statuses.rs
  catalyst-gateway/bin/src/service/api/v1/mod.rs
  catalyst-gateway/bin/src/service/common/objects/account_votes.rs
  catalyst-gateway/bin/src/service/common/objects/block.rs
  catalyst-gateway/bin/src/service/common/objects/delegate_public_key.rs
  catalyst-gateway/bin/src/service/common/objects/fragment_status.rs
  catalyst-gateway/bin/src/service/common/objects/fragments_batch.rs
  catalyst-gateway/bin/src/service/common/objects/fragments_processing_summary.rs
  catalyst-gateway/bin/src/service/common/objects/hash.rs
  catalyst-gateway/bin/src/service/common/objects/vote_plan.rs
  catalyst-gateway/bin/src/service/common/objects/voter_info.rs
  catalyst-gateway/bin/src/service/common/objects/voting_public_key.rs
  catalyst-gateway/bin/src/service/common/responses/resp_2xx.rs
  catalyst-gateway/bin/src/service/common/responses/resp_5xx.rs
  catalyst-gateway/tests/integration/catalyst_gateway_event_db.rs
Labels: documentation, enhancement

#208 feat: add openapi linter
  catalyst-gateway/.spectral.yml
  catalyst-gateway/Earthfile
Labels: enhancement

#235 docs: Cursor-based pagination ADR
  .github/workflows/flutter-web-integration-test.yml
  docs/src/architecture/09_architecture_decisions/0006-cursor-pegination-cat-data-service.md
Labels: documentation, review me

#251 chore: bump kotlin version
  catalyst_voices/android/build.gradle
Labels: review me

#253 fix: Deprecating legacy vote endpoints
  README.md
  catalyst-gateway/bin/src/event_db/mod.rs
  catalyst-gateway/bin/src/event_db/queries/mod.rs
  catalyst-gateway/bin/src/event_db/schema_check.rs
  catalyst-gateway/bin/src/service/api/registration/mod.rs
  catalyst-gateway/bin/src/service/api/v0/mod.rs
  catalyst-gateway/bin/src/service/api/v1/mod.rs
  catalyst-gateway/bin/src/state/mod.rs
  catalyst_voices/android/build.gradle
Labels: review me

#248 refactor: Fix api fuzzer and refactor tests
  .config/dictionaries/project.dic
  README.md
  catalyst-gateway/Cargo.lock
  catalyst-gateway/Cargo.toml
  catalyst-gateway/Earthfile
  catalyst-gateway/bin/src/event_db/mod.rs
  catalyst-gateway/bin/src/event_db/queries/mod.rs
  catalyst-gateway/bin/src/event_db/schema_check.rs
  catalyst-gateway/bin/src/service/api/registration/mod.rs
  catalyst-gateway/bin/src/service/api/v0/mod.rs
  catalyst-gateway/bin/src/service/api/v1/mod.rs
  catalyst-gateway/bin/src/state/mod.rs
  catalyst-gateway/tests/.spectral.yml
  catalyst-gateway/tests/Cargo.toml
  catalyst-gateway/tests/Earthfile
  catalyst-gateway/tests/integration/catalyst_gateway_event_db.rs
  catalyst-gateway/tests/integration/main.rs
  catalyst-gateway/tests/schema-mismatch/Earthfile
  catalyst-gateway/tests/schemathesis-docker-compose.yml
Labels: review me

#256 chore: bump flutter and dart version
  catalyst_voices/packages/catalyst_voices_assets/example/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_assets/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_blocs/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_localization/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_repositories/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_services/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_shared/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_view_models/pubspec.yaml
  catalyst_voices/pubspec.yaml
  catalyst_voices_packages/catalyst_analysis/example/pubspec.yaml
  catalyst_voices_packages/catalyst_analysis/pubspec.yaml
  melos.yaml
  pubspec.yaml
Labels: review me

#263 feat(ci): add earthfile for voices fronted
  .config/dictionaries/project.dic
  catalyst_voices/.gitignore
  catalyst_voices/Earthfile
  catalyst_voices/README.md
  catalyst_voices/lib/configs/main_web.dart
  catalyst_voices/nginx.conf
  catalyst_voices/pubspec.yaml
Labels: review me

#264 chore: update flutter to 3.19.1
  catalyst_voices/packages/catalyst_voices_assets/example/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_assets/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_blocs/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_localization/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_repositories/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_services/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_shared/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_view_models/pubspec.yaml
  catalyst_voices/pubspec.yaml
  melos.yaml
Labels: review me

#260 feat: Gateway follower bootstrap
  .config/dictionaries/project.dic
  catalyst-gateway/Cargo.lock
  catalyst-gateway/Earthfile
  catalyst-gateway/bin/Cargo.toml
  catalyst-gateway/bin/src/cli.rs
  catalyst-gateway/bin/src/event_db/config.rs
  catalyst-gateway/bin/src/event_db/error.rs
  catalyst-gateway/bin/src/event_db/follower.rs
  catalyst-gateway/bin/src/event_db/mod.rs
  catalyst-gateway/bin/src/follower.rs
  catalyst-gateway/bin/src/main.rs
  catalyst-gateway/bin/src/service/utilities/catch_panic.rs
  catalyst-gateway/bin/src/settings.rs
  catalyst-gateway/deny.toml
  catalyst-gateway/event-db/Earthfile
  catalyst-gateway/event-db/migrations/V1__config_tables.sql
  catalyst-gateway/event-db/migrations/V6__registration.sql
  catalyst-gateway/tests/schema-mismatch/Earthfile
  catalyst-gateway/tests/schema-mismatch/docker-compose.yml
  catalyst-gateway/tests/schemathesis-docker-compose.yml
  docs/src/architecture/08_concepts/gateway/concrete.md
Labels: review me
