Repository input-output-hk/catalyst-voices, pull requests merged in 2024-03, with the labels that each got.

#275 feat: Adds allure test report
  .config/dictionaries/project.dic
  .github/workflows/generate-allure-report.yml
  catalyst-gateway/Cargo.lock
  catalyst-gateway/tests/Earthfile
  docs/src/index.md
Labels: review me

#294 feat: Voter registration insert query
  Earthfile
  catalyst-gateway/Earthfile
  catalyst-gateway/bin/src/event_db/config_table.rs
  catalyst-gateway/bin/src/event_db/mod.rs
  catalyst-gateway/bin/src/event_db/voter_registration.rs
  catalyst-gateway/event-db/Earthfile
  catalyst-gateway/event-db/queries/voter_registration/insert_voter_registration.sql
Labels: review me

#298 fix: kroki ci errors
  .config/dictionaries/project.dic
  .vscode/extensions.json
  docs/Earthfile
  docs/src/api/cat-gateway/rust.md
Labels: bug, documentation

#297 refactor: Cleanup catalyst-gateway event-db queries
  catalyst-gateway/Cargo.lock
  catalyst-gateway/bin/Cargo.toml
  catalyst-gateway/bin/src/cli.rs
  catalyst-gateway/bin/src/event_db/config.rs
  catalyst-gateway/bin/src/event_db/follower.rs
  catalyst-gateway/bin/src/event_db/legacy/queries/event/ballot.rs
  catalyst-gateway/bin/src/event_db/legacy/queries/event/mod.rs
  catalyst-gateway/bin/src/event_db/legacy/queries/event/objective.rs
  catalyst-gateway/bin/src/event_db/legacy/queries/event/proposal.rs
  catalyst-gateway/bin/src/event_db/legacy/queries/event/review.rs
  catalyst-gateway/bin/src/event_db/legacy/queries/registration.rs
  catalyst-gateway/bin/src/event_db/legacy/queries/search.rs
  catalyst-gateway/bin/src/event_db/legacy/queries/vit_ss/fund.rs
  catalyst-gateway/bin/src/event_db/schema_check.rs
  catalyst-gateway/bin/src/event_db/utxo.rs
  catalyst-gateway/bin/src/follower.rs
  catalyst-gateway/bin/src/service/utilities/middleware/tracing_mw.rs
  catalyst-gateway/event-db/Readme.md
  catalyst-gateway/event-db/migrations/V6__registration.sql
  catalyst-gateway/event-db/queries/config/select_config.sql
  catalyst-gateway/event-db/queries/follower/insert_slot_index.sql
  catalyst-gateway/event-db/queries/follower/insert_update_state.sql
  catalyst-gateway/event-db/queries/follower/select_update_state.sql
  catalyst-gateway/event-db/queries/follower/utxo_index_utxo_query.sql
  catalyst-gateway/event-db/queries/follower/utxo_txn_index.sql
  catalyst-gateway/event-db/queries/schema_check/select_max_version.sql
Labels: enhancement

#319 feat: Add PlatformWidgetBuilder.
  catalyst_voices/packages/catalyst_voices_shared/lib/src/catalyst_voices_shared.dart
  catalyst_voices/packages/catalyst_voices_shared/lib/src/platform/io_platform.dart
  catalyst_voices/packages/catalyst_voices_shared/lib/src/platform/platform_key.dart
  catalyst_voices/packages/catalyst_voices_shared/lib/src/platform/stub_platform.dart
  catalyst_voices/packages/catalyst_voices_shared/lib/src/platform/web_platform.dart
  catalyst_voices/packages/catalyst_voices_shared/lib/src/platform_aware_builder/platform_aware_builder.dart
  catalyst_voices/packages/catalyst_voices_shared/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_shared/test/src/catalyst_voices_shared_test.dart
  catalyst_voices/packages/catalyst_voices_shared/test/src/platform_aware_builder/platform_aware_builder_test.dart
Labels: review me

#331 feat: Add ResponsiveBuilder widget.
  catalyst_voices/packages/catalyst_voices_shared/lib/src/responsive_builder/responsive_breakpoint_key.dart
  catalyst_voices/packages/catalyst_voices_shared/lib/src/responsive_builder/responsive_builder.dart
  catalyst_voices/packages/catalyst_voices_shared/test/src/responsive_builder_test.dart
Labels: review me

#325 feat: Total utxo staked ada amount
  .config/dictionaries/project.dic
  catalyst-gateway/Cargo.toml
  catalyst-gateway/bin/src/event_db/follower.rs
  catalyst-gateway/bin/src/event_db/utxo.rs
  catalyst-gateway/bin/src/event_db/voter_registration.rs
  catalyst-gateway/bin/src/follower.rs
  catalyst-gateway/bin/src/service/api/mod.rs
  catalyst-gateway/bin/src/service/api/utxo/mod.rs
  catalyst-gateway/bin/src/service/api/utxo/staked_ada_get.rs
  catalyst-gateway/bin/src/service/common/objects/cardano_address.rs
  catalyst-gateway/bin/src/service/common/objects/mod.rs
  catalyst-gateway/bin/src/service/common/objects/network.rs
  catalyst-gateway/bin/src/service/common/objects/stake_amount.rs
  catalyst-gateway/bin/src/service/common/responses/resp_4xx.rs
  catalyst-gateway/bin/src/service/common/tags.rs
  catalyst-gateway/bin/src/state/mod.rs
  catalyst-gateway/event-db/migrations/V6__registration.sql
  catalyst-gateway/event-db/queries/utxo/insert_txn_index.sql
  catalyst-gateway/event-db/queries/utxo/insert_utxo.sql
  catalyst-gateway/event-db/queries/utxo/select_total_utxo_amount.sql
  catalyst-gateway/tests/.spectral.yml
  catalyst-gateway/tests/Earthfile
  catalyst-gateway/tests/schema-mismatch/Earthfile
Labels: review me

#340 feat: bump ci to 3.0.0
  catalyst-gateway/Earthfile
  catalyst-gateway/event-db/Earthfile
  docs/Earthfile
Labels: review me

#339 refactor: Add `anyhow` error handling
  catalyst-gateway/Cargo.lock
  catalyst-gateway/Cargo.toml
  catalyst-gateway/bin/Cargo.toml
  catalyst-gateway/bin/src/cli.rs
  catalyst-gateway/bin/src/follower.rs
  catalyst-gateway/bin/src/logger.rs
  catalyst-gateway/bin/src/util.rs
Labels: review me

#324 feat: add DynamicPadding widget.
  catalyst_voices/packages/catalyst_voices_shared/lib/src/catalyst_voices_shared.dart
  catalyst_voices/packages/catalyst_voices_shared/lib/src/responsive_padding/responsive_padding.dart
  catalyst_voices/packages/catalyst_voices_shared/test/src/catalyst_voices_shared_test.dart
  catalyst_voices/packages/catalyst_voices_shared/test/src/platform_aware_builder_test.dart
  catalyst_voices/packages/catalyst_voices_shared/test/src/responsive_padding_test.dart
Labels: review me

#342 feat: Add `ResponsiveChild`.
  catalyst_voices/packages/catalyst_voices_shared/lib/src/catalyst_voices_shared.dart
  catalyst_voices/packages/catalyst_voices_shared/lib/src/responsive/responsive_breakpoint_key.dart
  catalyst_voices/packages/catalyst_voices_shared/lib/src/responsive/responsive_builder.dart
  catalyst_voices/packages/catalyst_voices_shared/lib/src/responsive/responsive_child.dart
  catalyst_voices/packages/catalyst_voices_shared/lib/src/responsive/responsive_padding.dart
  catalyst_voices/packages/catalyst_voices_shared/test/src/platform_aware_builder_test.dart
  catalyst_voices/packages/catalyst_voices_shared/test/src/responsive_builder_test.dart
  catalyst_voices/packages/catalyst_voices_shared/test/src/responsive_child_test.dart
Labels: review me

#358 chore: upgrade flutter to 3.19.5
  catalyst_voices/packages/catalyst_voices_assets/example/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_assets/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_blocs/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_localization/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_repositories/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_services/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_shared/pubspec.yaml
  catalyst_voices/packages/catalyst_voices_view_models/pubspec.yaml
  catalyst_voices/pubspec.yaml
  catalyst_voices_packages/catalyst_analysis/example/pubspec.yaml
  catalyst_voices_packages/catalyst_analysis/pubspec.yaml
  melos.yaml
  pubspec.yaml
Labels: review me

#357 feat: setup code generation
  Earthfile
  catalyst_voices/Earthfile
  catalyst_voices/packages/catalyst_voices_services/README.md
  catalyst_voices/packages/catalyst_voices_services/build.yaml
  catalyst_voices/packages/catalyst_voices_services/lib/generated/catalyst_gateway/cat_gateway_api.enums.swagger.dart
  catalyst_voices/packages/catalyst_voices_services/lib/generated/catalyst_gateway/cat_gateway_api.models.swagger.dart
  catalyst_voices/packages/catalyst_voices_services/lib/generated/catalyst_gateway/cat_gateway_api.models.swagger.g.dart
  catalyst_voices/packages/catalyst_voices_services/lib/generated/catalyst_gateway/cat_gateway_api.swagger.chopper.dart
  catalyst_voices/packages/catalyst_voices_services/lib/generated/catalyst_gateway/cat_gateway_api.swagger.dart
  catalyst_voices/packages/catalyst_voices_services/lib/generated/catalyst_gateway/client_index.dart
  catalyst_voices/packages/catalyst_voices_services/lib/generated/catalyst_gateway/client_mapping.dart
  catalyst_voices/packages/catalyst_voices_services/pubspec.yaml
Labels: review me
