Repository input-output-hk/catalyst-voices, pull requests merged in 2025-07, with the labels that each got.

#2917 feat(cat-gateway): Temporary fix for removed stake addresses
  catalyst-gateway/bin/src/rbac/get_chain.rs
Labels: review me, rust, squad: gatekeepers, rr: gatekeepers

#2926 chore(general): update ci to v3.4.4
  .config/dictionaries/project.dic
  Earthfile
  catalyst-gateway/Earthfile
  catalyst-gateway/deny.toml
  catalyst-gateway/event-db/Earthfile
  catalyst-gateway/tests/Earthfile
  catalyst-gateway/tests/api_tests/Earthfile
  catalyst_voices/Earthfile
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/wallet-automation/Earthfile
  catalyst_voices/packages/libs/catalyst_key_derivation/Earthfile
  catalyst_voices/packages/libs/catalyst_key_derivation/rust/Earthfile
  catalyst_voices/packages/libs/catalyst_key_derivation/rust/deny.toml
  catalyst_voices/utilities/uikit_example/Earthfile
  docs/Earthfile
  utilities/docs-preview/Earthfile
Labels: review me

#2901 docs(cat-voices): documentation `catalyst_voices_blocs`
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/account/account_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/account/public_profile/public_profile_email_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/campaign/campaign_stage/campaign_stage_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/category/category_detail_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/common/bloc_error_emitter_mixin.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/common/bloc_signal_emitter_mixin.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/dev_tools/dev_tools_bloc.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/dev_tools/document_lookup/document_lookup_bloc.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/discovery/discovery_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/document/document_to_segment_mixin.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal/proposal_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal/proposal_cubit_cache.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal/proposal_signal.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/new_proposal/new_proposal_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/proposal_builder_bloc.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/proposal_builder_signal.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposals/proposals_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/registration/cubits/base_profile_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/registration/cubits/keychain_creation_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/registration/cubits/recover_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/registration/cubits/wallet_link_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/session/session_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/workspace/workspace_bloc.dart
Labels: documentation, review me, squad: face

#2916 chore(cat-voices): build runner 2.5.4 update and kirk-check
  catalyst_voices/apps/voices/pubspec.yaml
  catalyst_voices/melos.yaml
  catalyst_voices/packages/internal/catalyst_voices_assets/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_models/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_repositories/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cardano_serialization/pubspec.yaml
  catalyst_voices/utilities/uikit_example/pubspec.yaml
Labels: review me, squad: face

#2951 chore: update dates for rc6
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/campaign/campaign_timeline.dart
Labels: review me

#2947 feat(cat-voices): dartdoc internal packages documentation
  .config/dictionaries/project.dic
  catalyst_voices/.gitignore
  catalyst_voices/Earthfile
  catalyst_voices/dartdoc_options.yaml
  catalyst_voices/docs/dependency_graph.dot
  catalyst_voices/docs/licenses/licenses.csv
  catalyst_voices/justfile
  catalyst_voices/melos.yaml
Labels: review me, squad: face

#2845 fix(cat-gateway): Remove Chain Follower metrics network prefix names
  catalyst-gateway/bin/src/metrics/chain_follower/mod.rs
  catalyst-gateway/bin/src/metrics/chain_follower/reporter.rs
Labels: review me, rust, requires architecture review, squad: gatekeepers

#2954 fix(cat-gateway): Correct `immutable_tip` notifying behaviour, when index-db is already indexed
  catalyst-gateway/bin/src/cardano/mod.rs
  catalyst-gateway/bin/src/service/utilities/health/start.rs
Labels: review me, squad: gatekeepers, rr: gatekeepers

#2991 feat(cat-voices): removing last category description from Partners and Products
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/campaign/campaign_category.dart
Labels: review me, F14-RC4, squad: face

#2977 feat(cat-gateway): Health endpoint metrics
  catalyst-gateway/bin/src/metrics/health.rs
  catalyst-gateway/bin/src/metrics/mod.rs
  catalyst-gateway/bin/src/service/api/cardano/cip36/endpoint.rs
  catalyst-gateway/bin/src/service/api/cardano/rbac/registrations_get/mod.rs
  catalyst-gateway/bin/src/service/api/health/live_get.rs
  catalyst-gateway/bin/src/service/api/health/mod.rs
  catalyst-gateway/bin/src/service/api/health/ready_get.rs
  catalyst-gateway/bin/src/service/api/health/started_get.rs
  catalyst-gateway/bin/src/service/api/mod.rs
  catalyst-gateway/bin/src/service/common/responses/mod.rs
  catalyst-gateway/bin/src/service/mod.rs
  catalyst-gateway/bin/src/service/poem_service.rs
  catalyst-gateway/bin/src/service/utilities/middleware/metrics_updater.rs
Labels: review me, squad: gatekeepers

#2997 feat(cat-voices): custom helper text for milestone cost
  catalyst_voices/apps/voices/lib/common/constants/constants.dart
  catalyst_voices/apps/voices/lib/widgets/document_builder/value/document_token_value_widget.dart
  catalyst_voices/apps/voices/lib/widgets/text_field/token_field.dart
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/specialized/proposal_document.dart
Labels: review me, squad: face, a: proposal editor

#3007 feat(cat-gateway): Bumping `cat-libs` versions
  catalyst-gateway/bin/Cargo.toml
Labels: review me

#3005 fix(cat-voices): get proper base url for share proposal
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/config/app_environment.dart
Labels: review me, squad: face, F14-RC6

#3012 fix(cat-voices): pagination numbering
  catalyst_voices/apps/voices/lib/widgets/pagination/paging_state.dart
Labels: review me, squad: face, F14-RC6

#2959 fix: disable nightly ci
  .github/workflows/nightly-ci.yml
  catalyst-gateway/tests/schemathesis_tests/Earthfile
  catalyst-gateway/tests/schemathesis_tests/blueprint.cue
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/wallet-automation/Earthfile
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/wallet-automation/blueprint.cue
Labels: review me, rr: qa

#2983 feat(cat-gateway): `cat-gateway` api tests
  catalyst-gateway/bin/src/cardano/mod.rs
  catalyst-gateway/tests/api_tests/Earthfile
  catalyst-gateway/tests/api_tests/Readme.md
  catalyst-gateway/tests/api_tests/integration/__init__.py
  catalyst-gateway/tests/api_tests/integration/test_schema_mismatch_behavior.py
  catalyst-gateway/tests/docker-compose.yml
Labels: review me, squad: gatekeepers, rr: gatekeepers

#3013 chore(cat-voices): open submission times
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/campaign/campaign_timeline.dart
Labels: review me

#3032 fix(cat-gateway): Cache metric descriptions update
  catalyst-gateway/bin/src/metrics/caches/native_assets.rs
  catalyst-gateway/bin/src/metrics/caches/txo_assets.rs
Labels: review me, squad: gatekeepers

#2925 feat(cat-gateway): Cardano assets caches
  catalyst-gateway/bin/src/cardano/mod.rs
  catalyst-gateway/bin/src/db/index/queries/caches/mod.rs
  catalyst-gateway/bin/src/db/index/queries/caches/txo_assets_by_stake.rs
  catalyst-gateway/bin/src/db/index/queries/caches/txo_by_stake.rs
  catalyst-gateway/bin/src/db/index/queries/cql/get_assets_by_stake_address.cql
  catalyst-gateway/bin/src/db/index/queries/cql/get_txo_by_stake_address.cql
  catalyst-gateway/bin/src/db/index/queries/mod.rs
  catalyst-gateway/bin/src/db/index/queries/staked_ada/get_assets_by_stake_address.rs
  catalyst-gateway/bin/src/db/index/queries/staked_ada/get_txo_by_stake_address.rs
  catalyst-gateway/bin/src/db/index/queries/staked_ada/update_txo_spent.rs
  catalyst-gateway/bin/src/db/index/session.rs
  catalyst-gateway/bin/src/db/index/tests/scylla_queries.rs
  catalyst-gateway/bin/src/metrics/caches/mod.rs
  catalyst-gateway/bin/src/metrics/caches/native_assets.rs
  catalyst-gateway/bin/src/metrics/caches/txo_assets.rs
  catalyst-gateway/bin/src/metrics/mod.rs
  catalyst-gateway/bin/src/service/api/cardano/staking/assets_get.rs
  catalyst-gateway/bin/src/service/common/types/cardano/asset_name.rs
  catalyst-gateway/bin/src/service/common/types/cardano/asset_value.rs
  catalyst-gateway/bin/src/service/common/types/cardano/hash28.rs
  catalyst-gateway/bin/src/settings/cardano_assets_cache.rs
  catalyst-gateway/bin/src/settings/mod.rs
  catalyst-gateway/tests/Earthfile
Labels: enhancement, squad: gatekeepers

#3036 fix(cat-voices): title in edit state for tag widget in proposal builder
  catalyst_voices/apps/voices/lib/widgets/document_builder/value/single_grouped_tag_selector_widget.dart
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
Labels: review me, squad: face, fyi: qa, F14-RC6

#3035 feat(cat-voices): proposal discovery view model
  catalyst_voices/apps/voices/lib/pages/discovery/sections/most_recent_proposals.dart
  catalyst_voices/apps/voices/lib/pages/discovery/state_selectors/most_recent_proposals_selector.dart
  catalyst_voices/apps/voices/lib/pages/funded_projects/funded_projects_page.dart
  catalyst_voices/apps/voices/lib/pages/proposals/proposals_page.dart
  catalyst_voices/apps/voices/lib/pages/proposals/widgets/proposals_pagination.dart
  catalyst_voices/apps/voices/lib/pages/proposals/widgets/proposals_pagination_tile.dart
  catalyst_voices/apps/voices/lib/pages/voting/voting_page.dart
  catalyst_voices/apps/voices/lib/widgets/cards/funded_proposal_card.dart
  catalyst_voices/apps/voices/lib/widgets/cards/proposal/proposal_border.dart
  catalyst_voices/apps/voices/lib/widgets/cards/proposal/proposal_brief_card.dart
  catalyst_voices/apps/voices/lib/widgets/cards/proposal/proposal_card.dart
  catalyst_voices/apps/voices/lib/widgets/widgets.dart
  catalyst_voices/apps/voices/test/widgets/cards/small_proposal_card_test.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/discovery/discovery_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/discovery/discovery_state.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposals/proposals_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposals/proposals_signal.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/proposal/proposal.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/catalyst_voices_view_models.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/proposal/proposal_brief.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/proposal/proposal_view_model.dart
  catalyst_voices/utilities/uikit_example/lib/examples/voices_proposal_card_example.dart
Labels: draft, squad: face, refactor

#3043 chore: update username
  .github/CODEOWNERS
Labels: enhancement

#3059 fix(cat-voices): Pre proposal submission check
  catalyst_voices/apps/voices/lib/routes/guards/proposal_submission_guard.dart
Labels: review me, squad: face

#3055 feat(cat-voices): voting models
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/catalyst_voices_models.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/voting/vote.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/voting/vote_type.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/voting/voting_ballot.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/voting/voting_ballot_builder.dart
  catalyst_voices/packages/internal/catalyst_voices_models/test/voting/voting_ballot_builder_test.dart
Labels: squad: face

#3056 feat(cat-voices): campaign model refactor
  catalyst_voices/apps/voices/lib/app/view/app.dart
  catalyst_voices/apps/voices/lib/dependency/dependencies.dart
  catalyst_voices/apps/voices/lib/pages/campaign/details/campaign_details_dialog.dart
  catalyst_voices/apps/voices/lib/pages/campaign/details/widgets/campaign_categories_tile.dart
  catalyst_voices/apps/voices/lib/pages/campaign/details/widgets/campaign_details_tile.dart
  catalyst_voices/apps/voices/lib/pages/campaign/details/widgets/campaign_header.dart
  catalyst_voices/apps/voices/lib/pages/campaign/details/widgets/campaign_management.dart
  catalyst_voices/apps/voices/lib/pages/campaign/details/widgets/campaign_management_dialog.dart
  catalyst_voices/apps/voices/lib/pages/campaign/details/widgets/campaign_sections_list_view.dart
  catalyst_voices/apps/voices/lib/pages/discovery/sections/current_campaign.dart
  catalyst_voices/apps/voices/lib/pages/discovery/state_selectors/campaign_categories_state_selector.dart
  catalyst_voices/apps/voices/lib/pages/proposals/widgets/proposals_campaign_details_button.dart
  catalyst_voices/apps/voices/lib/pages/proposals/widgets/proposals_fund_info.dart
  catalyst_voices/apps/voices/lib/pages/spaces/spaces_shell_page.dart
  catalyst_voices/apps/voices/lib/widgets/cards/funds_detail_card.dart
  catalyst_voices/apps/voices/test/widgets/campaign_timeline/campaign_timeline_card_test.dart
  catalyst_voices/apps/voices/test/widgets/campaign_timeline/campaign_timeline_test.dart
  catalyst_voices/apps/voices/test/widgets/cards/campaign_stage_card_test.dart
  catalyst_voices/apps/voices/test/widgets/cards/funds_detail_card_test.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/campaign/campaign_stage/campaign_stage_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/campaign/details/campaign_details.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/campaign/details/campaign_details_bloc.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/campaign/details/campaign_details_event.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/campaign/details/campaign_details_state.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/campaign/info/campaign_info.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/campaign/info/campaign_info_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/campaign/info/campaign_info_state.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/catalyst_voices_blocs.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/category/category_detail_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/discovery/discovery_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/discovery/discovery_state.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal/proposal_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/new_proposal/new_proposal_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/proposal_builder_bloc.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposals/proposals_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/workspace/workspace_bloc.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/workspace/workspace_state.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/test/campaign/info/campaign_info_cubit_test.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/campaign/campaign.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/campaign/campaign_base.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/campaign/campaign_category.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/campaign/campaign_phase.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/campaign/campaign_timeline.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/campaign/current_campaign.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/catalyst_voices_models.dart
  catalyst_voices/packages/internal/catalyst_voices_models/test/campaign/campaign_test.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/campaign/campaign_repository.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/campaign/campaign_service.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/campaign/campaign_info.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/campaign/campaign_stage.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/campaign/campaign_timeline_view_model.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/campaign/current_campaign_info_view_model.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/test/campaign/campaign_stage_test.dart
Labels: review me, squad: face, refactor

#3071 revert(cat-voices): campaign model refactor
  catalyst_voices/apps/voices/lib/app/view/app.dart
  catalyst_voices/apps/voices/lib/dependency/dependencies.dart
  catalyst_voices/apps/voices/lib/pages/campaign/details/campaign_details_dialog.dart
  catalyst_voices/apps/voices/lib/pages/campaign/details/widgets/campaign_categories_tile.dart
  catalyst_voices/apps/voices/lib/pages/campaign/details/widgets/campaign_details_tile.dart
  catalyst_voices/apps/voices/lib/pages/campaign/details/widgets/campaign_header.dart
  catalyst_voices/apps/voices/lib/pages/campaign/details/widgets/campaign_management.dart
  catalyst_voices/apps/voices/lib/pages/campaign/details/widgets/campaign_management_dialog.dart
  catalyst_voices/apps/voices/lib/pages/campaign/details/widgets/campaign_sections_list_view.dart
  catalyst_voices/apps/voices/lib/pages/discovery/sections/current_campaign.dart
  catalyst_voices/apps/voices/lib/pages/discovery/state_selectors/campaign_categories_state_selector.dart
  catalyst_voices/apps/voices/lib/pages/proposals/widgets/proposals_campaign_details_button.dart
  catalyst_voices/apps/voices/lib/pages/proposals/widgets/proposals_fund_info.dart
  catalyst_voices/apps/voices/lib/pages/spaces/spaces_shell_page.dart
  catalyst_voices/apps/voices/lib/widgets/cards/funds_detail_card.dart
  catalyst_voices/apps/voices/test/widgets/campaign_timeline/campaign_timeline_card_test.dart
  catalyst_voices/apps/voices/test/widgets/campaign_timeline/campaign_timeline_test.dart
  catalyst_voices/apps/voices/test/widgets/cards/campaign_stage_card_test.dart
  catalyst_voices/apps/voices/test/widgets/cards/funds_detail_card_test.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/campaign/campaign_stage/campaign_stage_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/campaign/details/campaign_details.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/campaign/details/campaign_details_bloc.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/campaign/details/campaign_details_event.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/campaign/details/campaign_details_state.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/campaign/info/campaign_info.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/campaign/info/campaign_info_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/campaign/info/campaign_info_state.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/catalyst_voices_blocs.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/category/category_detail_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/discovery/discovery_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/discovery/discovery_state.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal/proposal_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/new_proposal/new_proposal_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/proposal_builder_bloc.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposals/proposals_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/workspace/workspace_bloc.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/workspace/workspace_state.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/test/campaign/info/campaign_info_cubit_test.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/campaign/campaign.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/campaign/campaign_base.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/campaign/campaign_category.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/campaign/campaign_phase.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/campaign/campaign_timeline.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/campaign/current_campaign.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/catalyst_voices_models.dart
  catalyst_voices/packages/internal/catalyst_voices_models/test/campaign/campaign_test.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/campaign/campaign_repository.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/campaign/campaign_service.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/campaign/campaign_info.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/campaign/campaign_stage.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/campaign/campaign_timeline_view_model.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/campaign/current_campaign_info_view_model.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/test/campaign/campaign_stage_test.dart
Labels: review me, squad: face, refactor

#3073 feat(cat-voices): Refactor campaign model
  catalyst_voices/apps/voices/lib/app/view/app.dart
  catalyst_voices/apps/voices/lib/dependency/dependencies.dart
  catalyst_voices/apps/voices/lib/pages/campaign/details/campaign_details_dialog.dart
  catalyst_voices/apps/voices/lib/pages/campaign/details/widgets/campaign_categories_tile.dart
  catalyst_voices/apps/voices/lib/pages/campaign/details/widgets/campaign_details_tile.dart
  catalyst_voices/apps/voices/lib/pages/campaign/details/widgets/campaign_header.dart
  catalyst_voices/apps/voices/lib/pages/campaign/details/widgets/campaign_management.dart
  catalyst_voices/apps/voices/lib/pages/campaign/details/widgets/campaign_management_dialog.dart
  catalyst_voices/apps/voices/lib/pages/campaign/details/widgets/campaign_sections_list_view.dart
  catalyst_voices/apps/voices/lib/pages/discovery/sections/current_campaign.dart
  catalyst_voices/apps/voices/lib/pages/discovery/state_selectors/campaign_categories_state_selector.dart
  catalyst_voices/apps/voices/lib/pages/proposals/widgets/proposals_campaign_details_button.dart
  catalyst_voices/apps/voices/lib/pages/proposals/widgets/proposals_fund_info.dart
  catalyst_voices/apps/voices/lib/pages/spaces/spaces_shell_page.dart
  catalyst_voices/apps/voices/lib/widgets/cards/funds_detail_card.dart
  catalyst_voices/apps/voices/test/widgets/campaign_timeline/campaign_timeline_card_test.dart
  catalyst_voices/apps/voices/test/widgets/campaign_timeline/campaign_timeline_test.dart
  catalyst_voices/apps/voices/test/widgets/cards/campaign_stage_card_test.dart
  catalyst_voices/apps/voices/test/widgets/cards/funds_detail_card_test.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/campaign/campaign_stage/campaign_stage_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/campaign/details/campaign_details.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/campaign/details/campaign_details_bloc.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/campaign/details/campaign_details_event.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/campaign/details/campaign_details_state.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/campaign/info/campaign_info.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/campaign/info/campaign_info_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/campaign/info/campaign_info_state.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/catalyst_voices_blocs.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/category/category_detail_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/discovery/discovery_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/discovery/discovery_state.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal/proposal_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/new_proposal/new_proposal_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/proposal_builder_bloc.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposals/proposals_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/workspace/workspace_bloc.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/workspace/workspace_state.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/test/campaign/info/campaign_info_cubit_test.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/campaign/campaign.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/campaign/campaign_base.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/campaign/campaign_category.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/campaign/campaign_phase.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/campaign/campaign_timeline.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/campaign/current_campaign.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/catalyst_voices_models.dart
  catalyst_voices/packages/internal/catalyst_voices_models/test/campaign/campaign_test.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/campaign/campaign_repository.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/campaign/campaign_service.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/campaign/campaign_info.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/campaign/campaign_stage.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/campaign/campaign_timeline_view_model.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/campaign/current_campaign_info_view_model.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/test/campaign/campaign_stage_test.dart
Labels: review me, squad: face, refactor

#3075 feat(cat-voices): copy text update to drep approval contingency
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
Labels: review me, squad: face, F14-RC6

#3083 feat(cat-voices): registration transaction strategy
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/registration/registration_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/registration/account_submit_data.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/registration/registration_service.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/registration/registration_transaction_builder.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/registration/strategy/registration_transaction_strategy.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/registration/strategy/registration_transaction_strategy_bytes.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/registration/strategy/registration_transaction_strategy_models.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/registration/strategy/registration_transaction_strategy_type.dart
  catalyst_voices/packages/internal/catalyst_voices_services/test/src/registration/registration_transaction_builder_test.dart
  catalyst_voices/packages/internal/catalyst_voices_services/test/src/registration/strategy/registration_transaction_strategy_test.dart
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano_platform_interface/lib/src/cardano_wallet.dart
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano_web/lib/src/interop/catalyst_cardano_wallet_proxy.dart
  catalyst_voices/packages/libs/catalyst_cardano_serialization/lib/src/transaction.dart
Labels: squad: face

#3037 feat(cat-gateway): Get rid of the usage `WITH DOCKER` directive, dokerize all integration test runners
  .config/dictionaries/project.dic
  .github/workflows/ci.yml
  .github/workflows/generate-allure-report.yml
  catalyst-gateway/tests/Earthfile
  catalyst-gateway/tests/README.md
  catalyst-gateway/tests/api_tests/Earthfile
  catalyst-gateway/tests/docker-compose.yml
  catalyst-gateway/tests/schemathesis_tests/Earthfile
  catalyst-gateway/tests/schemathesis_tests/entry.sh
  docs/Earthfile
Labels: review me, squad: gatekeepers

#3101 feat(cat-voices): read only mode proposal view
  catalyst_voices/apps/voices/lib/app/view/app_content.dart
  catalyst_voices/apps/voices/lib/app/view/app_mobile_access_restriction.dart
  catalyst_voices/apps/voices/lib/common/constants/constants.dart
  catalyst_voices/apps/voices/lib/pages/proposal/proposal_content.dart
  catalyst_voices/apps/voices/lib/pages/proposal/proposal_page.dart
  catalyst_voices/apps/voices/lib/pages/proposal/snack_bar/viewing_older_version_snack_bar.dart
  catalyst_voices/apps/voices/lib/pages/proposal/tiles/proposal_metadata_tile.dart
  catalyst_voices/apps/voices/lib/pages/proposal/tiles/proposal_overview_tile.dart
  catalyst_voices/apps/voices/lib/pages/proposal/widget/proposal_app_closed.dart
  catalyst_voices/apps/voices/lib/pages/proposal/widget/proposal_header.dart
  catalyst_voices/apps/voices/lib/pages/proposal/widget/proposal_sidebars.dart
  catalyst_voices/apps/voices/lib/widgets/app_bar/voices_app_bar.dart
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/platform_aware_builder/platform_aware_builder.dart
Labels: review me, squad: face, a: proposal, F14-RC6

#3060 chore(cat-voices): registration transaction bytes strategy
  catalyst_voices/melos.yaml
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/registration/exception/registration_exception.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/registration/registration_transaction_builder.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/registration/registration_transaction_role.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/registration/strategy/registration_transaction_strategy_bytes.dart
  catalyst_voices/packages/internal/catalyst_voices_services/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_services/test/src/registration/registration_transaction_builder_test.dart
  catalyst_voices/packages/internal/catalyst_voices_services/test/src/registration/strategy/registration_transaction_strategy_bytes_test.dart
  catalyst_voices/packages/internal/catalyst_voices_services/test/src/registration/strategy/registration_transaction_strategy_test.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/registration/exception/localized_registration_exception.dart
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/example/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano_web/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cardano_serialization/lib/catalyst_cardano_serialization.dart
  catalyst_voices/packages/libs/catalyst_cardano_serialization/lib/src/builders/input_builder.dart
  catalyst_voices/packages/libs/catalyst_cardano_serialization/lib/src/builders/transaction_builder.dart
  catalyst_voices/packages/libs/catalyst_cardano_serialization/lib/src/exceptions.dart
  catalyst_voices/packages/libs/catalyst_cardano_serialization/lib/src/hashes.dart
  catalyst_voices/packages/libs/catalyst_cardano_serialization/lib/src/raw_transaction.dart
  catalyst_voices/packages/libs/catalyst_cardano_serialization/lib/src/raw_transaction_aspect.dart
  catalyst_voices/packages/libs/catalyst_cardano_serialization/lib/src/raw_transaction_tracing_encode_sink.dart
  catalyst_voices/packages/libs/catalyst_cardano_serialization/lib/src/rbac/x509_metadata_envelope.dart
  catalyst_voices/packages/libs/catalyst_cardano_serialization/lib/src/structured_bytes.dart
  catalyst_voices/packages/libs/catalyst_cardano_serialization/lib/src/transaction.dart
  catalyst_voices/packages/libs/catalyst_cardano_serialization/lib/src/types.dart
  catalyst_voices/packages/libs/catalyst_cardano_serialization/lib/src/witness.dart
  catalyst_voices/packages/libs/catalyst_cardano_serialization/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cardano_serialization/test/builders/transaction_builder_test.dart
  catalyst_voices/packages/libs/catalyst_cardano_serialization/test/raw_transaction_test.dart
  catalyst_voices/packages/libs/catalyst_cardano_serialization/test/structured_bytes_test.dart
  catalyst_voices/packages/libs/catalyst_cardano_serialization/test/types_test.dart
  catalyst_voices/packages/libs/catalyst_cose/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_key_derivation/lib/src/bip32_ed25519/bip32_ed25519_signature.dart
  catalyst_voices/packages/libs/catalyst_key_derivation/lib/src/bip32_ed25519/bip32_ed25519_signature_factory.dart
  catalyst_voices/packages/libs/catalyst_key_derivation/pubspec.yaml
Labels: squad: face, rr: architecture

#3038 fix(cat-voices): registration transaction single selection of inputs
  catalyst_voices/melos.yaml
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/registration/registration_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/registration/account_submit_data.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/registration/exception/registration_exception.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/registration/registration_service.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/registration/registration_transaction_builder.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/registration/registration_transaction_role.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/registration/strategy/registration_transaction_strategy.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/registration/strategy/registration_transaction_strategy_bytes.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/registration/strategy/registration_transaction_strategy_models.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/registration/strategy/registration_transaction_strategy_type.dart
  catalyst_voices/packages/internal/catalyst_voices_services/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_services/test/src/registration/registration_transaction_builder_test.dart
  catalyst_voices/packages/internal/catalyst_voices_services/test/src/registration/strategy/registration_transaction_strategy_bytes_test.dart
  catalyst_voices/packages/internal/catalyst_voices_services/test/src/registration/strategy/registration_transaction_strategy_test.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/registration/exception/localized_registration_exception.dart
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/example/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano_platform_interface/lib/src/cardano_wallet.dart
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano_web/lib/src/interop/catalyst_cardano_wallet_proxy.dart
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano_web/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cardano_serialization/lib/catalyst_cardano_serialization.dart
  catalyst_voices/packages/libs/catalyst_cardano_serialization/lib/src/builders/input_builder.dart
  catalyst_voices/packages/libs/catalyst_cardano_serialization/lib/src/builders/transaction_builder.dart
  catalyst_voices/packages/libs/catalyst_cardano_serialization/lib/src/exceptions.dart
  catalyst_voices/packages/libs/catalyst_cardano_serialization/lib/src/hashes.dart
  catalyst_voices/packages/libs/catalyst_cardano_serialization/lib/src/raw_transaction.dart
  catalyst_voices/packages/libs/catalyst_cardano_serialization/lib/src/raw_transaction_aspect.dart
  catalyst_voices/packages/libs/catalyst_cardano_serialization/lib/src/raw_transaction_tracing_encode_sink.dart
  catalyst_voices/packages/libs/catalyst_cardano_serialization/lib/src/rbac/x509_metadata_envelope.dart
  catalyst_voices/packages/libs/catalyst_cardano_serialization/lib/src/structured_bytes.dart
  catalyst_voices/packages/libs/catalyst_cardano_serialization/lib/src/transaction.dart
  catalyst_voices/packages/libs/catalyst_cardano_serialization/lib/src/types.dart
  catalyst_voices/packages/libs/catalyst_cardano_serialization/lib/src/witness.dart
  catalyst_voices/packages/libs/catalyst_cardano_serialization/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cardano_serialization/test/builders/transaction_builder_test.dart
  catalyst_voices/packages/libs/catalyst_cardano_serialization/test/raw_transaction_test.dart
  catalyst_voices/packages/libs/catalyst_cardano_serialization/test/structured_bytes_test.dart
  catalyst_voices/packages/libs/catalyst_cardano_serialization/test/types_test.dart
  catalyst_voices/packages/libs/catalyst_cose/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_key_derivation/lib/src/bip32_ed25519/bip32_ed25519_signature.dart
  catalyst_voices/packages/libs/catalyst_key_derivation/lib/src/bip32_ed25519/bip32_ed25519_signature_factory.dart
  catalyst_voices/packages/libs/catalyst_key_derivation/pubspec.yaml
Labels: squad: face, rr: architecture, a: account

#3102 fix(general): fix and improve github actions
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/test_case.yml
  .github/ISSUE_TEMPLATE/test_plan.yml
  .github/workflows/ci.yml
  .github/workflows/sync-labels.yml
Labels: review me

#3087 feat(cat-voices): campaign phase aware widget
  catalyst_voices/apps/voices/lib/app/view/app.dart
  catalyst_voices/apps/voices/lib/common/typedefs.dart
  catalyst_voices/apps/voices/lib/dependency/dependencies.dart
  catalyst_voices/apps/voices/lib/pages/account/account_page.dart
  catalyst_voices/apps/voices/lib/pages/campaign/stage/after_proposal_submission_page.dart
  catalyst_voices/apps/voices/lib/pages/campaign/stage/error_proposal_submission_page.dart
  catalyst_voices/apps/voices/lib/pages/campaign/stage/pre_proposal_submission_page.dart
  catalyst_voices/apps/voices/lib/pages/campaign_phase_aware/campaign_phase_aware.dart
  catalyst_voices/apps/voices/lib/pages/campaign_phase_aware/proposal_submission_phase_aware.dart
  catalyst_voices/apps/voices/lib/pages/campaign_phase_aware/widgets/bubble_campaign_phase_aware_background.dart
  catalyst_voices/apps/voices/lib/pages/campaign_phase_aware/widgets/error_campaign_phase_aware.dart
  catalyst_voices/apps/voices/lib/pages/campaign_phase_aware/widgets/loading_campaign_phase_aware.dart
  catalyst_voices/apps/voices/lib/pages/category/category_page.dart
  catalyst_voices/apps/voices/lib/pages/discovery/discovery_page.dart
  catalyst_voices/apps/voices/lib/pages/proposals/proposals_page.dart
  catalyst_voices/apps/voices/lib/pages/voting/voting_page.dart
  catalyst_voices/apps/voices/lib/pages/workspace/page/workspace_page.dart
  catalyst_voices/apps/voices/lib/routes/guards/proposal_submission_guard.dart
  catalyst_voices/apps/voices/lib/routes/guards/user_access_guard.dart
  catalyst_voices/apps/voices/lib/routes/routing/account_route.dart
  catalyst_voices/apps/voices/lib/routes/routing/campaign_stage_route.dart
  catalyst_voices/apps/voices/lib/routes/routing/overall_spaces_route.dart
  catalyst_voices/apps/voices/lib/routes/routing/proposal_builder_route.dart
  catalyst_voices/apps/voices/lib/routes/routing/proposal_route.dart
  catalyst_voices/apps/voices/lib/routes/routing/root_route.dart
  catalyst_voices/apps/voices/lib/routes/routing/routes.dart
  catalyst_voices/apps/voices/lib/routes/routing/spaces_route.dart
  catalyst_voices/packages/internal/catalyst_voices_assets/assets/images/mag_glass.webp
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/campaign/campaign_phase/campaign_phase_aware.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/campaign/campaign_phase/campaign_phase_aware_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/campaign/campaign_phase/campaign_phase_aware_state.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/campaign/campaign_stage/campaign_stage.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/campaign/campaign_stage/campaign_stage_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/campaign/campaign_stage/campaign_stage_state.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/catalyst_voices_blocs.dart
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/campaign/campaign_phase.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/campaign/active_campaign_observer.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/campaign/campaign_service.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/catalyst_voices_services.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/authentication/access_control.dart
Labels: review me, F15, squad: face, refactor

#3112 feat(cat-voices): pre-voting content
  catalyst_voices/apps/voices/lib/app/view/app_precache_image_assets.dart
  catalyst_voices/apps/voices/lib/pages/voting/voting_page.dart
  catalyst_voices/apps/voices/lib/pages/voting/widgets/pre_voting_content.dart
  catalyst_voices/apps/voices/lib/pages/voting/widgets/voting_background.dart
  catalyst_voices/apps/voices/lib/widgets/layouts/header_and_content_layout.dart
  catalyst_voices/packages/internal/catalyst_voices_assets/assets/images/voting_bg_dark.webp
  catalyst_voices/packages/internal/catalyst_voices_assets/assets/images/voting_bg_light.webp
  catalyst_voices/packages/internal/catalyst_voices_brands/lib/src/brands/brand.dart
Labels: review me, F15, squad: face

#3125 feat(cat-gateway): Rbac synchronization metric
  catalyst-gateway/bin/src/db/index/block/rbac509/mod.rs
  catalyst-gateway/bin/src/db/index/queries/rbac/get_catalyst_id_from_public_key.rs
  catalyst-gateway/bin/src/db/index/queries/rbac/get_catalyst_id_from_stake_address.rs
  catalyst-gateway/bin/src/db/index/queries/rbac/get_catalyst_id_from_transaction_id.rs
  catalyst-gateway/bin/src/metrics/mod.rs
  catalyst-gateway/bin/src/metrics/rbac.rs
  catalyst-gateway/bin/src/rbac/chains_cache.rs
Labels: review me, rust, squad: gatekeepers, rr: gatekeepers

#3070 feat(cat-voices): vote widget
  catalyst_voices/apps/voices/lib/pages/treasury/sections/treasury_campaign_stages_view_tile.dart
  catalyst_voices/apps/voices/lib/pages/treasury/sections/treasury_campaign_widgets.dart
  catalyst_voices/apps/voices/lib/pages/voting/widgets/account_voting_power_card.dart
  catalyst_voices/apps/voices/lib/pages/voting/widgets/voting_phase_progress_card.dart
  catalyst_voices/apps/voices/lib/widgets/cards/campaign_stage_card.dart
  catalyst_voices/apps/voices/lib/widgets/cards/proposal/proposal_brief_card.dart
  catalyst_voices/apps/voices/lib/widgets/cards/proposal/small_proposal_card.dart
  catalyst_voices/apps/voices/lib/widgets/common/affix_decorator.dart
  catalyst_voices/apps/voices/lib/widgets/countdown/campaign_phase_countdown.dart
  catalyst_voices/apps/voices/lib/widgets/rich_text/insert_new_image_dialog.dart
  catalyst_voices/apps/voices/lib/widgets/separators/voices_vertical_divider.dart
  catalyst_voices/apps/voices/lib/widgets/text/campaign_stage_time_text.dart
  catalyst_voices/apps/voices/lib/widgets/text/day_at_time_text.dart
  catalyst_voices/apps/voices/lib/widgets/text/day_month_time_text.dart
  catalyst_voices/apps/voices/lib/widgets/text/last_edit_date.dart
  catalyst_voices/apps/voices/lib/widgets/text/proposal_submission_closes_text.dart
  catalyst_voices/apps/voices/lib/widgets/text/proposal_submission_start_text.dart
  catalyst_voices/apps/voices/lib/widgets/text/proposal_version_info_text.dart
  catalyst_voices/apps/voices/lib/widgets/text/timestamp_text.dart
  catalyst_voices/apps/voices/lib/widgets/text/voting_start_at_time_text.dart
  catalyst_voices/apps/voices/lib/widgets/text_field/voices_email_text_field.dart
  catalyst_voices/apps/voices/lib/widgets/text_field/voices_password_text_field.dart
  catalyst_voices/apps/voices/lib/widgets/text_field/voices_uuid_text_field.dart
  catalyst_voices/apps/voices/lib/widgets/voting/vote_button.dart
  catalyst_voices/apps/voices/lib/widgets/voting/vote_button_compact.dart
  catalyst_voices/apps/voices/lib/widgets/voting/vote_button_expanded.dart
  catalyst_voices/apps/voices/lib/widgets/voting/vote_button_menu.dart
  catalyst_voices/apps/voices/lib/widgets/widgets.dart
  catalyst_voices/packages/internal/catalyst_voices_brands/lib/src/theme_extensions/voices_color_scheme.dart
  catalyst_voices/packages/internal/catalyst_voices_brands/lib/src/themes/catalyst.dart
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/catalyst_voices_view_models.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/common/formatters/date_formatter.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/common/formatters/duration_formatter.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/common/formatters/input_formatters.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/utils/typedefs.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/voting/vote_button_action.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/voting/vote_button_colors.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/voting/vote_button_data.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/voting/vote_type_data.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/voting/vote_type_view_model.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/test/common/formatters/date_formatter_test.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/test/common/formatters/duration_formatter_test.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/test/common/formatters/input_formatters_test.dart
Labels: squad: face, fyi: design

#3135 fix(cat-gateway): Fix Catalyst IDs comparins in RBAC validation
  catalyst-gateway/bin/src/db/index/schema/cql/rbac_registration.cql
  catalyst-gateway/bin/src/db/index/schema/mod.rs
  catalyst-gateway/bin/src/metrics/rbac.rs
  catalyst-gateway/bin/src/rbac/get_chain.rs
  catalyst-gateway/bin/src/rbac/validation.rs
  catalyst-gateway/bin/src/service/api/cardano/rbac/registrations_get/mod.rs
  catalyst-gateway/bin/src/service/common/auth/rbac/scheme.rs
Labels: do not merge yet, do not review yet

#3089 feat(cat-gateway): Integrate new version of the signed doc
  catalyst-gateway/bin/Cargo.toml
  catalyst-gateway/bin/src/db/event/mod.rs
  catalyst-gateway/bin/src/db/event/signed_docs/full_signed_doc.rs
  catalyst-gateway/bin/src/db/event/signed_docs/mod.rs
  catalyst-gateway/bin/src/db/event/signed_docs/signed_doc_body.rs
  catalyst-gateway/bin/src/db/event/signed_docs/sql/filtered_select_full_signed_documents.sql.jinja
  catalyst-gateway/bin/src/jinja.rs
  catalyst-gateway/bin/src/service/api/documents/common/mod.rs
  catalyst-gateway/bin/src/service/api/documents/post_document_index_query/mod.rs
  catalyst-gateway/bin/src/service/api/documents/post_document_index_query/response.rs
  catalyst-gateway/bin/src/service/api/documents/put_document/mod.rs
  catalyst-gateway/bin/src/service/api/documents/templates/data.rs
  catalyst-gateway/bin/src/service/api/documents/templates/mod.rs
  catalyst-gateway/bin/src/service/common/types/document/doc_ref.rs
  catalyst-gateway/event-db/migrations/V3__signed_documents.sql
Labels: draft, squad: gatekeepers

#3139 fix(cat-gateway): Bumping `rbac-registration` crate [PORT]
  catalyst-gateway/bin/Cargo.toml
Labels: review me
