Repository input-output-hk/catalyst-voices, pull requests merged in 2025-09, with the labels that each got.

#3319 refactor(general): Optimize rust test runner size
  catalyst-gateway/tests/Earthfile
Labels: review me, squad: gatekeepers, refactor, rr: engineering, rr: gatekeepers, github_actions

#3337 feat(cat-voices): permission handler
  catalyst_voices/apps/voices/android/app/src/main/AndroidManifest.xml
  catalyst_voices/apps/voices/ios/Runner.xcodeproj/project.pbxproj
  catalyst_voices/apps/voices/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  catalyst_voices/apps/voices/lib/common/permission_mixin.dart
  catalyst_voices/apps/voices/lib/dependency/dependencies.dart
  catalyst_voices/apps/voices/lib/permissions/android_permission_strategy.dart
  catalyst_voices/apps/voices/lib/permissions/default_permission_strategy.dart
  catalyst_voices/apps/voices/lib/permissions/ios_permission_strategy.dart
  catalyst_voices/apps/voices/lib/permissions/permission_handler_factory.dart
  catalyst_voices/apps/voices/lib/permissions/permission_request.dart
  catalyst_voices/apps/voices/lib/permissions/permission_strategy.dart
  catalyst_voices/apps/voices/macos/Flutter/GeneratedPluginRegistrant.swift
  catalyst_voices/apps/voices/pubspec.yaml
  catalyst_voices/melos.yaml
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/catalyst_voices_models.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/permissions/exceptions/permission_exceptions.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/permissions/exceptions/permission_need_explanation_exception.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/permissions/exceptions/permission_need_rationale_exception.dart
  catalyst_voices/packages/internal/catalyst_voices_models/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/catalyst_voices_view_models.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/exception/localized_permission_need_explanation_exception.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/exception/localized_permission_need_rationale_exception.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/pubspec.yaml
Labels: review me, squad: face, platform: iOS, platform: android

#3348 feat(cat-voices): frontend sentry integration
  catalyst_voices/Earthfile
  catalyst_voices/apps/voices/lib/app/view/app_precache_image_assets.dart
  catalyst_voices/apps/voices/lib/app/view/app_splash_screen_manager.dart
  catalyst_voices/apps/voices/lib/app/view/video_cache/app_video_manager.dart
  catalyst_voices/apps/voices/lib/configs/bootstrap.dart
  catalyst_voices/apps/voices/lib/configs/sentry_service.dart
  catalyst_voices/apps/voices/lib/dependency/dependencies.dart
  catalyst_voices/apps/voices/lib/pages/discovery/discovery_page.dart
  catalyst_voices/apps/voices/lib/routes/app_router_factory.dart
  catalyst_voices/apps/voices/lib/routes/routing/account_route.dart
  catalyst_voices/apps/voices/lib/routes/routing/overall_spaces_route.dart
  catalyst_voices/apps/voices/lib/routes/routing/proposal_builder_route.dart
  catalyst_voices/apps/voices/lib/routes/routing/proposal_route.dart
  catalyst_voices/apps/voices/lib/routes/routing/spaces_route.dart
  catalyst_voices/apps/voices/pubspec.yaml
  catalyst_voices/blueprint.cue
  catalyst_voices/melos.yaml
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/catalyst_voices_models.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/config/app_config.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/config/reporting_service_config.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/api/api_services.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/config/app_config_factory.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/database/catalyst_database.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/config/remote_sentry_config.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/catalyst_voices_services.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/logging/logging_service.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/logging/noop_logging_service.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/logging/reporting/log_reporting_strategy.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/logging/reporting/sentry_errors_reporting_strategy.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/reporting/database_logging_interceptor.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/reporting/noop_reporting_service.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/reporting/reporting_service.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/reporting/reporting_service_mediator.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/reporting/sentry_reporting_service.dart
  catalyst_voices/packages/internal/catalyst_voices_services/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/catalyst_voices_shared.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/profiler/catalyst_noop_profiler.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/profiler/catalyst_profiler.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/profiler/catalyst_profiler_arguments.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/profiler/catalyst_sentry_profiler.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/profiler/catalyst_startup_profiler.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/profiler/profiler.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/utils/typedefs.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/pubspec.yaml
  config/dev/config.json
  config/preprod/config.json
  config/prod/config.json
Labels: squad: face, no-track

#3160 feat(cat-gateway): Return invalid registrations from RBAC endpoint
  catalyst-gateway/bin/Cargo.toml
  catalyst-gateway/bin/src/db/index/queries/rbac/get_rbac_invalid_registrations.rs
  catalyst-gateway/bin/src/rbac/get_chain.rs
  catalyst-gateway/bin/src/rbac/mod.rs
  catalyst-gateway/bin/src/service/api/cardano/rbac/mod.rs
  catalyst-gateway/bin/src/service/api/cardano/rbac/registrations_get/invalid_registration.rs
  catalyst-gateway/bin/src/service/api/cardano/rbac/registrations_get/invalid_registration_list.rs
  catalyst-gateway/bin/src/service/api/cardano/rbac/registrations_get/key_type.rs
  catalyst-gateway/bin/src/service/api/cardano/rbac/registrations_get/mod.rs
  catalyst-gateway/bin/src/service/api/cardano/rbac/registrations_get/pem.rs
  catalyst-gateway/bin/src/service/api/cardano/rbac/registrations_get/role_id.rs
  catalyst-gateway/bin/src/service/api/cardano/rbac/registrations_get/v1/binary_data.rs
  catalyst-gateway/bin/src/service/api/cardano/rbac/registrations_get/v1/endpoint.rs
  catalyst-gateway/bin/src/service/api/cardano/rbac/registrations_get/v1/extended_data.rs
  catalyst-gateway/bin/src/service/api/cardano/rbac/registrations_get/v1/key_data.rs
  catalyst-gateway/bin/src/service/api/cardano/rbac/registrations_get/v1/key_data_list.rs
  catalyst-gateway/bin/src/service/api/cardano/rbac/registrations_get/v1/mod.rs
  catalyst-gateway/bin/src/service/api/cardano/rbac/registrations_get/v1/payment_data.rs
  catalyst-gateway/bin/src/service/api/cardano/rbac/registrations_get/v1/payment_data_list.rs
  catalyst-gateway/bin/src/service/api/cardano/rbac/registrations_get/v1/registration_chain.rs
  catalyst-gateway/bin/src/service/api/cardano/rbac/registrations_get/v1/response.rs
  catalyst-gateway/bin/src/service/api/cardano/rbac/registrations_get/v1/role_data.rs
  catalyst-gateway/bin/src/service/api/cardano/rbac/registrations_get/v1/role_map.rs
  catalyst-gateway/bin/src/service/api/cardano/rbac/registrations_get/v2/c509.rs
  catalyst-gateway/bin/src/service/api/cardano/rbac/registrations_get/v2/endpoint.rs
  catalyst-gateway/bin/src/service/api/cardano/rbac/registrations_get/v2/extended_data.rs
  catalyst-gateway/bin/src/service/api/cardano/rbac/registrations_get/v2/extended_data_key.rs
  catalyst-gateway/bin/src/service/api/cardano/rbac/registrations_get/v2/extended_data_list.rs
  catalyst-gateway/bin/src/service/api/cardano/rbac/registrations_get/v2/extended_data_value.rs
  catalyst-gateway/bin/src/service/api/cardano/rbac/registrations_get/v2/key_data.rs
  catalyst-gateway/bin/src/service/api/cardano/rbac/registrations_get/v2/key_data_list.rs
  catalyst-gateway/bin/src/service/api/cardano/rbac/registrations_get/v2/key_value.rs
  catalyst-gateway/bin/src/service/api/cardano/rbac/registrations_get/v2/mod.rs
  catalyst-gateway/bin/src/service/api/cardano/rbac/registrations_get/v2/payment_data.rs
  catalyst-gateway/bin/src/service/api/cardano/rbac/registrations_get/v2/payment_data_list.rs
  catalyst-gateway/bin/src/service/api/cardano/rbac/registrations_get/v2/registration_chain.rs
  catalyst-gateway/bin/src/service/api/cardano/rbac/registrations_get/v2/response.rs
  catalyst-gateway/bin/src/service/api/cardano/rbac/registrations_get/v2/role_data.rs
  catalyst-gateway/bin/src/service/api/cardano/rbac/registrations_get/v2/role_list.rs
  catalyst-gateway/bin/src/service/common/types/cardano/ada_value.rs
  catalyst-gateway/bin/src/service/common/types/generic/error_msg.rs
Labels: review me, rust, requires architecture review, rr: gatekeepers

#3372 fix(cat-gateway): Check stake addresses of all roles during RBAC validation
  catalyst-gateway/bin/Cargo.toml
  catalyst-gateway/bin/src/rbac/validation.rs
Labels: review me, rust, squad: gatekeepers, rr: gatekeepers

#3376 feat(cat-voices): uploader service
  catalyst_voices/apps/voices/lib/dependency/dependencies.dart
  catalyst_voices/apps/voices/lib/pages/registration/widgets/upload_seed_phrase/upload_seed_phrase_dialog.dart
  catalyst_voices/apps/voices/lib/pages/workspace/header/import_proposal_button.dart
  catalyst_voices/apps/voices/lib/widgets/modals/voices_upload_file_dialog.dart
  catalyst_voices/apps/voices/pubspec.yaml
  catalyst_voices/melos.yaml
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/catalyst_voices_models.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/file/voices_file.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/catalyst_voices_services.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/common/file_path_helper_mixin.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/downloader/downloader_service.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/uploader/uploader_service.dart
  catalyst_voices/packages/internal/catalyst_voices_services/pubspec.yaml
Labels: review me, squad: face, platform: iOS, platform: android, platform: web

#3375 chore(cat-gateway): Fix gateway build for arm
  catalyst-gateway/Earthfile
  catalyst-gateway/tests/Earthfile
Labels: review me, squad: gatekeepers, rr: architecture

#3380 feat(cat-voices): Discovery Page mobile screen adjustment
  catalyst_voices/apps/voices/lib/pages/discovery/sections/campaign_categories.dart
  catalyst_voices/apps/voices/lib/pages/discovery/sections/campaign_hero.dart
  catalyst_voices/apps/voices/lib/pages/discovery/sections/current_campaign.dart
  catalyst_voices/apps/voices/lib/pages/discovery/sections/most_recent_proposals.dart
  catalyst_voices/apps/voices/lib/pages/discovery/sections/stay_involved.dart
  catalyst_voices/apps/voices/lib/pages/discovery/state_selectors/campaign_categories_state_selector.dart
  catalyst_voices/apps/voices/lib/pages/discovery/state_selectors/current_campaign_selector.dart
  catalyst_voices/apps/voices/lib/widgets/campaign_timeline/campaign_timeline.dart
  catalyst_voices/apps/voices/lib/widgets/cards/campaign_category_card.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/catalyst_voices_shared.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/responsive/responsive_padding.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/responsive/responsive_sized_box.dart
Labels: review me, squad: face, platform: iOS, platform: android

#3406 fix(cat-gateway): `EventDb::connection_is_ok` making also schema version check
  catalyst-gateway/bin/src/db/event/mod.rs
  catalyst-gateway/bin/src/service/api/cardano/staking/mod.rs
  catalyst-gateway/bin/src/service/api/documents/mod.rs
  catalyst-gateway/bin/src/service/utilities/middleware/mod.rs
  catalyst-gateway/bin/src/service/utilities/middleware/schema_validation.rs
Labels: review me, squad: gatekeepers

#3422 chore(general): Try python-base without rust
  catalyst-gateway/tests/api_tests/Earthfile
Labels: do not merge yet

#3441 fix(cat-gateway): Migrate EventDB from `bb8` to `deadpool`
  .config/dictionaries/project.dic
  catalyst-gateway/bin/Cargo.toml
  catalyst-gateway/bin/src/cli.rs
  catalyst-gateway/bin/src/db/event/mod.rs
  catalyst-gateway/bin/src/db/event/signed_docs/tests/mod.rs
  catalyst-gateway/bin/src/service/common/responses/mod.rs
  catalyst-gateway/bin/src/settings/event_db.rs
  catalyst-gateway/bin/src/settings/mod.rs
Labels: review me, squad: gatekeepers

#3450 fix(cat-gateway): Fixing `cat-gateway` CI build
  catalyst-gateway/.config/nextest.toml
  catalyst-gateway/Earthfile
  catalyst-gateway/bin/Cargo.toml
  catalyst-gateway/deny.toml
  catalyst-gateway/event-db/Earthfile
  catalyst-gateway/tests/Earthfile
Labels: review me

#3449 feat(cat-voices): tracking registration status
  catalyst_voices/apps/voices/lib/dependency/dependencies.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/test/session/session_cubit_test.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/catalyst_voices_models.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/user/account.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/user/account_registration_status.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/user/recovered_account.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/user/account_dto.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/user/user_repository.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/catalyst_voices_services.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/registration/registration_service.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/user/registration_status_poller.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/user/user_service.dart
  catalyst_voices/packages/internal/catalyst_voices_services/test/src/user/user_service_test.dart
Labels: squad: face, a: account

#3448 feat(cat-voices): Improvements to import proposals, handling malformed proposals
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/workspace/workspace_bloc.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/document_ref.dart
  catalyst_voices/packages/internal/catalyst_voices_models/test/document/document_ref_test.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/document/document_repository.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/proposal/proposal_repository.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/document/document_repository_test.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/utils/test_factories.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/proposal/proposal_service.dart
Labels: review me, squad: face
