Repository input-output-hk/catalyst-voices, pull requests merged in 2025-01, with the labels that each got.

#1448 test(cat-gateway): Add CRUD queries testing into Scylla integration test
  catalyst-gateway/bin/src/db/index/queries/sync_status/update.rs
  catalyst-gateway/bin/src/db/index/tests/mod.rs
  catalyst-gateway/bin/src/db/index/tests/scylla_queries.rs
  catalyst-gateway/bin/src/db/index/tests/scylla_schema.rs
  catalyst-gateway/bin/src/db/index/tests/scylla_session.rs
  catalyst-gateway/tests/Earthfile
Labels: review me

#1330 feat(docs): proposal template drafting
  Overall,
  docs/src/architecture/08_concepts/document_templates/proposal/F14-Generic/0ce8ab38-9258-4fbc-a62e-7faa6e58318f.schema.json
  docs/src/architecture/08_concepts/document_templates/proposal/F14-Generic/example.proposal.json
Labels: review me

#1442 feat(cat-voices): document builder editing
  catalyst_voices/apps/voices/lib/pages/proposal_builder/proposal_builder_rich_text_step.dart
  catalyst_voices/apps/voices/lib/widgets/document_builder/document_property_builder_widget.dart
  catalyst_voices/apps/voices/lib/widgets/document_builder/document_section_builder_widget.dart
  catalyst_voices/melos.yaml
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/catalyst_voices_models.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/document.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/document_builder.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/document_change.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/document_definitions.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/document_node_id.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/document_schema.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document_builder/document_builder.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document_builder/document_schema.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/document_dto.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/document_properties_dto.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/schema/document_definitions_dto.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/schema/document_schema_dto.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/schema/document_schema_property_dto.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/schema/document_schema_section_dto.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/schema/document_schema_segment_dto.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document_builder_dto.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document_schema_dto.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/utils/document_schema_dto_converter.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/document/document_dto_test.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/document/schema/document_definitions_dto_test.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/document/schema/document_schema_dto_test.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/document_builder/document_builder_test.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/catalyst_voices_shared.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/document/extension/document_list_sort_ext.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/document/extension/document_map_to_list_ext.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/document/identifiable.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/document/signed_document_manager.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/document/signed_document_manager_impl.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/test/src/document/signed_document_manager_test.dart
Labels: review me, dart

#1445 test(cat-voices): 1444 add tooltip test
  catalyst_voices/apps/voices/integration_test/app_test.dart
  catalyst_voices/apps/voices/integration_test/pageobject/spaces_drawer_page.dart
  catalyst_voices/apps/voices/lib/widgets/tooltips/voices_plain_tooltip.dart
Labels: review me

#1458 chore(flutter): publish packages
  catalyst_voices/CHANGELOG.md
  catalyst_voices/apps/voices/pubspec.yaml
  catalyst_voices/melos.yaml
  catalyst_voices/packages/internal/catalyst_voices_assets/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_blocs/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_brands/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_localization/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_models/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_repositories/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_services/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_shared/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_view_models/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_analysis/CHANGELOG.md
  catalyst_voices/packages/libs/catalyst_analysis/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/CHANGELOG.md
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/example/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano_platform_interface/CHANGELOG.md
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano_platform_interface/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano_web/CHANGELOG.md
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano_web/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cardano_serialization/CHANGELOG.md
  catalyst_voices/packages/libs/catalyst_cardano_serialization/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_compression/catalyst_compression/CHANGELOG.md
  catalyst_voices/packages/libs/catalyst_compression/catalyst_compression/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_compression/catalyst_compression_platform_interface/CHANGELOG.md
  catalyst_voices/packages/libs/catalyst_compression/catalyst_compression_platform_interface/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_compression/catalyst_compression_web/CHANGELOG.md
  catalyst_voices/packages/libs/catalyst_compression/catalyst_compression_web/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cose/CHANGELOG.md
  catalyst_voices/packages/libs/catalyst_cose/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_key_derivation/CHANGELOG.md
  catalyst_voices/packages/libs/catalyst_key_derivation/Earthfile
  catalyst_voices/packages/libs/catalyst_key_derivation/example/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_key_derivation/lib/src/rust/api/simple.dart
  catalyst_voices/packages/libs/catalyst_key_derivation/pubspec.yaml
  catalyst_voices/utilities/poc_local_storage/pubspec.yaml
  catalyst_voices/utilities/remote_widgets/example/pubspec.yaml
  catalyst_voices/utilities/remote_widgets/pubspec.yaml
  catalyst_voices/utilities/uikit_example/pubspec.yaml
Labels: review me, dart

#1459 refactor(cat-voices): simplify document parsing
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/document_schema.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/schema/document_schema_property_dto.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/schema/document_schema_section_dto.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/schema/document_schema_segment_dto.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/utils/document_schema_dto_converter.dart
Labels: review me, dart

#1393 feat(cat-gateway): Add simple `signed_docs` select query, update insert query.
  .config/dictionaries/project.dic
  catalyst-gateway/bin/Cargo.toml
  catalyst-gateway/bin/src/db/event/common/mod.rs
  catalyst-gateway/bin/src/db/event/common/query_limits.rs
  catalyst-gateway/bin/src/db/event/mod.rs
  catalyst-gateway/bin/src/db/event/signed_docs/full_signed_doc.rs
  catalyst-gateway/bin/src/db/event/signed_docs/mod.rs
  catalyst-gateway/bin/src/db/event/signed_docs/query_filter.rs
  catalyst-gateway/bin/src/db/event/signed_docs/signed_doc_body.rs
  catalyst-gateway/bin/src/db/event/signed_docs/sql/filtered_select_signed_documents.sql.jinja
  catalyst-gateway/bin/src/db/event/signed_docs/sql/select_signed_documents.sql.jinja
  catalyst-gateway/bin/src/db/event/signed_docs/tests/mod.rs
  catalyst-gateway/bin/src/jinja.rs
  catalyst-gateway/bin/src/main.rs
  catalyst-gateway/bin/src/service/common/objects/generic/pagination.rs
  catalyst-gateway/bin/src/service/common/types/generic/query/pagination.rs
  catalyst-gateway/bin/src/service/mod.rs
Labels: review me

#1460 fix(cat-voices): allow optional title in document properties/sections
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/document_schema.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/schema/document_schema_property_dto.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/schema/document_schema_section_dto.dart
Labels: bug, review me, dart

#1463 feat(cat-voices): DocumentBuilderSectionTile
  catalyst_voices/apps/voices/lib/pages/proposal_builder/proposal_builder_rich_text_step.dart
  catalyst_voices/apps/voices/lib/pages/treasury/steps/treasury_campaign_stages_edit_step.dart
  catalyst_voices/apps/voices/lib/pages/treasury/steps/treasury_campaign_stages_view_step.dart
  catalyst_voices/apps/voices/lib/widgets/document_builder/document_property_builder_widget.dart
  catalyst_voices/apps/voices/lib/widgets/document_builder/document_section_builder_widget.dart
  catalyst_voices/apps/voices/lib/widgets/tiles/document_builder_section_tile.dart
  catalyst_voices/apps/voices/lib/widgets/tiles/selectable_tile.dart
  catalyst_voices/apps/voices/lib/widgets/widgets.dart
Labels: review me, dart

#1457 refactor: update proposal schema structure and example
  docs/src/architecture/08_concepts/document_templates/proposal/F14-Generic/0ce8ab38-9258-4fbc-a62e-7faa6e58318f.schema.json
  docs/src/architecture/08_concepts/document_templates/proposal/F14-Generic/example.proposal.json
Labels: review me

#1456 feat(cat-voices): Enable the 'arithmetic_side_effects' Clippy lint
  catalyst-gateway/Cargo.toml
  catalyst-gateway/Earthfile
  catalyst-gateway/bin/Cargo.toml
  catalyst-gateway/bin/src/cardano/mod.rs
  catalyst-gateway/bin/src/db/index/queries/sync_status/get.rs
  catalyst-gateway/bin/src/service/api/cardano/staking/assets_get.rs
  catalyst-gateway/bin/src/service/common/auth/rbac/token.rs
  catalyst-gateway/bin/src/settings/chain_follower.rs
  catalyst-gateway/clippy.toml
  catalyst_voices/packages/libs/catalyst_key_derivation/rust/Cargo.toml
  catalyst_voices/packages/libs/catalyst_key_derivation/rust/Earthfile
  catalyst_voices/packages/libs/catalyst_key_derivation/rust/clippy.toml
Labels: review me

#1443 feat(cat-voices): TokenField and DocumentTokenValueTile
  catalyst_voices/apps/voices/lib/widgets/document_builder/document_token_value_widget.dart
  catalyst_voices/apps/voices/lib/widgets/text_field/token_field.dart
  catalyst_voices/apps/voices/lib/widgets/text_field/voices_int_field.dart
  catalyst_voices/apps/voices/lib/widgets/text_field/voices_num_field.dart
  catalyst_voices/apps/voices/lib/widgets/text_field/voices_text_field.dart
  catalyst_voices/apps/voices/lib/widgets/tiles/document_builder_section_tile.dart
  catalyst_voices/apps/voices/lib/widgets/widgets.dart
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/catalyst_voices_models.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/money/currency.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/money/money.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/catalyst_voices_shared.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/codecs/codecs.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/codecs/int_codec.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/formatter/cryptocurrency_formatter.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/range/range.dart
Labels: review me, ux/ui, dart

#1451 feat(cat-voices): User Input Component - Checkbox
  .config/dictionaries/project.dic
  catalyst_voices/apps/voices/lib/widgets/document_builder/agreement_confirmation_widget.dart
  catalyst_voices/apps/voices/lib/widgets/rich_text/markdown_text.dart
  catalyst_voices/apps/voices/lib/widgets/tiles/document_builder_section_tile.dart
  catalyst_voices/apps/voices/lib/widgets/toggles/voices_checkbox.dart
  catalyst_voices/apps/voices/pubspec.yaml
  catalyst_voices/melos.yaml
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/document.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/document_builder.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/document_definitions.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/document_schema.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/document_dto.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/schema/document_definitions_converter_ext.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/schema/document_definitions_dto.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/utils/json_converters.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/assets/0ce8ab38-9258-4fbc-a62e-7faa6e58318f.schema.json
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/assets/generic_proposal.json
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/document/document_dto_test.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/catalyst_voices_shared.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/utils/launch_url_mixin.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/pubspec.yaml
Labels: review me, ux/ui

#1455 feat(cat-voices): TagSelection
  catalyst_voices/apps/voices/lib/common/ext/string_ext.dart
  catalyst_voices/apps/voices/lib/widgets/document_builder/document_token_value_widget.dart
  catalyst_voices/apps/voices/lib/widgets/document_builder/single_grouped_tag_selector_widget.dart
  catalyst_voices/apps/voices/lib/widgets/dropdown/voices_dropdown_form_field.dart
  catalyst_voices/apps/voices/lib/widgets/tiles/document_builder_section_tile.dart
  catalyst_voices/apps/voices/lib/widgets/widgets.dart
  catalyst_voices/packages/internal/catalyst_voices_brands/lib/src/themes/catalyst.dart
  catalyst_voices/packages/internal/catalyst_voices_brands/lib/src/themes/widgets/voices_input_decoration_theme.dart
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/catalyst_voices_models.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/defined_property/grouped_tags.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/document.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/document_definitions.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/document_schema.dart
  catalyst_voices/packages/internal/catalyst_voices_models/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_models/test/document/defined_property/grouped_tags.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/schema/document_schema_logical_property_dto.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/schema/document_schema_property_dto.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/utils/document_schema_dto_converter.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/document/schema/document_schema_property_dto_test.dart
Labels: review me, ux/ui, dart

#1475 feat(cat-gateway): Removed unused `event-db` queries and integration tests run
  catalyst-gateway/event-db/Earthfile
  catalyst-gateway/event-db/blueprint.cue
  catalyst-gateway/event-db/poetry.lock
  catalyst-gateway/event-db/pyproject.toml
  catalyst-gateway/event-db/queries/insert_signed_documents.sql
  catalyst-gateway/event-db/queries/select_signed_documents.sql.jinja
  catalyst-gateway/event-db/queries/select_signed_documents_2.sql.jinja
  catalyst-gateway/event-db/tests/docker-compose.yml
  catalyst-gateway/event-db/tests/test_signed_docs_queries.py
Labels: review me

#1472 test(cat-voices): Another batch of onboarding tests
  catalyst_voices/apps/voices/integration_test/all_test.dart
  catalyst_voices/apps/voices/integration_test/app_test.dart
  catalyst_voices/apps/voices/integration_test/onboarding_test.dart
  catalyst_voices/apps/voices/integration_test/pageobject/app_bar_page.dart
  catalyst_voices/apps/voices/integration_test/pageobject/common_page.dart
  catalyst_voices/apps/voices/integration_test/pageobject/onboarding_page.dart
  catalyst_voices/apps/voices/integration_test/pageobject/overall_spaces_page.dart
  catalyst_voices/apps/voices/integration_test/pageobject/spaces_drawer_page.dart
  catalyst_voices/apps/voices/integration_test/suites/app_test.dart
  catalyst_voices/apps/voices/integration_test/suites/onboarding_test.dart
  catalyst_voices/apps/voices/integration_test/types/registration_state.dart
  catalyst_voices/apps/voices/lib/pages/registration/create_keychain/stage/seed_phrase_panel.dart
  catalyst_voices/apps/voices/lib/pages/registration/create_keychain/stage/splash_panel.dart
  catalyst_voices/apps/voices/lib/pages/registration/recover/recover_method_panel.dart
  catalyst_voices/apps/voices/lib/pages/registration/registration_dialog.dart
  catalyst_voices/apps/voices/lib/pages/registration/wallet_link/stage/select_wallet_panel.dart
  catalyst_voices/apps/voices/lib/pages/registration/widgets/information_panel.dart
  catalyst_voices/apps/voices/lib/pages/registration/widgets/registration_stage_navigation.dart
  catalyst_voices/apps/voices/lib/pages/registration/widgets/seed_phrase_actions.dart
  catalyst_voices/apps/voices/lib/widgets/modals/voices_desktop_dialog.dart
  catalyst_voices/apps/voices/lib/widgets/seed_phrase/seed_phrases_viewer.dart
Labels: review me

#1476 feat(cat-voices): document property validation
  catalyst_voices/apps/voices/lib/widgets/document_builder/single_grouped_tag_selector_widget.dart
  catalyst_voices/apps/voices/lib/widgets/tiles/document_builder_section_tile.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/catalyst_voices_models.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/definitions/agreement_confirmation_definition.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/definitions/drop_down_single_select_definition.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/definitions/duration_in_months_definition.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/definitions/language_code_definition.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/definitions/multi_line_text_entry_definition.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/definitions/multi_line_text_entry_list_markdown_definition.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/definitions/multi_line_text_entry_markdown_definition.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/definitions/multi_select_definition.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/definitions/nested_questions_definition.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/definitions/nested_questions_list_definition.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/definitions/section_definition.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/definitions/segment_definition.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/definitions/single_grouped_tag_selector_definition.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/definitions/single_line_https_url_entry_definition.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/definitions/single_line_https_url_entry_list_definition.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/definitions/single_line_text_entry_definition.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/definitions/single_line_text_entry_list_definition.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/definitions/spdx_license_or_url_definition.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/definitions/tag_group_definition.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/definitions/tag_selection_definition.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/definitions/token_value_cardano_ada_definition.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/definitions/yes_no_choice_definition.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/document.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/document_builder.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/document_definitions.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/document_schema.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/document_validator.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/defined_property_dto/grouped_tags_dto.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/document_dto.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/schema/document_definitions_converter_ext.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/schema/document_schema_property_dto.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/utils/json_converters.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/document/document_dto_test.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/range/range.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/catalyst_voices_view_models.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/document/validation/localized_document_validation_result.dart
Labels: review me, dart, F14

#1482 feat(cat-voices): validation error translations
  catalyst_voices/apps/voices/lib/widgets/document_builder/document_token_value_widget.dart
  catalyst_voices/apps/voices/lib/widgets/text_field/token_field.dart
  catalyst_voices/apps/voices/lib/widgets/tiles/document_builder_section_tile.dart
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/range/range.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/document/validation/localized_document_validation_result.dart
Labels: review me, dart, F14

#1434 test(cat-gateway): restore schemathesis tests
  catalyst-gateway/tests/Earthfile
  catalyst-gateway/tests/node1-scylla.yaml
  catalyst-gateway/tests/schemathesis_tests/Earthfile
  catalyst-gateway/tests/schemathesis_tests/blueprint.cue
  catalyst-gateway/tests/schemathesis_tests/schemathesis-docker-compose.yml
Labels: review me

#1489 feat(cat-voices): PlaceholderRichText and TokenValue helper handles nullable range
  catalyst_voices/apps/voices/lib/widgets/document_builder/agreement_confirmation_widget.dart
  catalyst_voices/apps/voices/lib/widgets/rich_text/placeholder_rich_text.dart
  catalyst_voices/apps/voices/lib/widgets/text_field/token_field.dart
  catalyst_voices/apps/voices/lib/widgets/widgets.dart
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/money/currency.dart
Labels: review me, dart

#1484 refactor(cat-voices): rename SectionsController into SegmentsController
  catalyst_voices/apps/voices/lib/pages/proposal_builder/proposal_builder_body.dart
  catalyst_voices/apps/voices/lib/pages/proposal_builder/proposal_builder_navigation_panel.dart
  catalyst_voices/apps/voices/lib/pages/proposal_builder/proposal_builder_page.dart
  catalyst_voices/apps/voices/lib/pages/proposal_builder/proposal_builder_rich_text_step.dart
  catalyst_voices/apps/voices/lib/pages/treasury/sections/treasury_campaign_categories_step.dart
  catalyst_voices/apps/voices/lib/pages/treasury/sections/treasury_campaign_details_tile.dart
  catalyst_voices/apps/voices/lib/pages/treasury/sections/treasury_campaign_stages_edit_tile.dart
  catalyst_voices/apps/voices/lib/pages/treasury/sections/treasury_campaign_stages_view_tile.dart
  catalyst_voices/apps/voices/lib/pages/treasury/sections/treasury_campaign_widgets.dart
  catalyst_voices/apps/voices/lib/pages/treasury/sections/treasury_proposal_template_tile.dart
  catalyst_voices/apps/voices/lib/pages/treasury/treasury_body.dart
  catalyst_voices/apps/voices/lib/pages/treasury/treasury_navigation_panel.dart
  catalyst_voices/apps/voices/lib/pages/treasury/treasury_page.dart
  catalyst_voices/apps/voices/lib/widgets/navigation/section_header.dart
  catalyst_voices/apps/voices/lib/widgets/navigation/sections_controller.dart
  catalyst_voices/apps/voices/lib/widgets/navigation/sections_menu.dart
  catalyst_voices/apps/voices/lib/widgets/segments/section_state_builder.dart
  catalyst_voices/apps/voices/lib/widgets/segments/segment_header_tile.dart
  catalyst_voices/apps/voices/lib/widgets/segments/segments_controller.dart
  catalyst_voices/apps/voices/lib/widgets/segments/segments_list_view.dart
  catalyst_voices/apps/voices/lib/widgets/segments/segments_list_view_builder.dart
  catalyst_voices/apps/voices/lib/widgets/segments/segments_menu.dart
  catalyst_voices/apps/voices/lib/widgets/widgets.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/proposal_builder_bloc.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/proposal_builder_event.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/proposal_builder_state.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/catalyst_voices_models.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/document_node_id.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/node_id.dart
  catalyst_voices/packages/internal/catalyst_voices_models/test/document/document_node_id_test.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/document_dto.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/catalyst_voices_view_models.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/navigation/sections_list_view_item.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/navigation/sections_navigation.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/proposal_builder/proposal_builder_segments.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/segments/segments_navigation.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/treasury/treasury_sections.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/treasury/treasury_segments.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/workspace/workspace_sections.dart
Labels: review me, dart, F14

#1483 refactor(cat-gateway): Restructure cat-gateway metrics module
  catalyst-gateway/bin/src/main.rs
  catalyst-gateway/bin/src/metrics/chain_follower.rs
  catalyst-gateway/bin/src/metrics/chain_indexer.rs
  catalyst-gateway/bin/src/metrics/endpoint.rs
  catalyst-gateway/bin/src/metrics/memory.rs
  catalyst-gateway/bin/src/metrics/mod.rs
  catalyst-gateway/bin/src/service/poem_service.rs
  catalyst-gateway/bin/src/service/utilities/middleware/tracing_mw.rs
Labels: rust

#1478 feat(cat-voices): Dropdown selection component
  catalyst_voices/apps/voices/lib/pages/proposal_builder/proposal_builder_guidance_view.dart
  catalyst_voices/apps/voices/lib/widgets/document_builder/single_dropdown_selection_widget.dart
  catalyst_voices/apps/voices/lib/widgets/document_builder/single_grouped_tag_selector_widget.dart
  catalyst_voices/apps/voices/lib/widgets/dropdown/voices_dropdown.dart
  catalyst_voices/apps/voices/lib/widgets/dropdown/voices_dropdown_form_field.dart
  catalyst_voices/apps/voices/lib/widgets/tiles/document_builder_section_tile.dart
  catalyst_voices/apps/voices/lib/widgets/widgets.dart
  catalyst_voices/apps/voices/test/widgets/dropdown/voices_dropdown_test.dart
Labels: review me, ux/ui

#1486 chore(general): update forge cli version to 1.5.1
  .github/workflows/ci.yml
  .github/workflows/flutter-uikit-example-firebase-deploy.yml
  .github/workflows/generate-allure-report.yml
Labels: review me

#1505 fix(flutter/catalyst_key_derivation)!: catalyst key derivation native compilation fix and publishing
  .config/dictionaries/project.dic
  catalyst_voices/apps/voices/android/app/build.gradle
  catalyst_voices/apps/voices/ios/Podfile.lock
  catalyst_voices/apps/voices/ios/Runner.xcodeproj/project.pbxproj
  catalyst_voices/apps/voices/macos/Podfile
  catalyst_voices/apps/voices/macos/Podfile.lock
  catalyst_voices/apps/voices/macos/Runner.xcodeproj/project.pbxproj
  catalyst_voices/melos.yaml
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/README.md
  catalyst_voices/packages/libs/catalyst_cardano_serialization/README.md
  catalyst_voices/packages/libs/catalyst_cardano_serialization/example/main.dart
  catalyst_voices/packages/libs/catalyst_key_derivation/.earthlyignore
  catalyst_voices/packages/libs/catalyst_key_derivation/.gitignore
  catalyst_voices/packages/libs/catalyst_key_derivation/.pubignore
  catalyst_voices/packages/libs/catalyst_key_derivation/assets/js/catalyst_key_derivation.js
  catalyst_voices/packages/libs/catalyst_key_derivation/assets/js/catalyst_key_derivation_bg.wasm
  catalyst_voices/packages/libs/catalyst_key_derivation/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_key_derivation/rust/src/frb_generated.rs
Labels: bug, review me, dart

#1507 chore(flutter): publish packages
  .markdownlint-cli2.jsonc
  catalyst_voices/CHANGELOG.md
  catalyst_voices/apps/voices/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_blocs/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_models/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_repositories/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_services/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_shared/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_view_models/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/CHANGELOG.md
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/example/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano_platform_interface/CHANGELOG.md
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano_platform_interface/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano_web/CHANGELOG.md
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano_web/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cardano_serialization/CHANGELOG.md
  catalyst_voices/packages/libs/catalyst_cardano_serialization/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_key_derivation/CHANGELOG.md
  catalyst_voices/packages/libs/catalyst_key_derivation/pubspec.yaml
  catalyst_voices/utilities/uikit_example/pubspec.yaml
Labels: review me, dart

#1485 test(cat-gateway): schemathesis for health endpoints
  .gitignore
  Overall,
  catalyst-gateway/tests/schemathesis_tests/.gitignore
  catalyst-gateway/tests/schemathesis_tests/Earthfile
Labels: review me

#1491 test(cat-voices): Adding account tests
  catalyst_voices/apps/voices/integration_test/all_test.dart
  catalyst_voices/apps/voices/integration_test/pageobject/account_dropdown_page.dart
  catalyst_voices/apps/voices/integration_test/pageobject/app_bar_page.dart
  catalyst_voices/apps/voices/integration_test/suites/account_test.dart
  catalyst_voices/apps/voices/integration_test/suites/app_test.dart
  catalyst_voices/apps/voices/lib/pages/account/account_popup.dart
  catalyst_voices/apps/voices/lib/widgets/app_bar/session/session_state_header.dart
Labels: review me

#1492 feat(cat-voices): Add link(s) component
  catalyst_voices/apps/voices/lib/common/ext/document_property_ext.dart
  catalyst_voices/apps/voices/lib/widgets/document_builder/single_line_https_url_widget.dart.dart
  catalyst_voices/apps/voices/lib/widgets/text_field/voices_https_text_field.dart
  catalyst_voices/apps/voices/lib/widgets/text_field/voices_text_field.dart
  catalyst_voices/apps/voices/lib/widgets/tiles/document_builder_section_tile.dart
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/definitions/single_line_https_url_entry_definition.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/document_validator.dart
  catalyst_voices/packages/internal/catalyst_voices_models/test/document/validation/document_validation_test.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/document/validation/localized_document_validation_result.dart
Labels: review me, ux/ui

#1494 feat(cat-voices): cip36 registrations consolidated endpoint
  .config/dictionaries/project.dic
  catalyst-gateway/bin/src/db/index/queries/cql/get_all_stake_addrs.cql
  catalyst-gateway/bin/src/db/index/queries/mod.rs
  catalyst-gateway/bin/src/db/index/queries/registrations/get_all_stakes_and_vote_keys.rs
  catalyst-gateway/bin/src/db/index/queries/registrations/get_from_stake_addr.rs
  catalyst-gateway/bin/src/db/index/queries/registrations/get_invalid.rs
  catalyst-gateway/bin/src/db/index/queries/registrations/mod.rs
  catalyst-gateway/bin/src/db/index/schema/cql/cip36_registration_for_vote_key.cql
  catalyst-gateway/bin/src/db/index/tests/scylla_queries.rs
  catalyst-gateway/bin/src/service/api/cardano/cip36/endpoint.rs
  catalyst-gateway/bin/src/service/api/cardano/cip36/filter.rs
  catalyst-gateway/bin/src/service/api/cardano/cip36/mod.rs
  catalyst-gateway/bin/src/service/api/cardano/cip36/old_endpoint.rs
  catalyst-gateway/bin/src/service/api/cardano/cip36/response.rs
  catalyst-gateway/bin/src/service/common/objects/cardano/cip36.rs
  catalyst-gateway/bin/src/service/common/objects/cardano/mod.rs
  catalyst-gateway/bin/src/service/common/types/cardano/cip19_stake_address.rs
  catalyst-gateway/bin/src/service/common/types/cardano/nonce.rs
  catalyst-gateway/bin/src/service/common/types/cardano/query/as_at.rs
  catalyst-gateway/bin/src/service/common/types/cardano/query/mod.rs
  catalyst-gateway/bin/src/service/common/types/cardano/query/stake_or_voter.rs
  catalyst-gateway/bin/src/service/common/types/cardano/slot_no.rs
  catalyst-gateway/bin/src/service/common/types/cardano/txn_index.rs
  catalyst-gateway/bin/src/service/common/types/generic/ed25519_public_key.rs
Labels: review me, F14

#1508 feat(cat-voices): Yes/No choice component
  catalyst_voices/apps/voices/lib/widgets/document_builder/yes_no_choice_widget.dart
  catalyst_voices/apps/voices/lib/widgets/tiles/document_builder_section_tile.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/definitions/yes_no_choice_definition.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/document_validator.dart
Labels: review me, ux/ui

#1495 feat(cat-gateway): Improve observability and metrics
  catalyst-gateway/bin/src/main.rs
  catalyst-gateway/bin/src/metrics/chain_follower.rs
  catalyst-gateway/bin/src/metrics/chain_indexer.rs
  catalyst-gateway/bin/src/metrics/endpoint.rs
  catalyst-gateway/bin/src/metrics/memory.rs
  catalyst-gateway/bin/src/metrics/mod.rs
  catalyst-gateway/bin/src/service/poem_service.rs
  catalyst-gateway/bin/src/service/utilities/middleware/tracing_mw.rs
Labels: draft, rust, comment me

#1470 feat(cat-gateway): Add document endpoints
  .config/dictionaries/project.dic
  Earthfile
  catalyst-gateway/Earthfile
  catalyst-gateway/bin/Cargo.toml
  catalyst-gateway/bin/src/service/api/documents/get_document.rs
  catalyst-gateway/bin/src/service/api/documents/mod.rs
  catalyst-gateway/bin/src/service/api/documents/post_document_index_query/mod.rs
  catalyst-gateway/bin/src/service/api/documents/post_document_index_query/query_filter.rs
  catalyst-gateway/bin/src/service/api/documents/post_document_index_query/response.rs
  catalyst-gateway/bin/src/service/api/documents/put_document/bad_put_request.rs
  catalyst-gateway/bin/src/service/api/documents/put_document/mod.rs
  catalyst-gateway/bin/src/service/api/mod.rs
  catalyst-gateway/bin/src/service/common/objects/document/mod.rs
  catalyst-gateway/bin/src/service/common/objects/mod.rs
  catalyst-gateway/bin/src/service/common/tags.rs
  catalyst-gateway/bin/src/service/common/types/document/doc_ref.rs
  catalyst-gateway/bin/src/service/common/types/document/doc_type.rs
  catalyst-gateway/bin/src/service/common/types/document/id.rs
  catalyst-gateway/bin/src/service/common/types/document/mod.rs
  catalyst-gateway/bin/src/service/common/types/document/ver.rs
  catalyst-gateway/bin/src/service/common/types/generic/mod.rs
  catalyst-gateway/bin/src/service/common/types/generic/uuidv4.rs
  catalyst-gateway/bin/src/service/common/types/generic/uuidv7.rs
  catalyst-gateway/bin/src/service/common/types/mod.rs
  catalyst-gateway/bin/src/service/common/types/payload/cbor.rs
  catalyst-gateway/bin/src/service/common/types/payload/mod.rs
  catalyst-gateway/event-db/Earthfile
  catalyst-gateway/tests/Earthfile
  catalyst-gateway/tests/api_tests/Earthfile
  catalyst-gateway/tests/schemathesis_tests/Earthfile
  catalyst_voices/Earthfile
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/wallet-automation/Earthfile
  catalyst_voices/packages/libs/catalyst_key_derivation/Earthfile
  catalyst_voices/packages/libs/catalyst_key_derivation/rust/Earthfile
  catalyst_voices/utilities/uikit_example/Earthfile
  docs/Earthfile
  docs/src/api/cat-gateway/.pages
  docs/src/api/cat-gateway/index.md
  docs/src/api/cat-gateway/openapi-explorer.md
  docs/src/api/cat-gateway/openapi-scalar.md
  docs/src/api/cat-gateway/openapi-spec.md
  docs/src/api/cat-gateway/openapi-stoplight-elements.md
  docs/src/api/cat-gateway/openapi-swagger.md
  docs/src/api/cat-gateway/templates/openapi_explorer.html
  docs/src/api/cat-gateway/templates/scalar.html
  docs/src/api/cat-gateway/templates/stoplight_elements.html
  docs/src/api/cat-gateway/templates/swagger.html
  utilities/docs-preview/Earthfile
Labels: draft

#1517 feat(cat-voices): plain text component for single and multiline
  .config/dictionaries/project.dic
  catalyst_voices/apps/voices/lib/common/ext/guidance_ext.dart
  catalyst_voices/apps/voices/lib/dependency/dependencies.dart
  catalyst_voices/apps/voices/lib/widgets/cards/campaign_stage_card.dart
  catalyst_voices/apps/voices/lib/widgets/common/resizable_box_parent.dart
  catalyst_voices/apps/voices/lib/widgets/document_builder/simple_text_entry_widget.dart
  catalyst_voices/apps/voices/lib/widgets/text_field/voices_text_field.dart
  catalyst_voices/apps/voices/lib/widgets/tiles/document_builder_section_tile.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/campaign/campaign_builder/campaign_builder_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_driver/lib/src/extension.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/definitions/nested_questions_definition.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/schema/document_schema_property_dto.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/utils/launch_url_mixin.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/authentication/access_control.dart
Labels: review me, ux/ui

#1499 feat(cat-gateway): Add memory metrics to improve observability
  catalyst-gateway/bin/Cargo.toml
  catalyst-gateway/bin/src/metrics/memory.rs
  catalyst-gateway/bin/src/metrics/mod.rs
  catalyst-gateway/bin/src/settings/mod.rs
  catalyst-gateway/bin/src/settings/str_env_var.rs
Labels: review me, rust

#1504 test(cat-gateway): adds nightly schemathesis
  catalyst-gateway/tests/schemathesis_tests/Earthfile
  catalyst-gateway/tests/schemathesis_tests/blueprint.cue
Labels: review me

#1526 feat(cat-voices): new overlay and dropshadow colors
  catalyst_voices/apps/voices/lib/common/ext/space_ext.dart
  catalyst_voices/apps/voices/lib/pages/account/account_page.dart
  catalyst_voices/apps/voices/lib/pages/campaign/admin_tools/campaign_admin_tools_dialog.dart
  catalyst_voices/apps/voices/lib/pages/campaign/details/widgets/campaign_management.dart
  catalyst_voices/apps/voices/lib/pages/discovery/discovery_page.dart
  catalyst_voices/apps/voices/lib/pages/overall_spaces/brands_navigation.dart
  catalyst_voices/apps/voices/lib/pages/registration/upload_seed_phrase_confirmation_dialog.dart
  catalyst_voices/apps/voices/lib/pages/registration/wallet_link/account_role_dialog.dart
  catalyst_voices/apps/voices/lib/pages/registration/wallet_link/stage/rbac_transaction_panel.dart
  catalyst_voices/apps/voices/lib/pages/registration/widgets/exit_confirm_dialog.dart
  catalyst_voices/apps/voices/lib/pages/registration/widgets/wallet_summary.dart
  catalyst_voices/apps/voices/lib/widgets/buttons/voices_icon_button.dart
  catalyst_voices/apps/voices/lib/widgets/cards/campaign_stage_card.dart
  catalyst_voices/apps/voices/lib/widgets/cards/funded_proposal_card.dart
  catalyst_voices/apps/voices/lib/widgets/cards/role_chooser_card.dart
  catalyst_voices/apps/voices/lib/widgets/chips/voices_chip.dart
  catalyst_voices/apps/voices/lib/widgets/containers/roles_summary_container.dart
  catalyst_voices/apps/voices/lib/widgets/containers/workspace_text_tile_container.dart
  catalyst_voices/apps/voices/lib/widgets/dropdown/voices_dropdown.dart
  catalyst_voices/apps/voices/lib/widgets/indicators/voices_indicator.dart
  catalyst_voices/apps/voices/lib/widgets/modals/voices_desktop_dialog.dart
  catalyst_voices/apps/voices/lib/widgets/modals/voices_upload_file_dialog.dart
  catalyst_voices/apps/voices/lib/widgets/pickers/voices_time_picker.dart
  catalyst_voices/apps/voices/lib/widgets/text_field/seed_phrase_field.dart
  catalyst_voices/apps/voices/lib/widgets/text_field/voices_date_time_text_field.dart
  catalyst_voices/apps/voices/lib/widgets/text_field/voices_text_field.dart
  catalyst_voices/apps/voices/lib/widgets/tiles/selectable_tile.dart
  catalyst_voices/apps/voices/lib/widgets/toggles/voices_checkbox.dart
  catalyst_voices/packages/internal/catalyst_voices_brands/lib/src/theme_extensions/voices_color_scheme.dart
  catalyst_voices/packages/internal/catalyst_voices_brands/lib/src/themes/catalyst.dart
  catalyst_voices/packages/internal/catalyst_voices_brands/lib/src/themes/widgets/buttons_theme.dart
  catalyst_voices/packages/internal/catalyst_voices_brands/lib/src/themes/widgets/toggles_theme.dart
  catalyst_voices/packages/internal/catalyst_voices_brands/lib/src/themes/widgets/voices_dialog_theme.dart
  catalyst_voices/packages/internal/catalyst_voices_brands/lib/src/themes/widgets/voices_input_decoration_theme.dart
  catalyst_voices/utilities/uikit_example/lib/examples/voices_avatar_example.dart
  catalyst_voices/utilities/uikit_example/lib/examples/voices_badge_example.dart
  catalyst_voices/utilities/uikit_example/lib/examples/voices_modals_example.dart
Labels: review me, dart

#1490 test(cat-voices): Store and restore seeds during onboarding create
  catalyst_voices/apps/voices/integration_test/pageobject/common_page.dart
  catalyst_voices/apps/voices/integration_test/pageobject/onboarding_page.dart
  catalyst_voices/apps/voices/integration_test/pageobject/spaces_drawer_page.dart
  catalyst_voices/apps/voices/integration_test/suites/account_test.dart
  catalyst_voices/apps/voices/integration_test/suites/app_test.dart
  catalyst_voices/apps/voices/integration_test/suites/onboarding_test.dart
  catalyst_voices/apps/voices/integration_test/types/password_validation_states.dart
  catalyst_voices/apps/voices/integration_test/utils/constants.dart
  catalyst_voices/apps/voices/integration_test/utils/selector_utils.dart
  catalyst_voices/apps/voices/integration_test/utils/test_context.dart
  catalyst_voices/apps/voices/lib/pages/registration/finish_account/finish_account_creation_panel.dart
  catalyst_voices/apps/voices/lib/pages/registration/recover/recover_method_panel.dart
  catalyst_voices/apps/voices/lib/pages/registration/wallet_link/stage/intro_panel.dart
  catalyst_voices/apps/voices/lib/pages/registration/wallet_link/stage/select_wallet_panel.dart
  catalyst_voices/apps/voices/lib/pages/registration/widgets/next_step.dart
  catalyst_voices/apps/voices/lib/pages/registration/widgets/registration_tile.dart
  catalyst_voices/apps/voices/lib/pages/registration/widgets/unlock_password_form.dart
  catalyst_voices/apps/voices/lib/widgets/indicators/voices_password_strength_indicator.dart
  catalyst_voices/apps/voices/lib/widgets/seed_phrase/seed_phrases_sequencer.dart
  catalyst_voices/apps/voices/lib/widgets/separators/voices_text_divider.dart
  catalyst_voices/apps/voices/lib/widgets/text_field/voices_text_field.dart
Labels: review me

#1510 feat(cat-gateway): Catalyst signed docs endpoints initial implementation
  catalyst-gateway/bin/Cargo.toml
  catalyst-gateway/bin/src/db/event/signed_docs/full_signed_doc.rs
  catalyst-gateway/bin/src/db/event/signed_docs/query_filter.rs
  catalyst-gateway/bin/src/db/event/signed_docs/signed_doc_body.rs
  catalyst-gateway/bin/src/db/event/signed_docs/sql/filtered_select_signed_documents.sql.jinja
  catalyst-gateway/bin/src/db/event/signed_docs/sql/insert_signed_documents.sql
  catalyst-gateway/bin/src/db/event/signed_docs/sql/select_signed_documents.sql.jinja
  catalyst-gateway/bin/src/db/event/signed_docs/tests/mod.rs
  catalyst-gateway/bin/src/service/api/documents/get_document.rs
  catalyst-gateway/bin/src/service/api/documents/mod.rs
  catalyst-gateway/bin/src/service/api/documents/post_document_index_query/mod.rs
  catalyst-gateway/bin/src/service/api/documents/post_document_index_query/query_filter.rs
  catalyst-gateway/bin/src/service/api/documents/put_document/bad_put_request.rs
  catalyst-gateway/bin/src/service/api/documents/put_document/mod.rs
  catalyst-gateway/bin/src/service/common/auth/rbac/scheme.rs
  catalyst-gateway/event-db/migrations/V2__signed_documents.sql
  catalyst-gateway/tests/api_tests/api_tests/put_document.hurl
Labels: review me

#1188 feat(cat-gateway): Purge volatile data after immutable roll forward
  catalyst-gateway/bin/src/cardano/mod.rs
  catalyst-gateway/bin/src/db/index/block/mod.rs
  catalyst-gateway/bin/src/db/index/block/roll_forward.rs
  catalyst-gateway/bin/src/db/index/queries/mod.rs
  catalyst-gateway/bin/src/db/index/queries/purge/chain_root_for_role0_key.rs
  catalyst-gateway/bin/src/db/index/queries/purge/chain_root_for_stake_address.rs
  catalyst-gateway/bin/src/db/index/queries/purge/chain_root_for_txn_id.rs
  catalyst-gateway/bin/src/db/index/queries/purge/cip36_registration.rs
  catalyst-gateway/bin/src/db/index/queries/purge/cip36_registration_for_vote_key.rs
  catalyst-gateway/bin/src/db/index/queries/purge/cip36_registration_invalid.rs
  catalyst-gateway/bin/src/db/index/queries/purge/cql/delete_chain_root_for_role0_key.cql
  catalyst-gateway/bin/src/db/index/queries/purge/cql/delete_chain_root_for_stake_addr.cql
  catalyst-gateway/bin/src/db/index/queries/purge/cql/delete_chain_root_for_txn_id.cql
  catalyst-gateway/bin/src/db/index/queries/purge/cql/delete_cip36_registration.cql
  catalyst-gateway/bin/src/db/index/queries/purge/cql/delete_cip36_registration_for_vote_key.cql
  catalyst-gateway/bin/src/db/index/queries/purge/cql/delete_cip36_registration_invalid.cql
  catalyst-gateway/bin/src/db/index/queries/purge/cql/delete_rbac509_registration.cql
  catalyst-gateway/bin/src/db/index/queries/purge/cql/delete_stake_registration.cql
  catalyst-gateway/bin/src/db/index/queries/purge/cql/delete_txi_by_txn_hashes.cql
  catalyst-gateway/bin/src/db/index/queries/purge/cql/delete_txo_assets_by_stake_addr.cql
  catalyst-gateway/bin/src/db/index/queries/purge/cql/delete_txo_by_stake_address.cql
  catalyst-gateway/bin/src/db/index/queries/purge/cql/delete_unstaked_txo_assets_by_txn_hash.cql
  catalyst-gateway/bin/src/db/index/queries/purge/cql/delete_unstaked_txo_by_txn_hash.cql
  catalyst-gateway/bin/src/db/index/queries/purge/cql/get_chain_root_for_role0_key.cql
  catalyst-gateway/bin/src/db/index/queries/purge/cql/get_chain_root_for_stake_addr.cql
  catalyst-gateway/bin/src/db/index/queries/purge/cql/get_chain_root_for_txn_id.cql
  catalyst-gateway/bin/src/db/index/queries/purge/cql/get_cip36_registration.cql
  catalyst-gateway/bin/src/db/index/queries/purge/cql/get_cip36_registration_for_vote_key.cql
  catalyst-gateway/bin/src/db/index/queries/purge/cql/get_cip36_registration_invalid.cql
  catalyst-gateway/bin/src/db/index/queries/purge/cql/get_rbac509_registration.cql
  catalyst-gateway/bin/src/db/index/queries/purge/cql/get_stake_registration.cql
  catalyst-gateway/bin/src/db/index/queries/purge/cql/get_txi_by_txn_hashes.cql
  catalyst-gateway/bin/src/db/index/queries/purge/cql/get_txo_assets_by_stake_addr.cql
  catalyst-gateway/bin/src/db/index/queries/purge/cql/get_txo_by_stake_address.cql
  catalyst-gateway/bin/src/db/index/queries/purge/cql/get_unstaked_txo_assets_by_txn_hash.cql
  catalyst-gateway/bin/src/db/index/queries/purge/cql/get_unstaked_txo_by_txn_hash.cql
  catalyst-gateway/bin/src/db/index/queries/purge/mod.rs
  catalyst-gateway/bin/src/db/index/queries/purge/rbac509_registration.rs
  catalyst-gateway/bin/src/db/index/queries/purge/stake_registration.rs
  catalyst-gateway/bin/src/db/index/queries/purge/txi_by_hash.rs
  catalyst-gateway/bin/src/db/index/queries/purge/txo_ada.rs
  catalyst-gateway/bin/src/db/index/queries/purge/txo_assets.rs
  catalyst-gateway/bin/src/db/index/queries/purge/unstaked_txo_ada.rs
  catalyst-gateway/bin/src/db/index/queries/purge/unstaked_txo_assets.rs
  catalyst-gateway/bin/src/db/index/schema/cql/chain_root_for_role0_key.cql
  catalyst-gateway/bin/src/db/index/schema/cql/chain_root_for_stake_addr.cql
  catalyst-gateway/bin/src/db/index/schema/cql/chain_root_for_txn_id.cql
  catalyst-gateway/bin/src/db/index/schema/cql/unstaked_txo_assets_by_txn_hash.cql
  catalyst-gateway/bin/src/db/index/session.rs
  catalyst-gateway/bin/src/settings/mod.rs
Labels: review me

#1532 feat(cat-voices): Rich text component
  catalyst_voices/apps/voices/lib/widgets/document_builder/multiline_text_entry_markdown_widget.dart
  catalyst_voices/apps/voices/lib/widgets/rich_text/voices_rich_text.dart
  catalyst_voices/apps/voices/lib/widgets/rich_text/voices_rich_text_limit.dart
  catalyst_voices/apps/voices/lib/widgets/text_field/voices_date_time_text_field.dart
  catalyst_voices/apps/voices/lib/widgets/tiles/document_builder_section_tile.dart
  catalyst_voices/apps/voices/test/widgets/rich_text/voices_rich_text_test.dart
  catalyst_voices/utilities/uikit_example/lib/examples/voices_rich_text_example.dart
Labels: review me, ux/ui

#1528 feat(cat-voices): guarded get started
  catalyst_voices/apps/voices/integration_test/suites/onboarding_test.dart
  catalyst_voices/apps/voices/lib/dependency/dependencies.dart
  catalyst_voices/apps/voices/lib/pages/account/account_popup.dart
  catalyst_voices/apps/voices/lib/pages/spaces/appbar/session_action_header.dart
  catalyst_voices/apps/voices/lib/pages/spaces/appbar/session_state_header.dart
  catalyst_voices/apps/voices/lib/pages/spaces/spaces_shell_page.dart
  catalyst_voices/apps/voices/lib/routes/guards/user_access_guard.dart
  catalyst_voices/apps/voices/lib/widgets/widgets.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/session/session_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/session/session_state.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/test/session/session_cubit_test.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/registration/registration_service.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/account/session_account.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/catalyst_voices_view_models.dart
Labels: review me, dart

#1555 fix(cat-voices): proposal builder shows old values after saving
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/proposal_builder/proposal_builder_segments.dart
Labels: bug, do not merge yet, review me, dart

#1562 feat(cat-voices): How it works - Discovery Page
  catalyst_voices/apps/voices/lib/pages/discovery/how_it_works.dart
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
Labels: review me, ux/ui, F14

#1530 chore(general): update nightly to forge
  .github/workflows/generate-allure-report.yml
  .github/workflows/nightly-ci.yml
  catalyst-gateway/tests/schemathesis_tests/.gitignore
  catalyst-gateway/tests/schemathesis_tests/Earthfile
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/wallet-automation/blueprint.cue
Labels: review me

#1582 test(cat-voices): tests lock and unlock account
  catalyst_voices/apps/voices/integration_test/all_test.dart
  catalyst_voices/apps/voices/integration_test/pageobject/app_bar_page.dart
  catalyst_voices/apps/voices/integration_test/pageobject/unlock_modal_page.dart
  catalyst_voices/apps/voices/integration_test/suites/account_test.dart
  catalyst_voices/apps/voices/lib/pages/account/unlock_keychain_dialog.dart
  catalyst_voices/apps/voices/lib/pages/spaces/appbar/session_action_header.dart
Labels: review me

#1580 feat(cat-voices): registration create keychain f14 updates
  catalyst_voices/apps/voices/lib/pages/registration/create_keychain/stage/seed_phrase_check_panel.dart
  catalyst_voices/apps/voices/lib/pages/registration/create_keychain/stage/seed_phrase_panel.dart
  catalyst_voices/apps/voices/lib/pages/registration/create_keychain/stage/splash_panel.dart
  catalyst_voices/apps/voices/lib/pages/registration/recover/seed_phrase/seed_phrase_input_panel.dart
  catalyst_voices/apps/voices/lib/pages/registration/registration_dialog.dart
  catalyst_voices/apps/voices/lib/pages/registration/widgets/export_catalyst_key_confirm_dialog.dart
  catalyst_voices/apps/voices/lib/pages/registration/widgets/information_panel.dart
  catalyst_voices/apps/voices/lib/pages/registration/widgets/registration_confirm_dialog.dart
  catalyst_voices/apps/voices/lib/pages/registration/widgets/seed_phrase_actions.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/registration/cubits/keychain_creation_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
Labels: review me, dart

#1604 feat(cat-voices): add segment icons for proposal builder
  catalyst_voices/packages/internal/catalyst_voices_assets/assets/document_templates/proposal/F14-Generic/0ce8ab38-9258-4fbc-a62e-7faa6e58318f.schema.json
  catalyst_voices/packages/internal/catalyst_voices_assets/assets/document_templates/proposal/F14-Generic/example.proposal.json
  catalyst_voices/packages/internal/catalyst_voices_assets/lib/src/assets_ext.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/proposal_builder_bloc.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/schema/property/document_object_schema.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/schema/document_property_schema_dto.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/schema/mapper/document_object_schema_mapper.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/proposal_builder/proposal_builder_segments.dart
Labels: review me, dart

#1608 feat(cat-voices): registration waller link f14 updates
  catalyst_voices/apps/voices/lib/common/ext/account_role_ext.dart
  catalyst_voices/apps/voices/lib/pages/registration/account_completed/account_completed_panel.dart
  catalyst_voices/apps/voices/lib/pages/registration/recover/seed_phrase/account_details_panel.dart
  catalyst_voices/apps/voices/lib/pages/registration/wallet_link/account_role_dialog.dart
  catalyst_voices/apps/voices/lib/pages/registration/wallet_link/stage/wallet_details_panel.dart
  catalyst_voices/apps/voices/lib/pages/registration/widgets/wallet_summary.dart
  catalyst_voices/apps/voices/lib/widgets/cards/role_chooser_card.dart
  catalyst_voices/apps/voices/lib/widgets/containers/roles_chooser_container.dart
  catalyst_voices/apps/voices/lib/widgets/containers/roles_summary_container.dart
  catalyst_voices/apps/voices/lib/widgets/menu/voices_wallet_tile.dart
  catalyst_voices/packages/internal/catalyst_voices_assets/assets/icons/summary.svg
  catalyst_voices/packages/internal/catalyst_voices_assets/assets/images/2.0x/role_drep.webp
  catalyst_voices/packages/internal/catalyst_voices_assets/assets/images/2.0x/role_proposer.webp
  catalyst_voices/packages/internal/catalyst_voices_assets/assets/images/2.0x/role_voter.webp
  catalyst_voices/packages/internal/catalyst_voices_assets/assets/images/3.0x/role_drep.webp
  catalyst_voices/packages/internal/catalyst_voices_assets/assets/images/3.0x/role_proposer.webp
  catalyst_voices/packages/internal/catalyst_voices_assets/assets/images/3.0x/role_voter.webp
  catalyst_voices/packages/internal/catalyst_voices_assets/assets/images/dummy_catalyst_voices.webp
  catalyst_voices/packages/internal/catalyst_voices_assets/assets/images/registration_summary_keychain.png
  catalyst_voices/packages/internal/catalyst_voices_assets/assets/images/registration_summary_roles.png
  catalyst_voices/packages/internal/catalyst_voices_assets/assets/images/registration_summary_wallet.png
  catalyst_voices/packages/internal/catalyst_voices_assets/assets/images/role_drep.svg
  catalyst_voices/packages/internal/catalyst_voices_assets/assets/images/role_drep.webp
  catalyst_voices/packages/internal/catalyst_voices_assets/assets/images/role_info_drep.png
  catalyst_voices/packages/internal/catalyst_voices_assets/assets/images/role_info_proposer.png
  catalyst_voices/packages/internal/catalyst_voices_assets/assets/images/role_info_voter.png
  catalyst_voices/packages/internal/catalyst_voices_assets/assets/images/role_proposer.svg
  catalyst_voices/packages/internal/catalyst_voices_assets/assets/images/role_proposer.webp
  catalyst_voices/packages/internal/catalyst_voices_assets/assets/images/role_voter.svg
  catalyst_voices/packages/internal/catalyst_voices_assets/assets/images/role_voter.webp
  catalyst_voices/packages/internal/catalyst_voices_assets/example/lib/src/main.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/registration/cubits/recover_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/registration/cubits/wallet_link_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/user/account_role.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/registration/exception/localized_registration_exception.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/registration/wallet_summary.dart
  catalyst_voices/utilities/uikit_example/lib/examples/voices_role_panels_example.dart
Labels: review me, dart, F14

#1611 feat(cat-voices): account recovery f14 updates
  catalyst_voices/apps/voices/lib/pages/registration/recover/recover_method_panel.dart
  catalyst_voices/apps/voices/lib/pages/registration/widgets/registration_tile.dart
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
Labels: review me, dart, F14

#1529 feat(cat-gateway): Add Chain Follower metrics to improve observability
  catalyst-gateway/bin/Cargo.toml
  catalyst-gateway/bin/src/metrics/chain_follower.rs
  catalyst-gateway/bin/src/metrics/chain_follower/mod.rs
  catalyst-gateway/bin/src/metrics/chain_follower/reporter.rs
  catalyst-gateway/bin/src/metrics/memory.rs
  catalyst-gateway/bin/src/metrics/mod.rs
  catalyst-gateway/bin/src/settings/mod.rs
Labels: review me, rust

#1613 feat(cat-voices): update proposal template and add document property getter
  catalyst_voices/packages/internal/catalyst_voices_assets/assets/document_templates/proposal/F14-Generic/0ce8ab38-9258-4fbc-a62e-7faa6e58318f.schema.json
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/document.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/schema/document_schema.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/schema/property/document_boolean_schema.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/schema/property/document_integer_schema.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/schema/property/document_list_schema.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/schema/property/document_number_schema.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/schema/property/document_object_schema.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/schema/property/document_string_schema.dart
  catalyst_voices/packages/internal/catalyst_voices_models/test/document/builder/document_builder_test.dart
  catalyst_voices/packages/internal/catalyst_voices_models/test/document/document_test.dart
Labels: review me, dart

#1631 fix(cat-gateway): adds missing example apikey for cat-gateway
  catalyst-gateway/Justfile
Labels: review me

#1614 feat(cat-voices): Current campaign - Discovery Page
  catalyst_voices/apps/voices/lib/common/ext/build_context_ext.dart
  catalyst_voices/apps/voices/lib/common/ext/ext.dart
  catalyst_voices/apps/voices/lib/common/formatters/amount_formatter.dart
  catalyst_voices/apps/voices/lib/common/formatters/date_formatter.dart
  catalyst_voices/apps/voices/lib/pages/discovery/current_campaign.dart
  catalyst_voices/apps/voices/lib/pages/discovery/discovery_page.dart
  catalyst_voices/apps/voices/lib/pages/discovery/hero_section.dart
  catalyst_voices/apps/voices/lib/widgets/heroes/section_hero.dart
  catalyst_voices/apps/voices/test/common/formatters/date_formatter_test.dart
  catalyst_voices/apps/voices/test/helpers/pump_app.dart
  catalyst_voices/packages/internal/catalyst_voices_brands/lib/src/theme_extensions/voices_color_scheme.dart
  catalyst_voices/packages/internal/catalyst_voices_brands/lib/src/themes/catalyst.dart
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/catalyst_voices_shared.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/range/date_range.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/test/src/range/date_range_test.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/campaign/campaign_timeline.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/campaign/current_campaign_info_view_model.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/catalyst_voices_view_models.dart
Labels: review me, ux/ui, F14

#1575 feat(cat-voices): added x-icons to the schema template, aligned the json schema template with the F14 template document
  docs/src/architecture/08_concepts/document_templates/proposal/F14-Generic/0ce8ab38-9258-4fbc-a62e-7faa6e58318f.schema.json
  docs/src/architecture/08_concepts/document_templates/proposal/F14-Generic/example.proposal.json
Labels: review me, comment me, F14

#1633 feat(cat-voices): proposal editor minor UI fixes
  catalyst_voices/apps/voices/lib/common/ext/document_property_schema_ext.dart
  catalyst_voices/apps/voices/lib/common/ext/text_editing_controller_ext.dart
  catalyst_voices/apps/voices/lib/pages/proposal_builder/proposal_builder_segments.dart
  catalyst_voices/apps/voices/lib/pages/registration/create_keychain/stage/unlock_password_panel.dart
  catalyst_voices/apps/voices/lib/pages/registration/recover/seed_phrase/unlock_password_panel.dart
  catalyst_voices/apps/voices/lib/widgets/document_builder/agreement_confirmation_widget.dart
  catalyst_voices/apps/voices/lib/widgets/document_builder/multiline_text_entry_markdown_widget.dart
  catalyst_voices/apps/voices/lib/widgets/document_builder/simple_text_entry_widget.dart
  catalyst_voices/apps/voices/lib/widgets/document_builder/single_dropdown_selection_widget.dart
  catalyst_voices/apps/voices/lib/widgets/document_builder/single_line_https_url_widget.dart.dart
  catalyst_voices/apps/voices/lib/widgets/document_builder/yes_no_choice_widget.dart
  catalyst_voices/apps/voices/lib/widgets/segments/segments_list_view.dart
  catalyst_voices/apps/voices/lib/widgets/text_field/voices_date_field.dart
  catalyst_voices/apps/voices/lib/widgets/text_field/voices_num_field.dart
  catalyst_voices/apps/voices/lib/widgets/text_field/voices_text_field.dart
  catalyst_voices/apps/voices/lib/widgets/text_field/voices_time_field.dart
  catalyst_voices/apps/voices/lib/widgets/tiles/document_builder_section_tile.dart
  catalyst_voices/apps/voices/lib/widgets/toggles/voices_checkbox.dart
  catalyst_voices/packages/internal/catalyst_voices_assets/assets/document_templates/proposal/F14-Generic/0ce8ab38-9258-4fbc-a62e-7faa6e58318f.schema.json
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/validation/document_validator.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/segments/segments_navigation.dart
Labels: review me, dart

#1577 feat(cat-voices): Discovery page layout
  catalyst_voices/apps/voices/lib/common/ext/build_context_ext.dart
  catalyst_voices/apps/voices/lib/common/ext/ext.dart
  catalyst_voices/apps/voices/lib/common/formatters/amount_formatter.dart
  catalyst_voices/apps/voices/lib/common/formatters/date_formatter.dart
  catalyst_voices/apps/voices/lib/pages/discovery/current_campaign.dart
  catalyst_voices/apps/voices/lib/pages/discovery/discovery_page.dart
  catalyst_voices/apps/voices/lib/pages/proposals/proposals_page.dart
  catalyst_voices/apps/voices/lib/routes/routing/spaces_route.dart
  catalyst_voices/apps/voices/lib/widgets/heroes/section_hero.dart
  catalyst_voices/apps/voices/pubspec.yaml
  catalyst_voices/apps/voices/test/common/formatters/date_formatter_test.dart
  catalyst_voices/apps/voices/test/helpers/pump_app.dart
  catalyst_voices/packages/internal/catalyst_voices_assets/assets/videos/hero_desktop.mp4
  catalyst_voices/packages/internal/catalyst_voices_assets/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposals/proposals_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposals/proposals_state.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/test/proposals/proposals_cubit_test.dart
  catalyst_voices/packages/internal/catalyst_voices_brands/lib/src/theme_extensions/voices_color_scheme.dart
  catalyst_voices/packages/internal/catalyst_voices_brands/lib/src/themes/catalyst.dart
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/catalyst_voices_shared.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/range/date_range.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/test/src/range/date_range_test.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/campaign/campaign_timeline.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/campaign/current_campaign_info_view_model.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/catalyst_voices_view_models.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/proposal/proposal_view_model.dart
Labels: review me, ux/ui, F14

#1576 feat(cat-gateway): Catalyst singed Documents indexing `POST` endpoint
  catalyst-gateway/bin/Cargo.toml
  catalyst-gateway/bin/src/db/event/common/eq_or_ranged_uuid.rs
  catalyst-gateway/bin/src/db/event/common/mod.rs
  catalyst-gateway/bin/src/db/event/common/query_limits.rs
  catalyst-gateway/bin/src/db/event/signed_docs/full_signed_doc.rs
  catalyst-gateway/bin/src/db/event/signed_docs/query_filter.rs
  catalyst-gateway/bin/src/db/event/signed_docs/signed_doc_body.rs
  catalyst-gateway/bin/src/db/event/signed_docs/tests/mod.rs
  catalyst-gateway/bin/src/service/api/documents/post_document_index_query/mod.rs
  catalyst-gateway/bin/src/service/api/documents/post_document_index_query/query_filter.rs
  catalyst-gateway/bin/src/service/api/documents/post_document_index_query/response.rs
  catalyst-gateway/bin/src/service/api/documents/put_document/mod.rs
  catalyst-gateway/bin/src/service/common/types/document/doc_type.rs
  catalyst-gateway/bin/src/service/common/types/document/id.rs
  catalyst-gateway/bin/src/service/common/types/document/ver.rs
  catalyst-gateway/bin/src/service/common/types/generic/query/pagination.rs
  catalyst-gateway/tests/api_tests/api_tests/put_document.hurl
  catalyst-gateway/tests/api_tests/api_tests/signed_document.hurl
Labels: review me, rust

#1680 fix(cat-voices): didUpdateWidget can't await async func
  catalyst_voices/apps/voices/lib/widgets/heroes/section_hero.dart
Labels: review me, dart

#1698 test(cat-voices): add automation for lace
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/wallet-automation/playwright.config.ts
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/wallet-automation/tests/wallets.spec.ts
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/wallet-automation/utils/wallets/laceUtils.ts
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/wallet-automation/utils/wallets/walletUtils.ts
Labels: review me, F14

#1672 feat(cat-voices): user settings
  catalyst_voices/apps/voices/lib/app/view/app_session_listener.dart
  catalyst_voices/apps/voices/lib/pages/discovery/current_status_text.dart
  catalyst_voices/apps/voices/lib/pages/discovery/toggle_state_text.dart
  catalyst_voices/apps/voices/lib/pages/spaces/appbar/session_action_header.dart
  catalyst_voices/apps/voices/lib/pages/spaces/appbar/session_state_header.dart
  catalyst_voices/apps/voices/lib/pages/spaces/spaces_shell_page.dart
  catalyst_voices/apps/voices/lib/pages/voting/voting_page.dart
  catalyst_voices/apps/voices/lib/routes/guards/session_unlocked_guard.dart
  catalyst_voices/apps/voices/lib/widgets/text/timezone_date_time_text.dart
  catalyst_voices/apps/voices/lib/widgets/widgets.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/session/session_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/session/session_state.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/test/session/session_cubit_test.dart
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/catalyst_voices_models.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/user/preferences.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/user/user.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/user/user_settings.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/user_dto.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/user/user_repository.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/user/user_service.dart
  catalyst_voices/packages/internal/catalyst_voices_services/test/src/user/user_service_test.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/catalyst_voices_view_models.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/session/session_account.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/session/session_settings.dart
Labels: dart

#1667 feat(cat-voices): campaign categories - discovery page
  catalyst_voices/apps/voices/lib/pages/discovery/discovery_page.dart
  catalyst_voices/apps/voices/lib/widgets/buttons/voices_filled_button.dart
  catalyst_voices/apps/voices/lib/widgets/cards/campaign_category_card.dart
  catalyst_voices/packages/internal/catalyst_voices_assets/assets/images/campaign_category_developer.png
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/formatter/cryptocurrency_formatter.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/campaign/campaign_category.dart
Labels: review me, ux/ui

#1679 feat(cat-voices): copy catalystId
  catalyst_voices/apps/voices/lib/configs/bootstrap.dart
  catalyst_voices/apps/voices/lib/dependency/dependencies.dart
  catalyst_voices/apps/voices/lib/widgets/footers/standard_links_page_footer.dart
  catalyst_voices/apps/voices/lib/widgets/text/catalyst_id_text.dart
  catalyst_voices/apps/voices/lib/widgets/text/link_text.dart
  catalyst_voices/apps/voices/lib/widgets/tooltips/voices_plain_tooltip.dart
  catalyst_voices/apps/voices/lib/widgets/widgets.dart
  catalyst_voices/apps/voices/test/widgets/common/link_text_test.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/test/session/session_cubit_test.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/user/account.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/user/user.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/user_dto.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/user/user_storage.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/dto/user_dto_test.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/registration/registration_service.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/user/user_service.dart
  catalyst_voices/packages/internal/catalyst_voices_services/test/src/user/user_service_test.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/storage/secure_storage.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/test/src/storage/secure_storage_test.dart
Labels: review me, dart

#1695 fix: placeholder and descriptions updated on the proposal template
  docs/src/architecture/08_concepts/document_templates/proposal/F14-Generic/0ce8ab38-9258-4fbc-a62e-7faa6e58318f.schema.json
Labels: enhancement, review me, F14

#1716 fix(docs): Fix invalid md link
  docs/src/architecture/08_concepts/domain-models/index.md
Labels: review me

#1533 test(cat-voices): Enabling integration tests
  .config/dictionaries/project.dic
  .github/workflows/nightly-ci.yml
  catalyst_voices/Earthfile
  catalyst_voices/apps/voices/integration_test/Earthfile
  catalyst_voices/apps/voices/integration_test/suites/onboarding_test.dart
Labels: review me

#1714 feat(cat-voices): validation + section/subsection handling
  catalyst_voices/apps/voices/lib/pages/proposal_builder/proposal_builder_segments.dart
  catalyst_voices/apps/voices/lib/widgets/document_builder/agreement_confirmation_widget.dart
  catalyst_voices/apps/voices/lib/widgets/document_builder/document_token_value_widget.dart
  catalyst_voices/apps/voices/lib/widgets/document_builder/multiline_text_entry_markdown_widget.dart
  catalyst_voices/apps/voices/lib/widgets/document_builder/simple_text_entry_widget.dart
  catalyst_voices/apps/voices/lib/widgets/document_builder/single_dropdown_selection_widget.dart
  catalyst_voices/apps/voices/lib/widgets/document_builder/single_grouped_tag_selector_widget.dart
  catalyst_voices/apps/voices/lib/widgets/document_builder/single_line_https_url_widget.dart.dart
  catalyst_voices/apps/voices/lib/widgets/document_builder/yes_no_choice_widget.dart
  catalyst_voices/apps/voices/lib/widgets/tiles/document_builder_section_tile.dart
  catalyst_voices/packages/internal/catalyst_voices_assets/assets/document_templates/proposal/F14-Generic/0ce8ab38-9258-4fbc-a62e-7faa6e58318f.schema.json
  catalyst_voices/packages/internal/catalyst_voices_assets/assets/document_templates/proposal/F14-Generic/example.proposal.json
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/proposal_builder_bloc.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/test/proposals/proposals_cubit_test.dart
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/builder/document_builder.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/document.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/schema/document_schema.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/schema/property/document_boolean_schema.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/schema/property/document_integer_schema.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/schema/property/document_list_schema.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/schema/property/document_number_schema.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/schema/property/document_object_schema.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/schema/property/document_property_schema.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/schema/property/document_string_schema.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/validation/document_validation_result.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/validation/document_validator.dart
  catalyst_voices/packages/internal/catalyst_voices_models/test/document/builder/document_builder_test.dart
  catalyst_voices/packages/internal/catalyst_voices_models/test/document/document_test.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/document_dto.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/schema/document_property_schema_dto.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/schema/document_schema_dto.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/schema/mapper/document_boolean_schema_mapper.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/schema/mapper/document_integer_schema_mapper.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/schema/mapper/document_list_schema_mapper.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/schema/mapper/document_number_schema_mapper.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/schema/mapper/document_object_schema_mapper.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/schema/mapper/document_string_schema_mapper.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/document/validation/localized_document_validation_result.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/proposal_builder/proposal_builder_segments.dart
Labels: review me, dart, F14

#1689 feat(cat-gateway): Catalyst Signed Documents `POST` endpoint. Improve filtering.
  catalyst-gateway/bin/Cargo.toml
  catalyst-gateway/bin/src/db/event/signed_docs/doc_ref.rs
  catalyst-gateway/bin/src/db/event/signed_docs/mod.rs
  catalyst-gateway/bin/src/db/event/signed_docs/query_filter.rs
  catalyst-gateway/bin/src/db/event/signed_docs/tests/filter_by_field.rs
  catalyst-gateway/bin/src/db/event/signed_docs/tests/mod.rs
  catalyst-gateway/bin/src/service/api/documents/mod.rs
  catalyst-gateway/bin/src/service/api/documents/post_document_index_query/mod.rs
  catalyst-gateway/bin/src/service/api/documents/post_document_index_query/query_filter.rs
  catalyst-gateway/bin/src/service/api/documents/post_document_index_query/response.rs
  catalyst-gateway/bin/src/service/api/documents/put_document/bad_put_request.rs
  catalyst-gateway/bin/src/service/api/documents/put_document/mod.rs
  catalyst-gateway/bin/src/service/common/types/document/doc_ref.rs
  catalyst-gateway/bin/src/service/common/types/document/doc_type.rs
  catalyst-gateway/bin/src/service/common/types/document/id.rs
  catalyst-gateway/bin/src/service/common/types/document/ver.rs
  catalyst-gateway/bin/src/service/common/types/generic/uuidv4.rs
  catalyst-gateway/bin/src/service/common/types/generic/uuidv7.rs
Labels: review me

#1717 feat(cat-voices): update milestone list titles according to the index
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/builder/document_builder.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/schema/property/document_boolean_schema.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/schema/property/document_integer_schema.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/schema/property/document_list_schema.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/schema/property/document_number_schema.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/schema/property/document_object_schema.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/schema/property/document_property_schema.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/schema/property/document_string_schema.dart
  catalyst_voices/packages/internal/catalyst_voices_models/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_models/test/document/builder/document_builder_test.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/document_dto.dart
Labels: review me, dart, F14

#1718 feat(cat-voices): Project duration months picker
  catalyst_voices/apps/voices/lib/widgets/document_builder/duration_in_months_widget.dart
  catalyst_voices/apps/voices/lib/widgets/document_builder/single_dropdown_selection_widget.dart
  catalyst_voices/apps/voices/lib/widgets/document_builder/single_grouped_tag_selector_widget.dart
  catalyst_voices/apps/voices/lib/widgets/dropdown/voices_dropdown.dart
  catalyst_voices/apps/voices/lib/widgets/tiles/document_builder_section_tile.dart
  catalyst_voices/apps/voices/test/widgets/dropdown/voices_dropdown_test.dart
Labels: review me, ux/ui, F14

#1709 feat(cat-voices): account dropdown
  catalyst_voices/apps/voices/lib/app/view/app_content.dart
  catalyst_voices/apps/voices/lib/common/constants/constants.dart
  catalyst_voices/apps/voices/lib/common/ext/preferences_ext.dart
  catalyst_voices/apps/voices/lib/pages/account/account_popup.dart
  catalyst_voices/apps/voices/lib/pages/spaces/appbar/account_popup/session_account_avatar.dart
  catalyst_voices/apps/voices/lib/pages/spaces/appbar/account_popup/session_account_display_name.dart
  catalyst_voices/apps/voices/lib/pages/spaces/appbar/account_popup/session_account_popup_catalyst_id.dart
  catalyst_voices/apps/voices/lib/pages/spaces/appbar/account_popup/session_account_popup_menu.dart
  catalyst_voices/apps/voices/lib/pages/spaces/appbar/account_popup/session_theme_menu_tile.dart
  catalyst_voices/apps/voices/lib/pages/spaces/appbar/account_popup/session_timezone_menu_tile.dart
  catalyst_voices/apps/voices/lib/pages/spaces/appbar/session_state_header.dart
  catalyst_voices/apps/voices/lib/pages/spaces/appbar/spaces_theme_mode_switch.dart
  catalyst_voices/apps/voices/lib/pages/spaces/spaces_shell_page.dart
  catalyst_voices/apps/voices/lib/widgets/avatars/voices_avatar.dart
  catalyst_voices/apps/voices/lib/widgets/common/affix_decorator.dart
  catalyst_voices/apps/voices/lib/widgets/separators/voices_divider.dart
  catalyst_voices/apps/voices/lib/widgets/text/timezone_date_time_text.dart
  catalyst_voices/apps/voices/lib/widgets/tiles/menu_item_tile.dart
  catalyst_voices/apps/voices/lib/widgets/tiles/menu_segments_item_tile.dart
  catalyst_voices/apps/voices/lib/widgets/toggles/voices_theme_mode_switch.dart
  catalyst_voices/apps/voices/lib/widgets/widgets.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/session/session_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_brands/lib/src/themes/catalyst.dart
  catalyst_voices/packages/internal/catalyst_voices_brands/lib/src/themes/widgets/buttons_theme.dart
  catalyst_voices/packages/internal/catalyst_voices_brands/lib/src/themes/widgets/voices_popup_menu_theme.dart
  catalyst_voices/packages/internal/catalyst_voices_brands/lib/src/themes/widgets/voices_segmented_button_theme.dart
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/session/session_account.dart
  catalyst_voices/utilities/uikit_example/lib/main.dart
Labels: review me, dart

#1712 fix(cat-gateway): implement a proper pagination for sign doc
  catalyst-gateway/bin/src/db/event/common/query_limits.rs
  catalyst-gateway/bin/src/db/event/signed_docs/mod.rs
  catalyst-gateway/bin/src/db/event/signed_docs/signed_doc_body.rs
  catalyst-gateway/bin/src/db/event/signed_docs/sql/filtered_count_signed_documents.sql.jinja
  catalyst-gateway/bin/src/db/event/signed_docs/tests/mod.rs
  catalyst-gateway/bin/src/jinja.rs
  catalyst-gateway/bin/src/service/api/documents/post_document_index_query/mod.rs
  catalyst-gateway/bin/src/service/common/types/generic/query/pagination.rs
Labels: enhancement, review me, rust

#1730 feat(cat-voices): language code component
  catalyst_voices/apps/voices/lib/widgets/document_builder/language_code_widget.dart
  catalyst_voices/apps/voices/lib/widgets/tiles/document_builder_section_tile.dart
Labels: review me, ux/ui, F14

#1725 feat(cat-voices): Radio button component
  catalyst_voices/apps/voices/lib/widgets/document_builder/radio_button_selection_widget.dart
  catalyst_voices/apps/voices/lib/widgets/tiles/document_builder_section_tile.dart
  catalyst_voices/apps/voices/lib/widgets/toggles/voices_radio_button_form.dart
  catalyst_voices/apps/voices/test/widgets/toggles/voices_radio_button_form_test.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/schema/property/document_string_schema.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/schema/mapper/document_string_schema_mapper.dart
Labels: review me, ux/ui, F14

#1711 chore(cat-voices): Using TimezoneText in ProposalCard
  catalyst_voices/apps/voices/lib/common/formatters/date_formatter.dart
  catalyst_voices/apps/voices/lib/pages/discovery/discovery_page.dart
  catalyst_voices/apps/voices/lib/widgets/cards/campaign_stage_card.dart
  catalyst_voices/apps/voices/lib/widgets/cards/pending_proposal_card.dart
  catalyst_voices/apps/voices/lib/widgets/scrollbar/voices_slider.dart
  catalyst_voices/apps/voices/lib/widgets/text/day_month_time_text.dart
  catalyst_voices/apps/voices/lib/widgets/text/timezone_date_time_text.dart
  catalyst_voices/apps/voices/test/common/formatters/date_formatter_test.dart
  catalyst_voices/packages/internal/catalyst_voices_brands/lib/src/themes/catalyst.dart
  catalyst_voices/packages/internal/catalyst_voices_brands/lib/src/themes/widgets/slider_theme.dart
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/proposal/proposal_base.dart
Labels: dart

#1713 feat(cat-voices): Mock data for Discovery Page
  .config/dictionaries/project.dic
  catalyst_voices/apps/voices/lib/app/view/app.dart
  catalyst_voices/apps/voices/lib/dependency/dependencies.dart
  catalyst_voices/apps/voices/lib/pages/discovery/current_status_text.dart
  catalyst_voices/apps/voices/lib/pages/discovery/discovery_page.dart
  catalyst_voices/apps/voices/lib/pages/discovery/sections/campaign_categories.dart
  catalyst_voices/apps/voices/lib/pages/discovery/sections/campaign_hero.dart
  catalyst_voices/apps/voices/lib/pages/discovery/sections/current_campaign.dart
  catalyst_voices/apps/voices/lib/pages/discovery/sections/how_it_works.dart
  catalyst_voices/apps/voices/lib/pages/discovery/sections/most_recent_proposals.dart
  catalyst_voices/apps/voices/lib/pages/discovery/state_selectors/campaign_categories_state_selector.dart
  catalyst_voices/apps/voices/lib/pages/discovery/state_selectors/current_campaign_selector.dart
  catalyst_voices/apps/voices/lib/pages/discovery/state_selectors/most_recent_proposals_selector.dart
  catalyst_voices/apps/voices/lib/pages/proposals/proposals_page.dart
  catalyst_voices/apps/voices/lib/routes/routing/spaces_route.dart
  catalyst_voices/apps/voices/lib/widgets/buttons/voices_outlined_button.dart
  catalyst_voices/apps/voices/lib/widgets/cards/campaign_category_card.dart
  catalyst_voices/apps/voices/lib/widgets/cards/pending_proposal_card.dart
  catalyst_voices/apps/voices/lib/widgets/heroes/section_hero.dart
  catalyst_voices/apps/voices/pubspec.yaml
  catalyst_voices/melos.yaml
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/catalyst_voices_blocs.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/discovery/discovery.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/discovery/discovery_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/discovery/discovery_state.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/campaign/current_campaign_info_view_model.dart
Labels: dart

#1749 chore(cat-voices): Making mouse on https text field as a click
  catalyst_voices/apps/voices/lib/widgets/text_field/voices_https_text_field.dart
  catalyst_voices/apps/voices/lib/widgets/text_field/voices_text_field.dart
Labels: review me, ux/ui, F14
