Repository input-output-hk/catalyst-voices, pull requests merged in 2025-02, with the labels that each got.

#1733 fix(cat-gateway): Get static doc template
  Earthfile
  catalyst-gateway/Earthfile
  catalyst-gateway/bin/Cargo.toml
  catalyst-gateway/bin/src/db/event/config/key.rs
  catalyst-gateway/bin/src/service/api/documents/get_document.rs
  catalyst-gateway/bin/src/service/api/documents/mod.rs
  catalyst-gateway/bin/src/service/api/documents/templates/mod.rs
  catalyst-gateway/bin/src/service/api/documents/templates/proposal.rs
  catalyst-gateway/bin/src/service/utilities/json.rs
  catalyst-gateway/bin/src/service/utilities/mod.rs
Labels: enhancement, review me, rust

#1722 chore(cat-gateway): Remove legacy code
  catalyst-gateway/bin/src/service/api/legacy/mod.rs
  catalyst-gateway/bin/src/service/api/legacy/registration/mod.rs
  catalyst-gateway/bin/src/service/api/legacy/v0/message_post.rs
  catalyst-gateway/bin/src/service/api/legacy/v0/mod.rs
  catalyst-gateway/bin/src/service/api/legacy/v0/plans_get.rs
  catalyst-gateway/bin/src/service/api/legacy/v1/account_votes_get.rs
  catalyst-gateway/bin/src/service/api/legacy/v1/fragments_post.rs
  catalyst-gateway/bin/src/service/api/legacy/v1/fragments_statuses.rs
  catalyst-gateway/bin/src/service/api/legacy/v1/mod.rs
  catalyst-gateway/bin/src/service/api/mod.rs
  catalyst-gateway/bin/src/service/common/objects/legacy/account_votes.rs
  catalyst-gateway/bin/src/service/common/objects/legacy/block.rs
  catalyst-gateway/bin/src/service/common/objects/legacy/delegate_public_key.rs
  catalyst-gateway/bin/src/service/common/objects/legacy/event_id.rs
  catalyst-gateway/bin/src/service/common/objects/legacy/fragment_status.rs
  catalyst-gateway/bin/src/service/common/objects/legacy/fragments_batch.rs
  catalyst-gateway/bin/src/service/common/objects/legacy/fragments_processing_summary.rs
  catalyst-gateway/bin/src/service/common/objects/legacy/hash.rs
  catalyst-gateway/bin/src/service/common/objects/legacy/mod.rs
  catalyst-gateway/bin/src/service/common/objects/legacy/stake_public_key.rs
  catalyst-gateway/bin/src/service/common/objects/legacy/vote_plan.rs
  catalyst-gateway/bin/src/service/common/objects/legacy/voter_group_id.rs
  catalyst-gateway/bin/src/service/common/objects/legacy/voter_info.rs
  catalyst-gateway/bin/src/service/common/objects/legacy/voter_registration.rs
  catalyst-gateway/bin/src/service/common/objects/legacy/voting_public_key.rs
  catalyst-gateway/bin/src/service/common/objects/mod.rs
  catalyst-gateway/bin/src/service/common/tags.rs
Labels: do not merge yet, draft, rust

#1769 feat(cat-voices): UUID HiLo
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/catalyst_voices_models.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/hi_lo/hi_lo.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/hi_lo/uuid_hi_lo.dart
  catalyst_voices/packages/internal/catalyst_voices_models/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_models/test/hi_lo/uuid_hi_lo_test.dart
Labels: review me, dart

#1768 test(cat-voices): Update integration tests
  .config/dictionaries/project.dic
  catalyst_voices/apps/voices/integration_test/Earthfile
  catalyst_voices/apps/voices/integration_test/pageobject/onboarding_page.dart
  catalyst_voices/apps/voices/integration_test/pageobject/overall_spaces_page.dart
  catalyst_voices/apps/voices/integration_test/suites/account_test.dart
  catalyst_voices/apps/voices/integration_test/suites/app_test.dart
  catalyst_voices/apps/voices/integration_test/suites/onboarding_test.dart
  catalyst_voices/apps/voices/lib/pages/registration/create_base_profile/stage/instructions_panel.dart
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/wallet-automation/Earthfile
Labels: review me

#1728 feat(cat-voices): updated account page layout
  catalyst_voices/apps/voices/lib/app/view/app.dart
  catalyst_voices/apps/voices/lib/common/ext/account_role_ext.dart
  catalyst_voices/apps/voices/lib/common/ext/string_ext.dart
  catalyst_voices/apps/voices/lib/dependency/dependencies.dart
  catalyst_voices/apps/voices/lib/pages/account/account_page.dart
  catalyst_voices/apps/voices/lib/pages/account/account_page_header.dart
  catalyst_voices/apps/voices/lib/pages/account/delete_keychain_dialog.dart
  catalyst_voices/apps/voices/lib/pages/account/edit_roles_dialog.dart
  catalyst_voices/apps/voices/lib/pages/account/widgets/account_action_tile.dart
  catalyst_voices/apps/voices/lib/pages/account/widgets/account_display_name_tile.dart
  catalyst_voices/apps/voices/lib/pages/account/widgets/account_email_tile.dart
  catalyst_voices/apps/voices/lib/pages/account/widgets/account_header_tile.dart
  catalyst_voices/apps/voices/lib/pages/account/widgets/account_keychain_tile.dart
  catalyst_voices/apps/voices/lib/pages/account/widgets/account_page_title.dart
  catalyst_voices/apps/voices/lib/pages/account/widgets/account_roles_tile.dart
  catalyst_voices/apps/voices/lib/pages/account/widgets/account_status_banner.dart
  catalyst_voices/apps/voices/lib/pages/account/widgets/account_status_title_text.dart
  catalyst_voices/apps/voices/lib/pages/spaces/appbar/account_popup/session_account_avatar.dart
  catalyst_voices/apps/voices/lib/pages/spaces/appbar/account_popup/session_lock_button.dart
  catalyst_voices/apps/voices/lib/pages/spaces/appbar/account_popup/session_unlock_button.dart
  catalyst_voices/apps/voices/lib/pages/spaces/appbar/session_action_header.dart
  catalyst_voices/apps/voices/lib/widgets/app_bar/voices_app_bar.dart
  catalyst_voices/apps/voices/lib/widgets/avatars/voices_avatar.dart
  catalyst_voices/apps/voices/lib/widgets/buttons/voices_buttons.dart
  catalyst_voices/apps/voices/lib/widgets/buttons/voices_text_button.dart
  catalyst_voices/apps/voices/lib/widgets/common/navigation_back.dart
  catalyst_voices/apps/voices/lib/widgets/modals/voices_desktop_dialog.dart
  catalyst_voices/apps/voices/lib/widgets/modals/voices_info_dialog.dart
  catalyst_voices/apps/voices/lib/widgets/text/catalyst_id_text.dart
  catalyst_voices/apps/voices/lib/widgets/text_field/voices_display_name_text_field.dart
  catalyst_voices/apps/voices/lib/widgets/text_field/voices_email_text_field.dart
  catalyst_voices/apps/voices/lib/widgets/text_field/voices_text_field.dart
  catalyst_voices/apps/voices/lib/widgets/tiles/document_builder_section_tile.dart
  catalyst_voices/apps/voices/lib/widgets/tiles/editable_tile.dart
  catalyst_voices/apps/voices/lib/widgets/tiles/property_tile.dart
  catalyst_voices/apps/voices/lib/widgets/widgets.dart
  catalyst_voices/packages/internal/catalyst_voices_assets/assets/images/account_bg.png
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/account/account.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/account/account_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/account/account_state.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/catalyst_voices_blocs.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/registration/state_data/wallet_link_state_data.dart
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/user/account.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/user/account_role.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/account/my_account_role_item.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/account/my_account_status_notification.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/catalyst_voices_view_models.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/session/session_account.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/pubspec.yaml
  catalyst_voices/utilities/uikit_example/lib/examples/voices_modals_example.dart
Labels: review me, dart

#1734 chore(cat-gateway): Remove `#[allow(dead_code)]` where it is actually not dead code
  catalyst-gateway/bin/src/db/event/cardano.obsolete/chain_state/mod.rs
  catalyst-gateway/bin/src/db/event/cardano.obsolete/cip36_registration/mod.rs
  catalyst-gateway/bin/src/db/event/cardano.obsolete/config/mod.rs
  catalyst-gateway/bin/src/db/event/cardano.obsolete/utxo/mod.rs
  catalyst-gateway/bin/src/db/event/mod.rs
  catalyst-gateway/bin/src/db/event/signed_docs/full_signed_doc.rs
  catalyst-gateway/bin/src/db/index/block/txo/mod.rs
  catalyst-gateway/bin/src/db/index/queries/purge/mod.rs
  catalyst-gateway/bin/src/service/api/documents/get_document.rs
  catalyst-gateway/bin/src/service/api/documents/put_document/mod.rs
  catalyst-gateway/bin/src/service/common/auth/none.rs
  catalyst-gateway/bin/src/service/common/types/cardano/cip19_shelley_address.rs
Labels: review me, rust

#1731 feat(cat-voices): f14-Comments Schema for Catalyst Proposals
  docs/src/architecture/08_concepts/document_templates/F14-Comments/example.comment.json
  docs/src/architecture/08_concepts/document_templates/F14-Comments/f47ac10b-58cc-4372-a567-0e02b2c3d479.schema.json
Labels: review me, comment me, F14

#1560 docs(docs): Update auth token to use new catalyst id
  .config/dictionaries/project.dic
  docs/src/catalyst-standards/permissionless-auth/auth-header.md
  docs/src/catalyst-standards/permissionless-auth/auth-token.cddl
Labels: documentation, comment me, requires architecture review

#1778 chore(cat-gateway): Remove removable dead code
  catalyst-gateway/bin/src/cardano/cip36_registration_obsolete/cip36.cddl
  catalyst-gateway/bin/src/cardano/cip36_registration_obsolete/cip36_registration.cddl
  catalyst-gateway/bin/src/cardano/cip36_registration_obsolete/cip36_witness.cddl
  catalyst-gateway/bin/src/cardano/cip36_registration_obsolete/mod.rs.obsolete
  catalyst-gateway/bin/src/cardano/mod.rs
  catalyst-gateway/bin/src/db/index/queries/mod.rs
  catalyst-gateway/bin/src/db/index/schema/mod.rs
  catalyst-gateway/bin/src/service/api/cardano/mod.rs
  catalyst-gateway/bin/src/service/api/cardano/registration_get.rs
  catalyst-gateway/bin/src/service/api/cardano/sync_state_get.rs
  catalyst-gateway/bin/src/service/api/cardano/types.rs
  catalyst-gateway/bin/src/service/common/types/cardano/nonce.rs
  catalyst-gateway/bin/src/service/common/types/cardano/txn_index.rs
  catalyst-gateway/bin/src/utils/blake2b_hash.rs
Labels: review me, rust

#1776 chore(cat-gateway): Remove EventDB `legacy` and `obsolete` parts
  catalyst-gateway/bin/Cargo.toml
  catalyst-gateway/bin/src/db/event/cardano.obsolete/chain_state/insert_update_state.sql
  catalyst-gateway/bin/src/db/event/cardano.obsolete/chain_state/mod.rs
  catalyst-gateway/bin/src/db/event/cardano.obsolete/chain_state/select_slot_info_by_datetime.sql.hbs
  catalyst-gateway/bin/src/db/event/cardano.obsolete/chain_state/select_update_state.sql
  catalyst-gateway/bin/src/db/event/cardano.obsolete/cip36_registration/mod.rs
  catalyst-gateway/bin/src/db/event/cardano.obsolete/cip36_registration/select_cip36_registration.sql
  catalyst-gateway/bin/src/db/event/cardano.obsolete/config/mod.rs
  catalyst-gateway/bin/src/db/event/cardano.obsolete/config/select_config.sql
  catalyst-gateway/bin/src/db/event/cardano.obsolete/mod.rs.obsolete
  catalyst-gateway/bin/src/db/event/cardano.obsolete/utxo/mod.rs
  catalyst-gateway/bin/src/db/event/cardano.obsolete/utxo/select_total_utxo_amount.sql
  catalyst-gateway/bin/src/db/event/legacy/mod.rs
  catalyst-gateway/bin/src/db/event/legacy/queries/event/ballot.rs
  catalyst-gateway/bin/src/db/event/legacy/queries/event/mod.rs
  catalyst-gateway/bin/src/db/event/legacy/queries/event/objective.rs
  catalyst-gateway/bin/src/db/event/legacy/queries/event/proposal.rs
  catalyst-gateway/bin/src/db/event/legacy/queries/event/review.rs
  catalyst-gateway/bin/src/db/event/legacy/queries/mod.rs
  catalyst-gateway/bin/src/db/event/legacy/queries/registration.rs
  catalyst-gateway/bin/src/db/event/legacy/queries/search.rs
  catalyst-gateway/bin/src/db/event/legacy/queries/vit_ss/fund.rs
  catalyst-gateway/bin/src/db/event/legacy/queries/vit_ss/mod.rs
  catalyst-gateway/bin/src/db/event/legacy/types/ballot.rs
  catalyst-gateway/bin/src/db/event/legacy/types/event.rs
  catalyst-gateway/bin/src/db/event/legacy/types/mod.rs
  catalyst-gateway/bin/src/db/event/legacy/types/objective.rs
  catalyst-gateway/bin/src/db/event/legacy/types/proposal.rs
  catalyst-gateway/bin/src/db/event/legacy/types/registration.rs
  catalyst-gateway/bin/src/db/event/legacy/types/review.rs
  catalyst-gateway/bin/src/db/event/legacy/types/search.rs
  catalyst-gateway/bin/src/db/event/legacy/types/vit_ss/challenge.rs
  catalyst-gateway/bin/src/db/event/legacy/types/vit_ss/fund.rs
  catalyst-gateway/bin/src/db/event/legacy/types/vit_ss/goal.rs
  catalyst-gateway/bin/src/db/event/legacy/types/vit_ss/group.rs
  catalyst-gateway/bin/src/db/event/legacy/types/vit_ss/mod.rs
  catalyst-gateway/bin/src/db/event/legacy/types/vit_ss/vote_plan.rs
  catalyst-gateway/bin/src/db/event/legacy/types/voting_status.rs
  catalyst-gateway/bin/src/db/event/mod.rs
Labels: review me, rust

#1781 chore(flutter): publish packages
  catalyst_voices/CHANGELOG.md
  catalyst_voices/apps/voices/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_blocs/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_models/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_repositories/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_services/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_shared/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_view_models/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/CHANGELOG.md
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/example/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano_platform_interface/CHANGELOG.md
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano_platform_interface/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano_web/CHANGELOG.md
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano_web/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cardano_serialization/CHANGELOG.md
  catalyst_voices/packages/libs/catalyst_cardano_serialization/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_key_derivation/CHANGELOG.md
  catalyst_voices/packages/libs/catalyst_key_derivation/pubspec.yaml
  catalyst_voices/utilities/uikit_example/pubspec.yaml
Labels: review me, dart

#1782 feat(cat-gateway): Bump `catalyst-signed-doc`
  catalyst-gateway/bin/Cargo.toml
  catalyst-gateway/bin/src/service/api/documents/put_document/mod.rs
  catalyst-gateway/bin/src/service/api/documents/templates/mod.rs
  catalyst-gateway/bin/src/service/api/documents/templates/proposal.rs
Labels: review me

#1788 fix(cat-gateway): Fix `document` PUT endpoint
  catalyst-gateway/bin/src/db/event/signed_docs/full_signed_doc.rs
  catalyst-gateway/bin/src/db/event/signed_docs/mod.rs
  catalyst-gateway/bin/src/db/event/signed_docs/signed_doc_body.rs
  catalyst-gateway/bin/src/service/api/documents/put_document/mod.rs
  catalyst-gateway/tests/api_tests/api_tests/signed_document.hurl
Labels: review me

#1790 chore(flutter): publish packages
  catalyst_voices/CHANGELOG.md
  catalyst_voices/apps/voices/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_assets/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_blocs/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_brands/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_localization/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_models/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_repositories/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_services/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_shared/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_view_models/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_analysis/CHANGELOG.md
  catalyst_voices/packages/libs/catalyst_analysis/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/CHANGELOG.md
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/example/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano_platform_interface/CHANGELOG.md
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano_platform_interface/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano_web/CHANGELOG.md
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano_web/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cardano_serialization/CHANGELOG.md
  catalyst_voices/packages/libs/catalyst_cardano_serialization/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_compression/catalyst_compression/CHANGELOG.md
  catalyst_voices/packages/libs/catalyst_compression/catalyst_compression/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_compression/catalyst_compression_platform_interface/CHANGELOG.md
  catalyst_voices/packages/libs/catalyst_compression/catalyst_compression_platform_interface/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_compression/catalyst_compression_web/CHANGELOG.md
  catalyst_voices/packages/libs/catalyst_compression/catalyst_compression_web/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cose/CHANGELOG.md
  catalyst_voices/packages/libs/catalyst_cose/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_key_derivation/CHANGELOG.md
  catalyst_voices/packages/libs/catalyst_key_derivation/example/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_key_derivation/pubspec.yaml
  catalyst_voices/utilities/poc_local_storage/pubspec.yaml
  catalyst_voices/utilities/remote_widgets/example/pubspec.yaml
  catalyst_voices/utilities/remote_widgets/pubspec.yaml
  catalyst_voices/utilities/uikit_example/pubspec.yaml
Labels: review me, dart

#1538 fix(cat-gateway): Fix health endpoints response schema and status code
  catalyst-gateway/bin/src/service/api/cardano/cip36/mod.rs
  catalyst-gateway/bin/src/service/api/cardano/cip36/response.rs
  catalyst-gateway/bin/src/service/api/cardano/date_time_to_slot_number_get.rs
  catalyst-gateway/bin/src/service/api/cardano/rbac/chain_root_get.rs
  catalyst-gateway/bin/src/service/api/cardano/rbac/registrations_get.rs
  catalyst-gateway/bin/src/service/api/cardano/rbac/role0_chain_root_get.rs
  catalyst-gateway/bin/src/service/api/cardano/staking/assets_get.rs
  catalyst-gateway/bin/src/service/api/config/mod.rs
  catalyst-gateway/bin/src/service/api/documents/mod.rs
  catalyst-gateway/bin/src/service/api/documents/put_document/mod.rs
  catalyst-gateway/bin/src/service/api/documents/put_document/unprocessable_content_request.rs
  catalyst-gateway/bin/src/service/api/health/inspection_get.rs
  catalyst-gateway/bin/src/service/api/health/live_get.rs
  catalyst-gateway/bin/src/service/api/health/ready_get.rs
  catalyst-gateway/bin/src/service/api/health/started_get.rs
  catalyst-gateway/bin/src/service/common/auth/api_key.rs
  catalyst-gateway/bin/src/service/common/auth/none.rs
  catalyst-gateway/bin/src/service/common/auth/rbac/scheme.rs
  catalyst-gateway/bin/src/service/common/objects/config/mod.rs
  catalyst-gateway/bin/src/service/common/responses/code_412_precondition_failed.rs
  catalyst-gateway/bin/src/service/common/responses/mod.rs
  catalyst-gateway/bin/src/service/poem_service.rs
  catalyst-gateway/tests/schemathesis_tests/Earthfile
  catalyst-gateway/tests/schemathesis_tests/hooks/hooks.py
Labels: review me

#1784 fix(cat-gateway): Sign doc GET static template
  catalyst-gateway/bin/Cargo.toml
  catalyst-gateway/bin/src/service/api/documents/get_document.rs
  catalyst-gateway/bin/src/service/api/documents/templates/data.rs
  catalyst-gateway/bin/src/service/api/documents/templates/docs/category/f14_category_10_template.schema.json
  catalyst-gateway/bin/src/service/api/documents/templates/docs/category/f14_category_11_template.schema.json
  catalyst-gateway/bin/src/service/api/documents/templates/docs/category/f14_category_12_template.schema.json
  catalyst-gateway/bin/src/service/api/documents/templates/docs/category/f14_category_1_template.schema.json
  catalyst-gateway/bin/src/service/api/documents/templates/docs/category/f14_category_2_template.schema.json
  catalyst-gateway/bin/src/service/api/documents/templates/docs/category/f14_category_3_template.schema.json
  catalyst-gateway/bin/src/service/api/documents/templates/docs/category/f14_category_4_template.schema.json
  catalyst-gateway/bin/src/service/api/documents/templates/docs/category/f14_category_5_template.schema.json
  catalyst-gateway/bin/src/service/api/documents/templates/docs/category/f14_category_6_template.schema.json
  catalyst-gateway/bin/src/service/api/documents/templates/docs/category/f14_category_7_template.schema.json
  catalyst-gateway/bin/src/service/api/documents/templates/docs/category/f14_category_8_template.schema.json
  catalyst-gateway/bin/src/service/api/documents/templates/docs/category/f14_category_9_template.schema.json
  catalyst-gateway/bin/src/service/api/documents/templates/docs/f14_comment_template.schema.json
  catalyst-gateway/bin/src/service/api/documents/templates/docs/f14_proposal_template.schema.json
  catalyst-gateway/bin/src/service/api/documents/templates/mod.rs
  catalyst-gateway/bin/src/service/api/documents/templates/proposal.rs
  docs/src/architecture/08_concepts/document_templates/F14-Comments/0b8424d4-ebfd-46e3-9577-1775a69d290c.schema.json
Labels: enhancement, do not merge yet, review me, F14

#1799 fix(cat-gateway): nightly schemathesis
  catalyst-gateway/tests/schemathesis_tests/Earthfile
Labels: review me

#1746 feat(cat-voices): Category Detail Page
  catalyst_voices/apps/voices/lib/app/view/app.dart
  catalyst_voices/apps/voices/lib/dependency/dependencies.dart
  catalyst_voices/apps/voices/lib/pages/category/category_detail_view.dart
  catalyst_voices/apps/voices/lib/pages/category/category_page.dart
  catalyst_voices/apps/voices/lib/pages/category/change_category_button.dart
  catalyst_voices/apps/voices/lib/pages/discovery/sections/campaign_categories.dart
  catalyst_voices/apps/voices/lib/pages/discovery/sections/current_campaign.dart
  catalyst_voices/apps/voices/lib/pages/discovery/state_selectors/campaign_categories_state_selector.dart
  catalyst_voices/apps/voices/lib/routes/routing/spaces_route.dart
  catalyst_voices/apps/voices/lib/widgets/cards/campaign_category_card.dart
  catalyst_voices/apps/voices/lib/widgets/cards/category_proposals_details_card.dart
  catalyst_voices/apps/voices/lib/widgets/cards/create_proposal_card.dart
  catalyst_voices/apps/voices/lib/widgets/cards/funds_detail_card.dart
  catalyst_voices/apps/voices/lib/widgets/cards/voices_leading_icon_card.dart
  catalyst_voices/apps/voices/lib/widgets/common/navigation_back.dart
  catalyst_voices/apps/voices/lib/widgets/text/day_at_time_text.dart
  catalyst_voices/apps/voices/lib/widgets/text/timezone_date_time_text.dart
  catalyst_voices/apps/voices/lib/widgets/tiles/voices_expansion_tile.dart
  catalyst_voices/apps/voices/macos/Flutter/GeneratedPluginRegistrant.swift
  catalyst_voices/apps/voices/test/widgets/cards/funds_detail_card_test.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/catalyst_voices_blocs.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/category/category_detail.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/category/category_detail_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/category/category_detail_state.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/discovery/discovery_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/discovery/discovery_state.dart
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/campaign/campaign_category.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/catalyst_voices_view_models.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/category/category_change_view_model.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/category/category_description_view_model.dart
  catalyst_voices/utilities/poc_local_storage/macos/Flutter/GeneratedPluginRegistrant.swift
Labels: do not merge yet, review me, ux/ui, F14

#1804 chore(cat-voices): move static analysis to build stage
  catalyst_voices/Earthfile
  catalyst_voices/justfile
Labels: review me

#1813 fix(cat-voices): tests reports progress progress
  catalyst_voices/.gitignore
  catalyst_voices/melos.yaml
Labels: enhancement, review me

#1815 chore: bump ci ver
  Earthfile
  catalyst-gateway/Earthfile
  catalyst-gateway/event-db/Earthfile
  catalyst-gateway/tests/Earthfile
  catalyst-gateway/tests/api_tests/Earthfile
  catalyst_voices/Earthfile
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/wallet-automation/Earthfile
  catalyst_voices/packages/libs/catalyst_key_derivation/Earthfile
  catalyst_voices/packages/libs/catalyst_key_derivation/rust/Earthfile
  catalyst_voices/utilities/uikit_example/Earthfile
  docs/Earthfile
  utilities/docs-preview/Earthfile
Labels: enhancement, review me

#1792 test(cat-voices): make playwright use ci browsers
  catalyst_voices/apps/voices/integration_test/Earthfile
  catalyst_voices/apps/voices/integration_test/pageobject/onboarding_page.dart
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/wallet-automation/playwright.config.ts
Labels: review me

#1811 feat(cat-voices): Debounce text editing
  .config/dictionaries/project.dic
  catalyst_voices/apps/voices/lib/widgets/document_builder/multiline_text_entry_markdown_widget.dart
  catalyst_voices/apps/voices/lib/widgets/document_builder/simple_text_entry_widget.dart
  catalyst_voices/apps/voices/lib/widgets/rich_text/voices_rich_text.dart
  catalyst_voices/apps/voices/test/widgets/rich_text/voices_rich_text_test.dart
  catalyst_voices/melos.yaml
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/catalyst_voices_shared.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/utils/debouncer.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_shared/test/src/utils/debouncer_test.dart
  catalyst_voices/utilities/uikit_example/lib/examples/voices_rich_text_example.dart
Labels: review me, ux/ui, dart, F14

#1798 test(cat-gateway): Signed doc test
  catalyst-gateway/docker-compose.yml
  catalyst-gateway/tests/api_tests/Earthfile
  catalyst-gateway/tests/api_tests/api_tests/__init__.py
  catalyst-gateway/tests/api_tests/api_tests/signed_document.hurl
  catalyst-gateway/tests/api_tests/api_tests/test_signed_doc.py
  catalyst-gateway/tests/api_tests/docker-compose.yml
Labels: review me, python, F14

#1825 feat(cat-gateway): Remove unneeded patch of `orx-pseudo-default`
  catalyst-gateway/Cargo.toml
Labels: do not merge yet

#1823 feat(cat-voices): automatic markdown recognition for rich text
  catalyst_voices/apps/voices/lib/widgets/document_builder/multiline_text_entry_markdown_widget.dart
  catalyst_voices/apps/voices/lib/widgets/rich_text/voices_rich_text.dart
Labels: review me, ux/ui, dart, F14

#1794 fix(cat-gateway): Schemathesis `/cardano/registration/cip36` fix
  catalyst-gateway/bin/src/service/api/cardano/cip36/filter.rs
  catalyst-gateway/bin/src/service/api/cardano/cip36/response.rs
  catalyst-gateway/bin/src/service/api/cardano/mod.rs
  catalyst-gateway/bin/src/service/api/cardano/staking/mod.rs
  catalyst-gateway/bin/src/service/common/types/cardano/cip19_shelley_address.rs
  catalyst-gateway/tests/Earthfile
  catalyst-gateway/tests/api_tests/Earthfile
  catalyst-gateway/tests/api_tests/docker-compose.yml
  catalyst-gateway/tests/blueprint.cue
  catalyst-gateway/tests/docker-compose.yml
  catalyst-gateway/tests/docker/docker-compose.postgres.yml
  catalyst-gateway/tests/node1-scylla.yaml
  catalyst-gateway/tests/schemathesis_tests/Earthfile
  catalyst-gateway/tests/schemathesis_tests/hooks/hooks.py
  catalyst-gateway/tests/schemathesis_tests/schemathesis-docker-compose.yml
Labels: review me

#1816 fix(cat-gateway): Pagination bigint out of range
  catalyst-gateway/bin/src/db/event/common/query_limits.rs
  catalyst-gateway/bin/src/service/api/documents/post_document_index_query/mod.rs
  catalyst-gateway/bin/src/service/common/objects/generic/pagination.rs
  catalyst-gateway/bin/src/service/common/types/generic/query/pagination.rs
  catalyst-gateway/tests/api_tests/api_tests/signed_document.hurl
  catalyst-gateway/tests/api_tests/api_tests/test_signed_doc.py
Labels: bug, review me, rust

#1835 fix(cat-gateway): Race condition in PUT signed doc
  catalyst-gateway/bin/src/db/event/signed_docs/full_signed_doc.rs
Labels: bug

#1791 feat(cat-voices): Proposal page pagination
  catalyst_voices/apps/voices/lib/dependency/dependencies.dart
  catalyst_voices/apps/voices/lib/pages/proposals/proposals_page.dart
  catalyst_voices/apps/voices/lib/pages/proposals/proposals_pagination.dart
  catalyst_voices/apps/voices/lib/pages/voting/voting_page.dart
  catalyst_voices/apps/voices/lib/widgets/cards/proposal_card.dart
  catalyst_voices/apps/voices/lib/widgets/pagination/builders/paged_wrap_child_builder.dart
  catalyst_voices/apps/voices/lib/widgets/pagination/layouts/paginated_grid_view.dart.dart
  catalyst_voices/apps/voices/lib/widgets/pagination/listenable_listener.dart
  catalyst_voices/apps/voices/lib/widgets/pagination/paging_controller.dart
  catalyst_voices/apps/voices/lib/widgets/pagination/paging_state.dart
  catalyst_voices/apps/voices/lib/widgets/pagination/paging_status.dart
  catalyst_voices/apps/voices/test/widgets/paging/paging_controller_test.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposals/proposals_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposals/proposals_state.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/test/proposals/proposals_cubit_test.dart
  catalyst_voices/packages/internal/catalyst_voices_brands/lib/src/themes/catalyst.dart
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/catalyst_voices_models.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/pagination/pagination_page.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/proposal/proposal_pagination_items.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/proposal/proposal_pagination_request.dart
  catalyst_voices/packages/internal/catalyst_voices_models/test/proposal/proposal_pagination_items_test.dart
  catalyst_voices/packages/internal/catalyst_voices_models/test/proposal/proposal_pagination_request_test.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/proposal/proposal_repository.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/proposal/proposal_service.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/proposal/proposal_view_model.dart
Labels: review me, ux/ui

#1832 test(cat-gateway): adds env vars for gateway and event db
  catalyst-gateway/tests/api_tests/Earthfile
  catalyst-gateway/tests/api_tests/api_tests/__init__.py
  catalyst-gateway/tests/api_tests/api_tests/test_schema_mismatch_behavior.py
  catalyst-gateway/tests/api_tests/api_tests/test_signed_doc.py
Labels: review me

#1830 feat(cat-gateway): Schemathesis for documents POST endpoint.
  catalyst-gateway/bin/src/service/api/documents/post_document_index_query/mod.rs
  catalyst-gateway/bin/src/service/api/documents/post_document_index_query/response.rs
  catalyst-gateway/tests/Earthfile
  catalyst-gateway/tests/api_tests/Earthfile
  catalyst-gateway/tests/docker-compose.yml
  catalyst-gateway/tests/schemathesis_tests/Earthfile
  catalyst-gateway/tests/scylla.yaml
  catalyst-gateway/tests/scylla_entry.sh
Labels: review me

#1831 feat(cat-voices): consecutive enters when editing bullet list should exit it in rich text
  catalyst_voices/apps/voices/lib/widgets/document_builder/multiline_text_entry_markdown_widget.dart
  catalyst_voices/apps/voices/lib/widgets/document_builder/simple_text_entry_widget.dart
  catalyst_voices/apps/voices/lib/widgets/rich_text/voices_rich_text.dart
  catalyst_voices/apps/voices/lib/widgets/rich_text/voices_rich_text_limit.dart
  catalyst_voices/apps/voices/lib/widgets/rich_text/voices_rich_text_rules.dart
  catalyst_voices/apps/voices/test/widgets/rich_text/voices_rich_text_rules_test.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/proposal_builder/proposal_builder_segments.dart
Labels: bug, review me, ux/ui, dart, F14

#1843 feat(cat-gateway): Catalyst Signed Document endpoints v1
  catalyst-gateway/bin/src/service/api/documents/mod.rs
  catalyst-gateway/tests/api_tests/api_tests/test_signed_doc.py
  catalyst-gateway/tests/schemathesis_tests/Earthfile
Labels: review me

#1846 feat(general): Disable running CI for draft PRs
  .github/workflows/ci.yml
Labels: review me

#1844 chore(cat-voices): upgrade flutter to 3.29.0
  .github/workflows/flutter-publish-packages.yml
  Earthfile
  catalyst-gateway/Earthfile
  catalyst-gateway/event-db/Earthfile
  catalyst-gateway/tests/Earthfile
  catalyst-gateway/tests/api_tests/Earthfile
  catalyst_voices/Earthfile
  catalyst_voices/README.md
  catalyst_voices/apps/voices/integration_test/Earthfile
  catalyst_voices/apps/voices/macos/Flutter/GeneratedPluginRegistrant.swift
  catalyst_voices/apps/voices/pubspec.yaml
  catalyst_voices/apps/voices/web/enable-threads.js
  catalyst_voices/apps/voices/web/index.html
  catalyst_voices/melos.yaml
  catalyst_voices/packages/internal/catalyst_voices_assets/example/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_assets/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_blocs/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_brands/lib/src/themes/catalyst.dart
  catalyst_voices/packages/internal/catalyst_voices_brands/lib/src/themes/widgets/voices_input_decoration_theme.dart
  catalyst_voices/packages/internal/catalyst_voices_brands/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_driver/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_localization/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/generated/api/client_index.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/generated/api/client_mapping.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_services/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_shared/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_view_models/pubspec.yaml
  catalyst_voices/packages/libs/README.md
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/README.md
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/example/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/wallet-automation/Earthfile
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/wallet-automation/nginx.conf
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano_platform_interface/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano_web/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cardano_serialization/README.md
  catalyst_voices/packages/libs/catalyst_cardano_serialization/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_compression/catalyst_compression/README.md
  catalyst_voices/packages/libs/catalyst_compression/catalyst_compression/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_compression/catalyst_compression_platform_interface/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_compression/catalyst_compression_web/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_key_derivation/Earthfile
  catalyst_voices/packages/libs/catalyst_key_derivation/README.md
  catalyst_voices/packages/libs/catalyst_key_derivation/example/web/enable-threads.js
  catalyst_voices/packages/libs/catalyst_key_derivation/example/web/index.html
  catalyst_voices/packages/libs/catalyst_key_derivation/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_key_derivation/rust/Earthfile
  catalyst_voices/utilities/poc_local_storage/macos/Flutter/GeneratedPluginRegistrant.swift
  catalyst_voices/utilities/poc_local_storage/pubspec.yaml
  catalyst_voices/utilities/remote_widgets/pubspec.yaml
  catalyst_voices/utilities/uikit_example/Earthfile
  catalyst_voices/utilities/uikit_example/pubspec.yaml
  docs/Earthfile
  utilities/docs-preview/Earthfile
Labels: review me, dart

#1842 test(cat-gateway): refactor api tests
  catalyst-gateway/tests/api_tests/Earthfile
  catalyst-gateway/tests/api_tests/api/__init__.py
  catalyst-gateway/tests/api_tests/api/draft/__init__.py
  catalyst-gateway/tests/api_tests/api/v1/__init__.py
  catalyst-gateway/tests/api_tests/api/v1/document.py
  catalyst-gateway/tests/api_tests/api/v1/health.py
  catalyst-gateway/tests/api_tests/api_tests/test_signed_doc.py
  catalyst-gateway/tests/api_tests/hurl/get_cardano_assets.hurl
  catalyst-gateway/tests/api_tests/hurl/signed_document.hurl
  catalyst-gateway/tests/api_tests/integration/__init__.py
  catalyst-gateway/tests/api_tests/integration/test_schema_mismatch_behavior.py
  catalyst-gateway/tests/api_tests/integration/test_signed_doc.py
  catalyst-gateway/tests/api_tests/integration/test_slot_info.py
  catalyst-gateway/tests/api_tests/integration/test_utils.py
  catalyst-gateway/tests/api_tests/integration/test_utxo.py
  catalyst-gateway/tests/api_tests/integration/test_voter_registration.py
  catalyst-gateway/tests/api_tests/poetry.lock
  catalyst-gateway/tests/api_tests/pyproject.toml
  catalyst-gateway/tests/api_tests/utils/__init__.py
  catalyst-gateway/tests/api_tests/utils/address.py
  catalyst-gateway/tests/api_tests/utils/health.py
  catalyst-gateway/tests/api_tests/utils/sync.py
Labels: review me

#1847 test(cat-gateway): fix docker compose path
  catalyst-gateway/tests/schemathesis_tests/Earthfile
Labels: review me

#1855 fix(cat-voices): Dart format in melos file after updating Dart 3.7
  catalyst_voices/melos.yaml
Labels: review me, dart

#1822 feat(cat-voices): Filter by Category for Proposal List
  catalyst_voices/apps/voices/lib/pages/category/change_category_button.dart
  catalyst_voices/apps/voices/lib/pages/proposals/proposals_page.dart
  catalyst_voices/apps/voices/lib/pages/proposals/proposals_pagination.dart
  catalyst_voices/apps/voices/lib/widgets/dropdown/category_dropdown.dart
  catalyst_voices/apps/voices/lib/widgets/pagination/layouts/paginated_grid_view.dart.dart
  catalyst_voices/apps/voices/lib/widgets/pagination/paging_controller.dart
  catalyst_voices/apps/voices/lib/widgets/pagination/paging_state.dart
  catalyst_voices/apps/voices/test/widgets/dropdown/category_dropdown_test.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposals/proposals_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposals/proposals_state.dart
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/campaign/campaign_service.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/catalyst_voices_view_models.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/category/category_change_view_model.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/category/dropdown_menu_view_model.dart
Labels: review me, ux/ui, F14

#1812 feat(cat-voices): update proposal index structure, proposal submission timeline
  catalyst_voices/apps/voices/lib/common/ext/space_ext.dart
  catalyst_voices/apps/voices/lib/common/typedefs.dart
  catalyst_voices/apps/voices/lib/pages/discovery/sections/current_campaign.dart
  catalyst_voices/apps/voices/lib/pages/discovery/state_selectors/campaign_categories_state_selector.dart
  catalyst_voices/apps/voices/lib/pages/discovery/state_selectors/current_campaign_selector.dart
  catalyst_voices/apps/voices/lib/pages/discovery/state_selectors/most_recent_proposals_selector.dart
  catalyst_voices/apps/voices/lib/pages/workspace/header/create_proposal_button.dart
  catalyst_voices/apps/voices/lib/pages/workspace/header/import_proposal_button.dart
  catalyst_voices/apps/voices/lib/pages/workspace/header/timeline_toggle_button.dart
  catalyst_voices/apps/voices/lib/pages/workspace/header/workspace_header.dart
  catalyst_voices/apps/voices/lib/pages/workspace/my_proposals/my_proposal_list_item.dart
  catalyst_voices/apps/voices/lib/pages/workspace/my_proposals/my_proposals_list.dart
  catalyst_voices/apps/voices/lib/pages/workspace/my_proposals/my_proposals_list_selector.dart
  catalyst_voices/apps/voices/lib/pages/workspace/my_proposals/my_proposals_tab_selector.dart
  catalyst_voices/apps/voices/lib/pages/workspace/my_proposals/my_proposals_tabs.dart
  catalyst_voices/apps/voices/lib/pages/workspace/my_proposals/workspace_my_proposals_selector.dart
  catalyst_voices/apps/voices/lib/pages/workspace/page/workspace_empty.dart
  catalyst_voices/apps/voices/lib/pages/workspace/page/workspace_error.dart
  catalyst_voices/apps/voices/lib/pages/workspace/page/workspace_loading.dart
  catalyst_voices/apps/voices/lib/pages/workspace/page/workspace_page.dart
  catalyst_voices/apps/voices/lib/pages/workspace/workspace.dart
  catalyst_voices/apps/voices/lib/pages/workspace/workspace_header.dart
  catalyst_voices/apps/voices/lib/pages/workspace/workspace_proposals.dart
  catalyst_voices/apps/voices/lib/widgets/campaign_timeline/campaign_timeline.dart
  catalyst_voices/apps/voices/lib/widgets/campaign_timeline/campaign_timeline_card.dart
  catalyst_voices/apps/voices/lib/widgets/search/search_text_field.dart
  catalyst_voices/apps/voices/lib/widgets/text_field/voices_text_field.dart
  catalyst_voices/apps/voices/lib/widgets/widgets.dart
  catalyst_voices/apps/voices/macos/Podfile.lock
  catalyst_voices/apps/voices/macos/Runner.xcodeproj/project.pbxproj
  catalyst_voices/apps/voices/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  catalyst_voices/apps/voices/macos/Runner/AppDelegate.swift
  catalyst_voices/apps/voices/macos/Runner/Configs/AppInfo.xcconfig
  catalyst_voices/apps/voices/macos/Runner/DebugProfile.entitlements
  catalyst_voices/apps/voices/macos/Runner/Release.entitlements
  catalyst_voices/apps/voices/test/widgets/campaign_timeline/campaign_timeline_card_test.dart
  catalyst_voices/apps/voices/test/widgets/campaign_timeline/campaign_timeline_test.dart
  catalyst_voices/apps/voices/test/widgets/search/search_text_field_test.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/workspace/workspace_state.dart
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/campaign/campaign_timeline.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/campaign/campaign_timeline_view_model.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/catalyst_voices_view_models.dart
Labels: review me, dart, F14

#1850 feat(cat-voices): convert object and list builders to be form fields
  catalyst_voices/apps/voices/lib/widgets/tiles/document_builder_section_tile.dart
Labels: review me, ux/ui, dart, F14

#1820 feat(cat-voices): integrate db with documents repository and service part1
  .config/dictionaries/project.dic
  catalyst_voices/apps/voices/lib/dependency/dependencies.dart
  catalyst_voices/melos.yaml
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/proposal_builder_bloc.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/campaign/campaign_base.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/catalyst_voices_models.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/data/document_data.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/data/document_data_content.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/data/document_data_metadata.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/data/document_type.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/document_ref.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/signed_document_ref.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/hi_lo/uuid_hi_lo.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/proposal/proposal_base.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/catalyst_voices_repositories.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/database/catalyst_database.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/database/dao/documents_dao.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/database/dao/drafts_dao.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/database/database.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/database/table/converter/document_converters.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/database/table/documents.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/database/table/drafts.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/database/table/mixin/document_table_mixin.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/document/document_repository.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/document/exception/document_data_local_source_exception.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/document/source/database_documents_data_source.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/document/source/database_drafts_data_source.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/document/source/document_data_local_source.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/document/source/document_data_remote_source.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/document/source/document_data_source.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/document_data_dto.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/document_dto.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/document_ref_dto.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/signed_document_data_dto.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/database/catalyst_database_test.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/database/dao/documents_dao_test.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/database/dao/drafts_dao_test.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/document/document_data_dto_test.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/document/document_dto_test.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/document/document_repository_test.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/utils/test_factories.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/proposal/proposal_service.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/utils/typedefs.dart
Labels: review me, dart

#1841 feat(cat-voices): DocumentsRepo db integration part2
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/proposal_builder_bloc.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/campaign/campaign_base.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/data/document_data.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/data/document_data_metadata.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/document_ref.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/proposal/proposal_base.dart
  catalyst_voices/packages/internal/catalyst_voices_models/test/document/data/document_data_metadata_test.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/document/document_repository.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/document/source/document_data_local_source.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/document/source/document_data_remote_source.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/document_data_dto.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/document_ref_dto.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/database/dao/documents_dao_test.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/database/dao/drafts_dao_test.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/document/document_repository_test.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/dto/document/document_data_dto_test.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/utils/test_factories.dart
Labels: review me, dart

#1861 fix(cat-voices): database injection
  catalyst_voices/apps/voices/lib/dependency/dependencies.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/app_config.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/hi_lo/uuid_hi_lo.dart
Labels: bug, review me, dart

#1859 feat(cat-voices): proposal actions and error indicators in proposal editor
  catalyst_voices/apps/voices/lib/pages/proposal_builder/proposal_builder_segments.dart
  catalyst_voices/apps/voices/lib/pages/spaces/appbar/proposal_builder_status_action.dart
  catalyst_voices/apps/voices/lib/pages/spaces/spaces_shell_page.dart
  catalyst_voices/apps/voices/lib/widgets/common/simple_tree_view.dart
  catalyst_voices/apps/voices/lib/widgets/document_builder/agreement_confirmation_widget.dart
  catalyst_voices/apps/voices/lib/widgets/document_builder/document_error_text.dart
  catalyst_voices/apps/voices/lib/widgets/document_builder/yes_no_choice_widget.dart
  catalyst_voices/apps/voices/lib/widgets/dropdown/voices_dropdown.dart
  catalyst_voices/apps/voices/lib/widgets/menu/voices_node_menu.dart
  catalyst_voices/apps/voices/lib/widgets/rich_text/voices_rich_text.dart
  catalyst_voices/apps/voices/lib/widgets/rich_text/voices_rich_text_limit.dart
  catalyst_voices/apps/voices/lib/widgets/segments/segments_menu.dart
  catalyst_voices/apps/voices/lib/widgets/text_field/voices_text_field.dart
  catalyst_voices/apps/voices/lib/widgets/tiles/document_builder_section_tile.dart
  catalyst_voices/apps/voices/lib/widgets/tiles/editable_tile.dart
  catalyst_voices/apps/voices/lib/widgets/tiles/property_tile.dart
  catalyst_voices/apps/voices/lib/widgets/toggles/voices_radio_button_form_field.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/proposal_builder_bloc.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/proposal_builder_event.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/proposal_builder_state.dart
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/document.dart
  catalyst_voices/packages/internal/catalyst_voices_models/test/document/document_test.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/proposal_builder/proposal_builder_segments.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/segments/segments_navigation.dart
Labels: review me, ux/ui, dart, F14

#1865 feat(cat-voices): proposal editor validation snackbar
  catalyst_voices/apps/voices/lib/pages/proposal_builder/proposal_builder_page.dart
  catalyst_voices/apps/voices/lib/widgets/buttons/voices_buttons.dart
  catalyst_voices/apps/voices/lib/widgets/rich_text/voices_rich_text.dart
  catalyst_voices/apps/voices/lib/widgets/snackbar/voices_snackbar.dart
  catalyst_voices/apps/voices/lib/widgets/snackbar/voices_snackbar_action.dart
  catalyst_voices/apps/voices/lib/widgets/snackbar/voices_snackbar_type.dart
  catalyst_voices/apps/voices/lib/widgets/text_field/voices_text_field.dart
  catalyst_voices/apps/voices/lib/widgets/tiles/editable_tile.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/proposal_builder_bloc.dart
  catalyst_voices/packages/internal/catalyst_voices_brands/lib/src/utils/typedefs.dart
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/document.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/utils/debouncer.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/catalyst_voices_view_models.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/proposal_builder/exception/proposal_builder_exception.dart
  catalyst_voices/utilities/uikit_example/lib/examples/voices_snackbar_example.dart
Labels: review me, ux/ui, dart, F14

#1874 fix(cat-voices): Final keyword in _border and padding in campaign timeline
  catalyst_voices/apps/voices/lib/pages/discovery/sections/campaign_hero.dart
  catalyst_voices/apps/voices/lib/pages/discovery/sections/current_campaign.dart
  catalyst_voices/apps/voices/lib/widgets/campaign_timeline/campaign_timeline.dart
  catalyst_voices/apps/voices/lib/widgets/cards/pending_proposal_card.dart
Labels: ux/ui, F14

#1868 feat(cat-voices): Proposal builder publish new iteration dialog
  catalyst_voices/apps/voices/lib/pages/proposal_builder/proposal_publish_iteration_dialog.dart
  catalyst_voices/apps/voices/lib/pages/spaces/appbar/proposal_builder_status_action.dart
  catalyst_voices/apps/voices/lib/widgets/painter/arrow_right_painter.dart
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
Labels: review me, ux/ui, dart, F14

#1875 feat(cat-voices): submit proposal for review dialog
  catalyst_voices/apps/voices/lib/pages/account/delete_keychain_dialog.dart
  catalyst_voices/apps/voices/lib/pages/account/edit_roles_dialog.dart
  catalyst_voices/apps/voices/lib/pages/account/keychain_deleted_dialog.dart
  catalyst_voices/apps/voices/lib/pages/campaign/details/widgets/campaign_management_dialog.dart
  catalyst_voices/apps/voices/lib/pages/proposal_builder/dialog/proposal_builder_dialog_widgets.dart
  catalyst_voices/apps/voices/lib/pages/proposal_builder/dialog/publish_proposal_iteration_dialog.dart
  catalyst_voices/apps/voices/lib/pages/proposal_builder/dialog/submit_proposal_for_review_dialog.dart
  catalyst_voices/apps/voices/lib/pages/proposal_builder/proposal_builder_page.dart
  catalyst_voices/apps/voices/lib/pages/registration/incorrect_seed_phrase_dialog.dart
  catalyst_voices/apps/voices/lib/pages/registration/registration_dialog.dart
  catalyst_voices/apps/voices/lib/pages/registration/upload_seed_phrase_confirmation_dialog.dart
  catalyst_voices/apps/voices/lib/pages/registration/wallet_link/account_role_dialog.dart
  catalyst_voices/apps/voices/lib/pages/registration/widgets/export_catalyst_key_confirm_dialog.dart
  catalyst_voices/apps/voices/lib/pages/spaces/appbar/proposal_builder_status_action.dart
  catalyst_voices/apps/voices/lib/widgets/modals/voices_dialog.dart
  catalyst_voices/apps/voices/lib/widgets/modals/voices_question_dialog.dart
  catalyst_voices/apps/voices/lib/widgets/modals/voices_upload_file_dialog.dart
  catalyst_voices/apps/voices/lib/widgets/painter/arrow_right_painter.dart
  catalyst_voices/apps/voices/lib/widgets/text_field/voices_text_field.dart
  catalyst_voices/apps/voices/lib/widgets/tiles/document_builder_section_tile.dart
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
  catalyst_voices/utilities/uikit_example/lib/examples/voices_modals_example.dart
Labels: review me, ux/ui, dart, F14

#1895 feat(cat-gateway): Schemathesis local run guide
  catalyst-gateway/bin/Cargo.toml
  catalyst-gateway/tests/docker-compose.yml
  catalyst-gateway/tests/schemathesis_tests/Earthfile
  catalyst-gateway/tests/schemathesis_tests/README.md
Labels: review me

#1900 feat(cat-voices): Updating UI for deleting keychain dialog
  catalyst_voices/apps/voices/lib/pages/account/delete_keychain_dialog.dart
  catalyst_voices/apps/voices/lib/pages/account/keychain_deleted_dialog.dart
  catalyst_voices/apps/voices/lib/pages/account/widgets/account_keychain_tile.dart
  catalyst_voices/apps/voices/lib/pages/account/widgets/account_page_title.dart
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
Labels: review me, ux/ui, F14

#1787 feat(cat-gateway): Add OpenAPI Examples and enforce error
  catalyst-gateway/bin/Cargo.toml
  catalyst-gateway/bin/src/db/index/tests/scylla_queries.rs
  catalyst-gateway/bin/src/service/api/cardano/cip36/filter.rs
  catalyst-gateway/bin/src/service/api/cardano/cip36/response.rs
  catalyst-gateway/bin/src/service/api/cardano/mod.rs
  catalyst-gateway/bin/src/service/api/cardano/rbac/chain_root_get.rs
  catalyst-gateway/bin/src/service/api/cardano/rbac/registrations_get.rs
  catalyst-gateway/bin/src/service/api/cardano/rbac/role0_chain_root_get.rs
  catalyst-gateway/bin/src/service/api/cardano/staking/assets_get.rs
  catalyst-gateway/bin/src/service/api/config/mod.rs
  catalyst-gateway/bin/src/service/api/documents/post_document_index_query/mod.rs
  catalyst-gateway/bin/src/service/api/documents/post_document_index_query/query_filter.rs
  catalyst-gateway/bin/src/service/api/documents/post_document_index_query/response.rs
  catalyst-gateway/bin/src/service/api/documents/put_document/unprocessable_content_request.rs
  catalyst-gateway/bin/src/service/common/objects/cardano/hash.rs
  catalyst-gateway/bin/src/service/common/objects/cardano/mod.rs
  catalyst-gateway/bin/src/service/common/objects/cardano/registration_info.rs
  catalyst-gateway/bin/src/service/common/objects/cardano/slot_info.rs
  catalyst-gateway/bin/src/service/common/objects/cardano/stake_info.rs
  catalyst-gateway/bin/src/service/common/objects/cardano/sync_state.rs
  catalyst-gateway/bin/src/service/common/objects/config/environment.rs
  catalyst-gateway/bin/src/service/common/objects/config/frontend_config.rs
  catalyst-gateway/bin/src/service/common/objects/config/mod.rs
  catalyst-gateway/bin/src/service/common/objects/config/version.rs
  catalyst-gateway/bin/src/service/common/objects/generic/json_object.rs
  catalyst-gateway/bin/src/service/common/objects/generic/mod.rs
  catalyst-gateway/bin/src/service/common/responses/code_401_unauthorized.rs
  catalyst-gateway/bin/src/service/common/responses/code_403_forbidden.rs
  catalyst-gateway/bin/src/service/common/responses/code_412_precondition_failed.rs
  catalyst-gateway/bin/src/service/common/responses/code_429_too_many_requests.rs
  catalyst-gateway/bin/src/service/common/responses/code_500_internal_server_error.rs
  catalyst-gateway/bin/src/service/common/responses/code_503_service_unavailable.rs
  catalyst-gateway/bin/src/service/common/types/array_types.rs
  catalyst-gateway/bin/src/service/common/types/cardano/asset_value.rs
  catalyst-gateway/bin/src/service/common/types/cardano/boolean.rs
  catalyst-gateway/bin/src/service/common/types/cardano/mod.rs
  catalyst-gateway/bin/src/service/common/types/cardano/query/as_at.rs
  catalyst-gateway/bin/src/service/common/types/cardano/registration_list.rs
  catalyst-gateway/bin/src/service/common/types/cardano/slot_no.rs
  catalyst-gateway/bin/src/service/common/types/document/doc_ref.rs
  catalyst-gateway/bin/src/service/common/types/generic/date_time.rs
  catalyst-gateway/bin/src/service/common/types/generic/error_list.rs
  catalyst-gateway/bin/src/service/common/types/generic/error_uuid.rs
  catalyst-gateway/bin/src/service/common/types/generic/mod.rs
  catalyst-gateway/bin/src/service/common/types/generic/url.rs
  catalyst-gateway/bin/src/service/common/types/mod.rs
  catalyst-gateway/bin/src/service/common/types/payload/cbor.rs
  catalyst-gateway/tests/openapi-v3.0-lints/.spectral.yml
Labels: review me, rust

#1899 docs(general): fix markdown in README.md
  README.md
Labels: review me

#1819 feat(cat-voices): changed the id to point to proposal on git
  docs/src/architecture/08_concepts/document_templates/proposal/F14-Generic/0ce8ab38-9258-4fbc-a62e-7faa6e58318f.schema.json
  docs/src/architecture/08_concepts/document_templates/proposal/F14-Generic/example.proposal.json
Labels: comment me, F14

#1845 feat(cat-voices): integrate cat-gateway network layer
  .earthlyignore
  .github/workflows/ci.yml
  catalyst_voices/.earthlyignore
  catalyst_voices/.gitignore
  catalyst_voices/Earthfile
  catalyst_voices/apps/voices/lib/dependency/dependencies.dart
  catalyst_voices/justfile
  catalyst_voices/melos.yaml
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/account/account_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/session/session_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_blocs/test/session/session_cubit_test.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/app_config.dart
  catalyst_voices/packages/internal/catalyst_voices_models/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_repositories/README.md
  catalyst_voices/packages/internal/catalyst_voices_repositories/build.yaml
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/generated/api/client_index.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/generated/api/client_mapping.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/api/api.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/api/api_services.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/api/interceptors/rbac_auth_interceptor.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/api/models/overridden_models.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/api/review_module.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/catalyst_voices_repositories.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/openapi-filters.json
  catalyst_voices/packages/internal/catalyst_voices_repositories/openapi/vit.json
  catalyst_voices/packages/internal/catalyst_voices_repositories/openapi/vit.yaml
  catalyst_voices/packages/internal/catalyst_voices_repositories/process_openapi.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/api/interceptors/mock_chain.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/api/interceptors/mock_keychain.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/api/interceptors/mock_response.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/api/interceptors/rbac_auth_interceptor_test.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/user/user_service.dart
  catalyst_voices/packages/internal/catalyst_voices_services/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_services/test/src/user/user_service_test.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/catalyst_voices_shared.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/keychain/keychain_transformers.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/user/user_observer.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_shared/test/src/keychain/keychain_transformers_test.dart
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/wallet-automation/Earthfile
  catalyst_voices/packages/libs/catalyst_key_derivation/.earthlyignore
  catalyst_voices/packages/libs/catalyst_key_derivation/Earthfile
  catalyst_voices/packages/libs/catalyst_key_derivation/cargokit/build_tool/pubspec.yaml
  catalyst_voices/utilities/remote_widgets/pubspec.yaml
  catalyst_voices/utilities/uikit_example/Earthfile
Labels: review me, dart

#1853 feat(cat-voices): Favorites proposals and Search input field
  .config/dictionaries/project.dic
  catalyst_voices/apps/voices/lib/pages/proposals/proposal_pagination_tabview.dart
  catalyst_voices/apps/voices/lib/pages/proposals/proposals_page.dart
  catalyst_voices/apps/voices/lib/pages/proposals/proposals_pagination.dart
  catalyst_voices/apps/voices/lib/widgets/pagination/layouts/paginated_grid_view.dart.dart
  catalyst_voices/apps/voices/lib/widgets/pagination/paging_controller.dart
  catalyst_voices/apps/voices/lib/widgets/pagination/paging_state.dart
  catalyst_voices/apps/voices/lib/widgets/search/search_text_field.dart
  catalyst_voices/apps/voices/test/widgets/dropdown/category_dropdown_test.dart
  catalyst_voices/apps/voices/test/widgets/paging/paging_controller_test.dart
  catalyst_voices/apps/voices/test/widgets/search/search_text_field_test.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposals/proposals_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposals/proposals_state.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/test/proposals/proposals_cubit_test.dart
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/proposal/proposal_pagination_items.dart
  catalyst_voices/packages/internal/catalyst_voices_models/test/proposal/proposal_pagination_items_test.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/proposal/proposal_repository.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/proposal/proposal_service.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/catalyst_voices_shared.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/range/paging_range.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/catalyst_voices_view_models.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/proposal/proposal_pagination_view_model.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/proposal/proposal_view_model.dart
Labels: review me, ux/ui, F14

#1886 chore(cat-voices): cleanup proposal builder actions
  catalyst_voices/apps/voices/lib/pages/spaces/appbar/proposal_builder_status_action.dart
  catalyst_voices/apps/voices/lib/widgets/cards/pending_proposal_card.dart
  catalyst_voices/apps/voices/lib/widgets/cards/proposal_card_widgets.dart
  catalyst_voices/apps/voices/lib/widgets/modals/proposals/proposal_builder_dialog_widgets.dart
  catalyst_voices/apps/voices/lib/widgets/modals/proposals/publish_proposal_iteration_dialog.dart
  catalyst_voices/apps/voices/lib/widgets/modals/proposals/submit_proposal_for_review_dialog.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/proposal_builder_bloc.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/proposal_builder_event.dart
Labels: review me, dart, F14

#1922 fix(cat-gateway): Set a strict version of the `base64ct` transitive dep
  catalyst-gateway/bin/Cargo.toml
Labels: review me

#1901 fix(general): rbac indexing invalids
  catalyst-gateway/bin/src/db/index/queries/registrations/get_all_invalids.rs
  catalyst-gateway/bin/src/db/index/queries/registrations/get_all_registrations.rs
  catalyst-gateway/bin/src/db/mod.rs
  catalyst-gateway/bin/src/service/api/cardano/cip36/filter.rs
  catalyst-gateway/bin/src/service/common/types/cardano/txn_index.rs
Labels: F14

#1738 feat: added F14 base category questions
  docs/src/architecture/08_concepts/document_templates/proposal/F14-Generic/0ce8ab38-9258-4fbc-a62e-7faa6e58318f.schema.json
Labels: review me, comment me, F14

#1870 fix(cat-gateway): Update service liveness
  catalyst-gateway/bin/src/cli.rs
  catalyst-gateway/bin/src/service/api/health/live_get.rs
  catalyst-gateway/bin/src/service/utilities/catch_panic.rs
  catalyst-gateway/bin/src/service/utilities/health/live.rs
  catalyst-gateway/bin/src/service/utilities/health/mod.rs
  catalyst-gateway/bin/src/service/utilities/mod.rs
  catalyst-gateway/bin/src/settings/mod.rs
Labels: enhancement, review me, F14

#1920 feat(cat-gateway): Partially implement Catalyst RBAC token validation
  catalyst-gateway/bin/Cargo.toml
  catalyst-gateway/bin/src/service/common/auth/none_or_rbac.rs
  catalyst-gateway/bin/src/service/common/auth/rbac/scheme.rs
  catalyst-gateway/bin/src/service/common/auth/rbac/token.rs
  catalyst-gateway/bin/src/service/common/responses/mod.rs
  catalyst-gateway/bin/src/service/common/types/cardano/catalyst_id.rs
Labels: do not merge yet

#1927 feat(cat-voices): Export proposal
  catalyst_voices/apps/voices/lib/dependency/dependencies.dart
  catalyst_voices/apps/voices/lib/pages/proposal_builder/appbar/proposal_builder_status_action.dart
  catalyst_voices/apps/voices/lib/pages/proposal_builder/proposal_builder_page.dart
  catalyst_voices/apps/voices/lib/pages/registration/registration_dialog.dart
  catalyst_voices/apps/voices/lib/pages/registration/widgets/export_catalyst_key_confirm_dialog.dart
  catalyst_voices/apps/voices/lib/pages/registration/widgets/registration_confirm_dialog.dart
  catalyst_voices/apps/voices/lib/pages/workspace/header/import_proposal_button.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/proposal_builder_bloc.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/proposal_builder_event.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/proposal_builder_state.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/registration/cubits/keychain_creation_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/registration/registration_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/data/document_type.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/document/document_repository.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/document_data_dto.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/catalyst_voices_services.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/downloader/downloader.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/downloader/downloader_service.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/downloader/utils/downloader.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/downloader/utils/downloader_stub.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/downloader/utils/io_downloader.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/downloader/utils/web_downloader.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/proposal/proposal_service.dart
Labels: review me, ux/ui, dart, F14

#1929 feat(cat-voices): Import proposal
  catalyst_voices/apps/voices/lib/dependency/dependencies.dart
  catalyst_voices/apps/voices/lib/pages/registration/upload_seed_phrase_dialog.dart
  catalyst_voices/apps/voices/lib/pages/workspace/header/import_proposal_button.dart
  catalyst_voices/apps/voices/lib/pages/workspace/header/workspace_header.dart
  catalyst_voices/apps/voices/lib/pages/workspace/page/workspace_page.dart
  catalyst_voices/apps/voices/lib/widgets/modals/voices_upload_file_dialog.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/proposal_builder_bloc.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/proposal_builder_state.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/workspace/workspace_bloc.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/workspace/workspace_event.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/workspace/workspace_state.dart
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/data/document_data_metadata.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/document_ref.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/specialized/proposal_document.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/document/document_repository.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/proposal/proposal_service.dart
  catalyst_voices/utilities/uikit_example/lib/examples/voices_modals_example.dart
Labels: review me, dart, F14

#1928 feat(cat-voices): uuid utils
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/hi_lo/uuid_hi_lo.dart
  catalyst_voices/packages/internal/catalyst_voices_models/test/hi_lo/uuid_hi_lo_test.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/catalyst_voices_shared.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/utils/string_ext.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/utils/uuid_utils.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/test/src/utils/uuid_utils_test.dart
Labels: review me, dart
