Repository input-output-hk/catalyst-voices, pull requests merged in 2025-08, with the labels that each got.

#3163 fix(cat-voices): user cant scroll to action buttons when wrong screen resolution
  catalyst_voices/apps/voices/lib/pages/account/delete_keychain_dialog.dart
  catalyst_voices/apps/voices/lib/pages/registration/wallet_link/account_role_dialog.dart
  catalyst_voices/apps/voices/lib/widgets/comment/pick_username_dialog.dart
  catalyst_voices/apps/voices/lib/widgets/modals/proposals/forget_proposal_dialog.dart
  catalyst_voices/apps/voices/lib/widgets/modals/proposals/publish_proposal_iteration_dialog.dart
  catalyst_voices/apps/voices/lib/widgets/modals/proposals/submit_proposal_for_review_dialog.dart
  catalyst_voices/apps/voices/lib/widgets/modals/proposals/unlock_edit_proposal.dart
  catalyst_voices/apps/voices/lib/widgets/modals/voices_info_dialog.dart
Labels: review me, ux/ui, squad: face, fyi: design

#3167 feat(cat-gateway): replace `CounterVec` with more performant `IntCounterVec`
  catalyst-gateway/bin/src/metrics/caches/native_assets.rs
  catalyst-gateway/bin/src/metrics/caches/txo_assets.rs
  catalyst-gateway/bin/src/metrics/chain_indexer.rs
  catalyst-gateway/bin/src/metrics/rbac.rs
Labels: review me, squad: gatekeepers

#3173 chore: update ci to v3.5.2
  Earthfile
  catalyst-gateway/event-db/Earthfile
  catalyst-gateway/tests/Earthfile
  catalyst-gateway/tests/api_tests/Earthfile
  catalyst_voices/Earthfile
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/wallet-automation/Earthfile
  catalyst_voices/packages/libs/catalyst_key_derivation/Earthfile
  catalyst_voices/utilities/uikit_example/Earthfile
  docs/Earthfile
  utilities/docs-preview/Earthfile
Labels: review me

#3175 feat(cat-gateway): Invalid RBAC registration metric counter
  catalyst-gateway/bin/src/db/index/block/rbac509/mod.rs
  catalyst-gateway/bin/src/metrics/mod.rs
  catalyst-gateway/bin/src/metrics/rbac.rs
Labels: squad: gatekeepers

#3171 fix(cat-gateway): Fix Chain Indexer metrics channel
  .config/dictionaries/project.dic
  .github/CODEOWNERS
  catalyst-gateway/bin/src/cardano/event.rs
  catalyst-gateway/bin/src/cardano/mod.rs
  catalyst-gateway/bin/src/metrics/chain_indexer.rs
Labels: review me, squad: gatekeepers

#3194 fix(cat-gateway): Fix `document/index` endpoints
  catalyst-gateway/bin/src/service/api/documents/post_document_index_query/v1/mod.rs
  catalyst-gateway/bin/src/service/api/documents/post_document_index_query/v2/mod.rs
Labels: review me, squad: gatekeepers

#3189 feat(cat-voices): voting ballot bloc
  catalyst_voices/apps/voices/lib/app/view/app.dart
  catalyst_voices/apps/voices/lib/dependency/dependencies.dart
  catalyst_voices/apps/voices/lib/pages/discovery/sections/most_recent_proposals.dart
  catalyst_voices/apps/voices/lib/pages/proposals/widgets/proposals_pagination_tile.dart
  catalyst_voices/apps/voices/lib/pages/voting/widgets/grid/voting_proposals_pagination_tile.dart
  catalyst_voices/apps/voices/lib/pages/voting/widgets/voting_list/voting_list_ballot.dart
  catalyst_voices/apps/voices/lib/pages/voting/widgets/voting_list/voting_list_campaign_phase_progress.dart
  catalyst_voices/apps/voices/lib/pages/voting/widgets/voting_list/voting_list_footer.dart
  catalyst_voices/apps/voices/lib/pages/voting/widgets/voting_list/voting_list_user_summary.dart
  catalyst_voices/apps/voices/lib/widgets/cards/proposal/proposal_brief_card.dart
  catalyst_voices/apps/voices/lib/widgets/text/timezone_date_time_text.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/campaign/campaign_phase/campaign_phase_aware_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/catalyst_voices_blocs.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposals/proposals_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/voting/voting_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/voting_ballot/voting_ballot.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/voting_ballot/voting_ballot_bloc.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/voting_ballot/voting_ballot_cache.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/voting_ballot/voting_ballot_event.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/voting_ballot/voting_ballot_state.dart
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/campaign/campaign_timeline.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/catalyst_voices_models.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/document_ref.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/proposal/core_proposal.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/proposal/detail_proposal.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/proposal/proposal_with_context.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/user/preferences.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/voting/vote.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/voting/vote_proposal.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/voting/voting_ballot_builder.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/voting/voting_ballot_local_builder.dart
  catalyst_voices/packages/internal/catalyst_voices_models/test/voting/voting_ballot_local_builder_test.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/campaign/active_campaign_observer.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/campaign/campaign_service.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/range/date_range.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/catalyst_voices_view_models.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/proposal/proposal_brief.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/voting/voting_list_campaign_phase_data.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/voting/voting_list_footer_data.dart
Labels: squad: face, a: voting

#3198 fix(cat-gateway): Scylla session redundant re-init process
  catalyst-gateway/bin/src/cardano/mod.rs
  catalyst-gateway/bin/src/db/index/session.rs
  catalyst-gateway/bin/src/db/index/tests/mod.rs
  catalyst-gateway/bin/src/service/api/health/ready_get.rs
Labels: review me, squad: gatekeepers

#3201 chore(cat-gateway): Update the `rbac-registration` dependency to `0.0.7` version
  catalyst-gateway/bin/Cargo.toml
  catalyst-gateway/bin/src/rbac/get_chain.rs
  catalyst-gateway/bin/src/rbac/validation.rs
Labels: review me, rr: gatekeepers

#3197 feat(cat-voices): voting service to ballot builder
  catalyst_voices/apps/voices/lib/dependency/dependencies.dart
  catalyst_voices/apps/voices/lib/pages/proposal/tiles/proposal_voting_overview.dart
  catalyst_voices/apps/voices/lib/pages/spaces/appbar/voting/vote_list_button.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal/proposal_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal/proposal_cubit_cache.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposals/proposals_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposals/proposals_cubit_cache.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/voting/voting_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/voting/voting_cubit_cache.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/voting_ballot/voting_ballot_bloc.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/voting_ballot/voting_ballot_cache.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/voting_ballot/voting_ballot_state.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/workspace/workspace_bloc.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/campaign/campaign_category.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/proposal/proposal_with_context.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/voting/vote.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/voting/vote_proposal.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/voting/voting_repository.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/proposal/proposal_service.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/voting/voting_service.dart
  catalyst_voices/packages/internal/catalyst_voices_services/test/src/proposal/proposal_service_test.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/proposal/proposal_brief.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/proposal/proposal_view_voting.dart
Labels: draft, review me, squad: face, a: voting

#3193 ci(general): add project fields validation
  .github/workflows/validate-project-fields.yml
Labels: review me

#3206 fix(cat-gateway): bump `cardano-chain-follower`
  catalyst-gateway/bin/Cargo.toml
Labels: review me, squad: gatekeepers

#3217 feat(cat-voices): read only vote button
  catalyst_voices/apps/voices/lib/pages/voting/widgets/grid/voting_proposals_pagination_tile.dart
  catalyst_voices/apps/voices/lib/widgets/cards/proposal/proposal_brief_card.dart
  catalyst_voices/apps/voices/lib/widgets/voting/vote_button.dart
  catalyst_voices/apps/voices/lib/widgets/voting/vote_button_expanded.dart
Labels: F15, squad: face, a: voting

#3230 chore(cat-voices): integration tests formatting
  catalyst_voices/apps/voices/integration_test/pageobject/account_dropdown_page.dart
  catalyst_voices/apps/voices/integration_test/pageobject/app_bar_page.dart
  catalyst_voices/apps/voices/integration_test/pageobject/common_page.dart
  catalyst_voices/apps/voices/integration_test/pageobject/discovery/campaign_categories_section.dart
  catalyst_voices/apps/voices/integration_test/pageobject/discovery/campaign_hero_section_page.dart
  catalyst_voices/apps/voices/integration_test/pageobject/discovery/current_campaign_selector_page.dart
  catalyst_voices/apps/voices/integration_test/pageobject/discovery/how_it_works_section_page.dart
  catalyst_voices/apps/voices/integration_test/pageobject/discovery/most_recent_section.dart
  catalyst_voices/apps/voices/integration_test/pageobject/discovery_page.dart
  catalyst_voices/apps/voices/integration_test/pageobject/onboarding/create_flow/step_10_input_seedphrase.dart
  catalyst_voices/apps/voices/integration_test/pageobject/onboarding/create_flow/step_11_seedphrase_success.dart
  catalyst_voices/apps/voices/integration_test/pageobject/onboarding/create_flow/step_12_password_info.dart
  catalyst_voices/apps/voices/integration_test/pageobject/onboarding/create_flow/step_13_password_input.dart
  catalyst_voices/apps/voices/integration_test/pageobject/onboarding/create_flow/step_14_keychain_final.dart
  catalyst_voices/apps/voices/integration_test/pageobject/onboarding/create_flow/step_15_link_wallet_info.dart
  catalyst_voices/apps/voices/integration_test/pageobject/onboarding/create_flow/step_16_wallet_list.dart
  catalyst_voices/apps/voices/integration_test/pageobject/onboarding/create_flow/step_2_profile_info.dart
  catalyst_voices/apps/voices/integration_test/pageobject/onboarding/create_flow/step_3_setup_profile.dart
  catalyst_voices/apps/voices/integration_test/pageobject/onboarding/create_flow/step_5_profile_final.dart
  catalyst_voices/apps/voices/integration_test/pageobject/onboarding/create_flow/step_6_catalyst_keychain_info.dart
  catalyst_voices/apps/voices/integration_test/pageobject/onboarding/create_flow/step_7_catalyst_keychain_success.dart
  catalyst_voices/apps/voices/integration_test/pageobject/onboarding/create_flow/step_8_writedown_seedphrase.dart
  catalyst_voices/apps/voices/integration_test/pageobject/onboarding/create_flow/step_9_writedown_seedphrase_info.dart
  catalyst_voices/apps/voices/integration_test/pageobject/onboarding/onboarding_base_page.dart
  catalyst_voices/apps/voices/integration_test/pageobject/onboarding/restore_flow/step_2_seedphrase_instructions_panel.dart
  catalyst_voices/apps/voices/integration_test/pageobject/onboarding/restore_flow/step_3_restore_keychain_success_panel.dart
  catalyst_voices/apps/voices/integration_test/pageobject/onboarding/restore_flow/step_4_unlock_password_info_panel.dart
  catalyst_voices/apps/voices/integration_test/pageobject/onboarding/restore_flow/step_5_unlock_password_input_panel.dart
  catalyst_voices/apps/voices/integration_test/pageobject/onboarding/restore_flow/step_6_unlock_password_success_panel.dart
  catalyst_voices/apps/voices/integration_test/pageobject/onboarding/step_1_get_started.dart
  catalyst_voices/apps/voices/integration_test/pageobject/profile_page.dart
  catalyst_voices/apps/voices/integration_test/pageobject/proposals_page.dart
  catalyst_voices/apps/voices/integration_test/pageobject/unlock_modal_page.dart
  catalyst_voices/apps/voices/integration_test/utils/mock_url_launcher_platform.dart
  catalyst_voices/apps/voices/integration_test/utils/selector_utils.dart
  catalyst_voices/apps/voices/integration_test/utils/test_context.dart
Labels: squad: face

#3229 feat(cat-gateway): `/panic` endpoint for testing
  .config/dictionaries/project.dic
  catalyst-gateway/bin/src/service/poem_service.rs
  catalyst-gateway/bin/src/service/utilities/catch_panic.rs
  catalyst-gateway/bin/src/settings/mod.rs
  catalyst-gateway/tests/api_tests/poetry.lock
  catalyst-gateway/tests/api_tests/pyproject.toml
  catalyst-gateway/tests/api_tests/scripts/panic_requests.py
  catalyst-gateway/tests/docker-compose.yml
Labels: review me, requires architecture review, squad: gatekeepers

#3235 feat(cat-voices): voted on mocked proposals
  catalyst_voices/apps/voices/lib/dependency/dependencies.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/voting/voting_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/proposals/proposals_count.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/proposal/proposal_service.dart
  catalyst_voices/packages/internal/catalyst_voices_services/test/src/proposal/proposal_service_test.dart
Labels: review me, squad: face

#3253 chore(cat-voices): minor adjustments
  catalyst_voices/apps/voices/lib/pages/account/account_page.dart
  catalyst_voices/apps/voices/lib/pages/account/widgets/account_keychain_tile.dart
  catalyst_voices/apps/voices/lib/pages/proposal/proposal_page.dart
  catalyst_voices/apps/voices/lib/pages/registration/account_completed/account_completed_panel.dart
  catalyst_voices/apps/voices/lib/pages/registration/recover/seed_phrase/restored_panel.dart
  catalyst_voices/apps/voices/lib/pages/spaces/appbar/spaces_appbar/voting_appbar.dart
  catalyst_voices/apps/voices/lib/pages/spaces/appbar/voting/voting_leading_button.dart
  catalyst_voices/apps/voices/lib/pages/voting/voting_page.dart
  catalyst_voices/apps/voices/lib/pages/voting/widgets/content/pre_voting_content.dart
  catalyst_voices/apps/voices/lib/pages/voting/widgets/grid/voting_proposals_tabs.dart
  catalyst_voices/apps/voices/lib/pages/voting/widgets/header/voting_general_header.dart
  catalyst_voices/apps/voices/lib/pages/voting/widgets/header/voting_header.dart
  catalyst_voices/apps/voices/lib/routes/routing/spaces_route.dart
  catalyst_voices/apps/voices/lib/widgets/indicators/voices_linear_progress_indicator.dart
  catalyst_voices/apps/voices/lib/widgets/layouts/header_and_content_layout.dart
  catalyst_voices/apps/voices/lib/widgets/tabbar/voices_tab.dart
  catalyst_voices/apps/voices/lib/widgets/tabbar/voices_tab_bar.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/campaign/campaign_phase/campaign_phase_aware_state.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal/proposal_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal/proposal_cubit_cache.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/session/session_state.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/voting/voting_state.dart
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/authentication/access_control.dart
Labels: squad: face

#3261 chore(cat-voices): workaround for v1 document index bug
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/document/source/document_data_remote_source.dart
Labels: squad: face

#3259 feat(cat-voices): animated loading gif
  catalyst_voices/apps/voices/lib/app/view/app_splash_screen_manager.dart
Labels: review me, F15

#3291 chore(cat-voices): safety check sentry config
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/config/app_config.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/config/app_config_factory.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/config/remote_sentry_config.dart
  config/dev/config.json
  config/preprod/config.json
  config/prod/config.json
Labels: squad: face

#3295 chore(cat-voices): flutter upgrade 3.35.1
  .github/workflows/flutter-publish-packages.yml
  Earthfile
  catalyst-gateway/event-db/Earthfile
  catalyst-gateway/tests/Earthfile
  catalyst_voices/Earthfile
  catalyst_voices/apps/voices/lib/widgets/cards/countdown_value_card.dart
  catalyst_voices/apps/voices/lib/widgets/containers/sidebar/sidebar_panel.dart
  catalyst_voices/apps/voices/lib/widgets/containers/sidebar/space_side_panel.dart
  catalyst_voices/apps/voices/lib/widgets/indicators/voices_loading_overlay.dart
  catalyst_voices/apps/voices/lib/widgets/toggles/voices_radio.dart
  catalyst_voices/apps/voices/lib/widgets/toggles/voices_radio_button_form_field.dart
  catalyst_voices/apps/voices/pubspec.yaml
  catalyst_voices/apps/voices/test/widgets/toggles/voices_radio_button_form_field_test.dart
  catalyst_voices/melos.yaml
  catalyst_voices/packages/internal/catalyst_voices_assets/example/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_assets/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_blocs/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_brands/lib/src/themes/catalyst.dart
  catalyst_voices/packages/internal/catalyst_voices_brands/lib/src/themes/widgets/voices_dialog_theme.dart
  catalyst_voices/packages/internal/catalyst_voices_brands/lib/src/themes/widgets/voices_input_decoration_theme_data.dart
  catalyst_voices/packages/internal/catalyst_voices_brands/lib/src/themes/widgets/voices_popup_menu_theme_data.dart
  catalyst_voices/packages/internal/catalyst_voices_brands/lib/src/themes/widgets/voices_segmented_button_theme_data.dart
  catalyst_voices/packages/internal/catalyst_voices_brands/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_driver/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_localization/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_models/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_repositories/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_services/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_shared/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_view_models/pubspec.yaml
  catalyst_voices/packages/libs/README.md
  catalyst_voices/packages/libs/catalyst_analysis/example/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_analysis/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/README.md
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/example/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/wallet-automation/Earthfile
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano_platform_interface/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano_web/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cardano_serialization/README.md
  catalyst_voices/packages/libs/catalyst_cardano_serialization/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_compression/catalyst_compression/README.md
  catalyst_voices/packages/libs/catalyst_compression/catalyst_compression/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_compression/catalyst_compression_platform_interface/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_compression/catalyst_compression_web/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cose/README.md
  catalyst_voices/packages/libs/catalyst_cose/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_key_derivation/Earthfile
  catalyst_voices/packages/libs/catalyst_key_derivation/README.md
  catalyst_voices/packages/libs/catalyst_key_derivation/cargokit/build_tool/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_key_derivation/example/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_key_derivation/pubspec.yaml
  catalyst_voices/utilities/poc_local_storage/pubspec.yaml
  catalyst_voices/utilities/remote_widgets/example/pubspec.yaml
  catalyst_voices/utilities/remote_widgets/pubspec.yaml
  catalyst_voices/utilities/uikit_example/Earthfile
  catalyst_voices/utilities/uikit_example/lib/examples/voices_radio_example.dart
  catalyst_voices/utilities/uikit_example/pubspec.yaml
  docs/Earthfile
  utilities/docs-preview/Earthfile
Labels: review me, dart, squad: face

#3241 feat(cat-gateway): Add Index DB session cache manager
  catalyst-gateway/bin/Cargo.toml
  catalyst-gateway/bin/src/cardano/mod.rs
  catalyst-gateway/bin/src/db/event/signed_docs/full_signed_doc.rs
  catalyst-gateway/bin/src/db/index/block/rbac509/mod.rs
  catalyst-gateway/bin/src/db/index/queries/caches/assets/ada.rs
  catalyst-gateway/bin/src/db/index/queries/caches/assets/mod.rs
  catalyst-gateway/bin/src/db/index/queries/caches/assets/native.rs
  catalyst-gateway/bin/src/db/index/queries/caches/mod.rs
  catalyst-gateway/bin/src/db/index/queries/caches/rbac/chains.rs
  catalyst-gateway/bin/src/db/index/queries/caches/rbac/mod.rs
  catalyst-gateway/bin/src/db/index/queries/caches/rbac/public_key.rs
  catalyst-gateway/bin/src/db/index/queries/caches/rbac/stake_address.rs
  catalyst-gateway/bin/src/db/index/queries/caches/rbac/transaction_id.rs
  catalyst-gateway/bin/src/db/index/queries/caches/txo_assets_by_stake.rs
  catalyst-gateway/bin/src/db/index/queries/caches/txo_by_stake.rs
  catalyst-gateway/bin/src/db/index/queries/mod.rs
  catalyst-gateway/bin/src/db/index/queries/rbac/get_catalyst_id_from_public_key.rs
  catalyst-gateway/bin/src/db/index/queries/rbac/get_catalyst_id_from_stake_address.rs
  catalyst-gateway/bin/src/db/index/queries/rbac/get_catalyst_id_from_transaction_id.rs
  catalyst-gateway/bin/src/db/index/queries/rbac/get_rbac_invalid_registrations.rs
  catalyst-gateway/bin/src/db/index/queries/staked_ada/get_assets_by_stake_address.rs
  catalyst-gateway/bin/src/db/index/queries/staked_ada/get_txo_by_stake_address.rs
  catalyst-gateway/bin/src/db/index/queries/staked_ada/update_txo_spent.rs
  catalyst-gateway/bin/src/db/index/session/cache_manager.rs
  catalyst-gateway/bin/src/db/index/session/mod.rs
  catalyst-gateway/bin/src/metrics/caches/mod.rs
  catalyst-gateway/bin/src/metrics/caches/native_assets.rs
  catalyst-gateway/bin/src/metrics/caches/rbac.rs
  catalyst-gateway/bin/src/metrics/caches/txo_assets.rs
  catalyst-gateway/bin/src/metrics/mod.rs
  catalyst-gateway/bin/src/metrics/rbac.rs
  catalyst-gateway/bin/src/rbac/chains_cache.rs
  catalyst-gateway/bin/src/rbac/get_chain.rs
  catalyst-gateway/bin/src/rbac/mod.rs
  catalyst-gateway/bin/src/rbac/validation.rs
  catalyst-gateway/bin/src/service/common/types/cardano/query/cat_id_or_stake.rs
  catalyst-gateway/bin/src/service/utilities/cache.rs
  catalyst-gateway/bin/src/settings/cardano_assets_cache.rs
Labels: squad: gatekeepers

#3191 test(cat-gateway): Fix health tests
  .config/dictionaries/project.dic
  .github/workflows/ci.yml
  .github/workflows/gateway-tests.yml
  catalyst-gateway/tests/Earthfile
  catalyst-gateway/tests/api_tests/Earthfile
  catalyst-gateway/tests/api_tests/Readme.md
  catalyst-gateway/tests/api_tests/integration/test_health.py
  catalyst-gateway/tests/api_tests/integration/test_health_thru_proxy.py
  catalyst-gateway/tests/api_tests/poetry.lock
  catalyst-gateway/tests/api_tests/pyproject.toml
  catalyst-gateway/tests/api_tests/utils/__init__.py
  catalyst-gateway/tests/api_tests/utils/panic.py
  catalyst-gateway/tests/api_tests/utils/proxy/haproxy.cfg
  catalyst-gateway/tests/api_tests/utils/proxy/haproxy_entry.sh
  catalyst-gateway/tests/api_tests/wrappers/__init__.py
  catalyst-gateway/tests/api_tests/wrappers/cat_gateway.py
  catalyst-gateway/tests/docker-compose.yml
Labels: rr: qa, rr: gatekeepers

#3311 feat(cat-voices): attach user `cat.id` while reporting
  catalyst_voices/apps/voices/lib/configs/bootstrap.dart
  catalyst_voices/apps/voices/lib/configs/sentry_service.dart
  catalyst_voices/apps/voices/lib/dependency/dependencies.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/catalyst_voices_models.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/config/app_config.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/config/reporting_service_config.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/catalyst_voices_services.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/reporting/reporting_service.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/reporting/reporting_service_mediator.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/reporting/sentry_reporting_service.dart
Labels: squad: face

#3312 feat(cat-voices): sentry navigation observing
  catalyst_voices/apps/voices/lib/configs/bootstrap.dart
  catalyst_voices/apps/voices/lib/pages/discovery/discovery_page.dart
  catalyst_voices/apps/voices/lib/routes/app_router_factory.dart
  catalyst_voices/apps/voices/lib/routes/routing/account_route.dart
  catalyst_voices/apps/voices/lib/routes/routing/overall_spaces_route.dart
  catalyst_voices/apps/voices/lib/routes/routing/proposal_builder_route.dart
  catalyst_voices/apps/voices/lib/routes/routing/proposal_route.dart
  catalyst_voices/apps/voices/lib/routes/routing/spaces_route.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/config/app_config.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/config/app_config_factory.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/config/remote_sentry_config.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/reporting/reporting_service.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/reporting/sentry_reporting_service.dart
  config/dev/config.json
  config/preprod/config.json
  config/prod/config.json
Labels: squad: face
