Repository input-output-hk/catalyst-voices, pull requests merged in 2025-04, with the labels that each got.

#2109 fix(cat-gateway): Fix `cardano/assets` endpoint.
  catalyst-gateway/bin/src/db/types/slot.rs
  catalyst-gateway/bin/src/service/api/cardano/staking/assets_get.rs
  catalyst-gateway/bin/src/service/api/cardano/staking/mod.rs
  catalyst-gateway/bin/src/service/common/objects/cardano/stake_info.rs
  catalyst-gateway/bin/src/service/common/types/cardano/slot_no.rs
Labels: review me

#2130 feat(cat-voices): auth error response handling
  catalyst_voices/apps/voices/lib/dependency/dependencies.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/api/interceptors/rbac_auth_interceptor.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/auth/auth_token_provider.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/api/interceptors/rbac_auth_interceptor_test.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/api/matcher/request_matchers.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/auth/auth_service.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/auth/auth_token_cache.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/catalyst_voices_services.dart
  catalyst_voices/packages/internal/catalyst_voices_services/test/src/auth/auth_service_test.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/cache/local_tll_cache.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/cache/ttl_cache.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/test/src/cache/local_tll_cache_test.dart
Labels: review me, dart, F14

#2133 feat(cat-voices): submission action tests
  catalyst-gateway/tests/api_tests/integration/test_signed_doc.py
  catalyst-gateway/tests/api_tests/test_data/signed_docs/submission_action.json
Labels: F14

#2115 test(cat-gateway): add valid and invalid test data for CIP509 registration
  catalyst-gateway/tests/api_tests/test_data/cip509/invalid.jsonc
  catalyst-gateway/tests/api_tests/test_data/cip509/valid.jsonc
Labels: review me

#2149 feat(cat-voices): Make text selectable on Discovery and Category Page
  catalyst_voices/apps/voices/lib/pages/category/category_page.dart
  catalyst_voices/apps/voices/lib/pages/discovery/discovery_page.dart
Labels: review me, ux/ui, dart, F14

#2156 chore(cat-voices): disposing more objects
  catalyst_voices/apps/voices/lib/app/view/app_active_state_listener.dart
  catalyst_voices/apps/voices/lib/dependency/dependencies.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposals/proposals_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/database/catalyst_database.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/dependency/dependency_provider.dart
Labels: review me, dart

#2125 feat(cat-voices): campaign timeline config
  catalyst_voices/apps/voices/lib/app/view/app.dart
  catalyst_voices/apps/voices/lib/app/view/app_mobile_access_restriction.dart
  catalyst_voices/apps/voices/lib/dependency/dependencies.dart
  catalyst_voices/apps/voices/lib/pages/campaign/stage/after_proposal_submission_page.dart
  catalyst_voices/apps/voices/lib/pages/campaign/stage/campaign_background.dart
  catalyst_voices/apps/voices/lib/pages/campaign/stage/error_proposal_submission_page.dart
  catalyst_voices/apps/voices/lib/pages/campaign/stage/pre_proposal_submission_page.dart
  catalyst_voices/apps/voices/lib/pages/proposal_builder/proposal_builder_page.dart
  catalyst_voices/apps/voices/lib/pages/registration/get_started/get_started_panel.dart
  catalyst_voices/apps/voices/lib/pages/registration/no_wallet_found_dialog.dart
  catalyst_voices/apps/voices/lib/pages/spaces/appbar/session_action_header.dart
  catalyst_voices/apps/voices/lib/pages/workspace/header/workspace_header.dart
  catalyst_voices/apps/voices/lib/pages/workspace/page/workspace_page.dart
  catalyst_voices/apps/voices/lib/pages/workspace/submission_closing_warning_dialog.dart
  catalyst_voices/apps/voices/lib/routes/guards/proposal_submission_guard.dart
  catalyst_voices/apps/voices/lib/routes/routing/account_route.dart
  catalyst_voices/apps/voices/lib/routes/routing/campaign_stage_route.dart
  catalyst_voices/apps/voices/lib/routes/routing/overall_spaces_route.dart
  catalyst_voices/apps/voices/lib/routes/routing/proposal_builder_route.dart
  catalyst_voices/apps/voices/lib/routes/routing/proposal_route.dart
  catalyst_voices/apps/voices/lib/routes/routing/routes.dart
  catalyst_voices/apps/voices/lib/routes/routing/spaces_route.dart
  catalyst_voices/apps/voices/lib/widgets/cards/countdown_value_card.dart
  catalyst_voices/apps/voices/lib/widgets/cards/tip_card.dart
  catalyst_voices/apps/voices/lib/widgets/countdown/voices_countdown.dart
  catalyst_voices/apps/voices/lib/widgets/modals/voices_desktop_dialog.dart
  catalyst_voices/apps/voices/lib/widgets/painter/bubble_painter.dart
  catalyst_voices/apps/voices/lib/widgets/text/proposal_submission_closes_text.dart
  catalyst_voices/apps/voices/lib/widgets/text/proposal_submission_start_text.dart
  catalyst_voices/apps/voices/test/widgets/campaign_timeline/campaign_timeline_card_test.dart
  catalyst_voices/apps/voices/test/widgets/campaign_timeline/campaign_timeline_test.dart
  catalyst_voices/apps/voices/test/widgets/countdown/voices_countdown_test.dart
  catalyst_voices/packages/internal/catalyst_voices_assets/assets/images/eternl_wallet.webp
  catalyst_voices/packages/internal/catalyst_voices_assets/assets/images/heads_up.webp
  catalyst_voices/packages/internal/catalyst_voices_assets/assets/images/lace_wallet.webp
  catalyst_voices/packages/internal/catalyst_voices_assets/assets/images/nami_wallet.webp
  catalyst_voices/packages/internal/catalyst_voices_assets/assets/images/thanks.webp
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/campaign/campaign_stage/campaign_stage.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/campaign/campaign_stage/campaign_stage_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/campaign/campaign_stage/campaign_stage_state.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/catalyst_voices_blocs.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/proposal_builder_bloc.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/proposal_builder_event.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/proposal_builder_signal.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/session/session_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/workspace/workspace_bloc.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/workspace/workspace_event.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/workspace/workspace_signal.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/workspace/workspace_state.dart
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/campaign/campaign_timeline.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/user/user_settings.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/user_dto.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/registration/registration_service.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/range/date_range.dart
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/utils/string_ext.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/campaign/campaign_timeline_view_model.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/session/session_settings.dart
Labels: review me, ux/ui, F14

#2144 feat(cat-voices): connect propsal action
  catalyst_voices/apps/voices/lib/widgets/cards/pending_proposal_card.dart
  catalyst_voices/apps/voices/lib/widgets/cards/proposal_iteration_history_card.dart
  catalyst_voices/apps/voices/lib/widgets/text/last_edit_date.dart
  catalyst_voices/apps/voices/lib/widgets/text/proposal_version_info_text.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/discovery/discovery_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/proposal_builder_bloc.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/workspace/workspace_bloc.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/proposal/proposal.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/proposal/proposal_data.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/proposal/proposal_version.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/database/dao/documents_dao.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/database/dao/drafts_dao.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/document/document_repository.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/document/source/database_documents_data_source.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/document/source/document_data_local_source.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/proposal/proposal_submission_action_dto.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/proposal/proposal_repository.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/database/dao/documents_dao_test.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/proposal/proposal_service.dart
  catalyst_voices/packages/internal/catalyst_voices_services/test/src/proposal/proposal_service_test.dart
Labels: review me, ux/ui, dart, F14

#2158 fix(cat-voices): fillPosition in single pane dialog
  catalyst_voices/apps/voices/lib/widgets/modals/comment/submit_comment_error_dialog.dart
  catalyst_voices/apps/voices/lib/widgets/modals/voices_desktop_dialog.dart
  catalyst_voices/apps/voices/lib/widgets/modals/voices_info_dialog.dart
Labels: bug, review me, ux/ui, F14

#2148 fix(cat-voices): proposal view iteration order
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal/proposal_cubit.dart
Labels: bug, review me, ux/ui, dart, F14

#2123 feat(cat-gateway): Store `RegistrationChain` as a part of the RBAC token
  catalyst-gateway/bin/Cargo.toml
  catalyst-gateway/bin/src/db/index/queries/rbac/get_rbac_registrations.rs
  catalyst-gateway/bin/src/db/index/session.rs
  catalyst-gateway/bin/src/service/common/auth/rbac/scheme.rs
  catalyst-gateway/bin/src/service/common/auth/rbac/token.rs
Labels: review me, rust

#2164 fix(cat-gateway): Fix `cat-gateway` build.
  catalyst-gateway/bin/Cargo.toml
Labels: review me

#2160 fix(cat-gateway): Use persistent state in volatile asset calculation
  catalyst-gateway/bin/src/service/api/cardano/staking/assets_get.rs
Labels: bug, review me

#2159 feat(cat-voices): integrate user proposals into drawer and overall spaces
  catalyst_voices/apps/voices/lib/common/typedefs.dart
  catalyst_voices/apps/voices/lib/pages/overall_spaces/space/discovery_overview.dart
  catalyst_voices/apps/voices/lib/pages/overall_spaces/space/user_proposal_selectors/discovery_overview_proposal_selector.dart
  catalyst_voices/apps/voices/lib/pages/overall_spaces/space/user_proposal_selectors/user_proposal_selectors.dart
  catalyst_voices/apps/voices/lib/pages/overall_spaces/space/user_proposal_selectors/user_proposals_selector_widgets.dart
  catalyst_voices/apps/voices/lib/pages/overall_spaces/space/user_proposal_selectors/workspace_overview_proposal_selector.dart
  catalyst_voices/apps/voices/lib/pages/overall_spaces/space/workspace_overview.dart
  catalyst_voices/apps/voices/lib/pages/overall_spaces/spaces_overview_list_view.dart
  catalyst_voices/apps/voices/lib/pages/spaces/drawer/guest_menu.dart
  catalyst_voices/apps/voices/lib/pages/spaces/spaces_shell_page.dart
  catalyst_voices/apps/voices/lib/widgets/cards/small_proposal_card.dart
  catalyst_voices/apps/voices/test/widgets/cards/small_proposal_card_test.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/workspace/workspace_bloc.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/workspace/workspace_event.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/workspace/workspace_state.dart
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/proposal/proposal_version.dart
Labels: review me, ux/ui, F14

#2163 test(cat-gateway): Generate auth token for test
  catalyst-gateway/tests/api_tests/Earthfile
  catalyst-gateway/tests/api_tests/api/__init__.py
  catalyst-gateway/tests/api_tests/api/v1/document.py
  catalyst-gateway/tests/api_tests/integration/test_signed_doc.py
  catalyst-gateway/tests/api_tests/poetry.lock
  catalyst-gateway/tests/api_tests/pyproject.toml
  catalyst-gateway/tests/api_tests/utils/auth_token.py
  docs/src/catalyst-standards/permissionless-auth/auth-header.md
Labels: enhancement, review me, python

#2146 feat(cat-gateway): Bumped cat-libs, include Catalyst Signed Docs time based validation
  catalyst-gateway/bin/Cargo.toml
  catalyst-gateway/bin/src/service/api/documents/get_document.rs
  catalyst-gateway/bin/src/settings/mod.rs
  catalyst-gateway/bin/src/settings/signed_doc.rs
  catalyst-gateway/tests/api_tests/integration/test_signed_doc.py
  catalyst-gateway/tests/api_tests/poetry.lock
  catalyst-gateway/tests/api_tests/pyproject.toml
  catalyst-gateway/tests/api_tests/utils/uuid_v7.py
Labels: review me

#2178 fix(cat-gateway): Fix `catalyst_key_derivation` build
  Earthfile
  catalyst-gateway/Earthfile
  catalyst-gateway/event-db/Earthfile
  catalyst-gateway/tests/Earthfile
  catalyst-gateway/tests/api_tests/Earthfile
  catalyst_voices/Earthfile
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/wallet-automation/Earthfile
  catalyst_voices/packages/libs/catalyst_key_derivation/Earthfile
  catalyst_voices/packages/libs/catalyst_key_derivation/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_key_derivation/rust/Cargo.toml
  catalyst_voices/packages/libs/catalyst_key_derivation/rust/Earthfile
  catalyst_voices/utilities/uikit_example/Earthfile
  docs/Earthfile
  utilities/docs-preview/Earthfile
Labels: review me

#2179 fix(cat-voices): handle new versions created by the proposal builder
  catalyst_voices/apps/voices/lib/widgets/modals/proposals/create_new_proposal_dialog.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/new_proposal/new_proposal_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/proposal_builder_bloc.dart
Labels: bug, review me, dart, F14

#2183 feat(cat-voices): hide admin functionality
  catalyst_voices/apps/voices/lib/pages/overall_spaces/back_fab.dart
  catalyst_voices/apps/voices/lib/pages/spaces/spaces_shell_page.dart
Labels: review me, dart, F14

#2169 fix(cat-voices): view comments in workspace page
  catalyst_voices/apps/voices/lib/pages/overall_spaces/space/workspace_overview.dart
  catalyst_voices/apps/voices/lib/pages/proposals/proposals_page.dart
  catalyst_voices/apps/voices/lib/pages/workspace/header/workspace_header.dart
  catalyst_voices/apps/voices/lib/routes/routing/spaces_route.dart
  catalyst_voices/apps/voices/lib/widgets/cards/workspace_proposal_card.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/workspace/workspace_state.dart
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
Labels: review me, ux/ui, F14

#2038 feat(cat-gateway): Add signature validation layer to `PUT /v1/document`
  catalyst-gateway/bin/src/db/event/signed_docs/signed_doc_body.rs
  catalyst-gateway/bin/src/service/api/documents/common/mod.rs
  catalyst-gateway/bin/src/service/api/documents/get_document.rs
  catalyst-gateway/bin/src/service/api/documents/mod.rs
  catalyst-gateway/bin/src/service/api/documents/put_document/mod.rs
  catalyst-gateway/bin/src/service/common/auth/rbac/scheme.rs
Labels: review me, rust

#1974 fix(cat-gateway): Correct Service Health logic
  catalyst-gateway/bin/src/cardano/mod.rs
  catalyst-gateway/bin/src/cli.rs
  catalyst-gateway/bin/src/db/event/mod.rs
  catalyst-gateway/bin/src/db/index/session.rs
  catalyst-gateway/bin/src/service/api/health/live_get.rs
  catalyst-gateway/bin/src/service/api/health/mod.rs
  catalyst-gateway/bin/src/service/api/health/ready_get.rs
  catalyst-gateway/bin/src/service/api/health/started_get.rs
  catalyst-gateway/bin/src/service/api/mod.rs
  catalyst-gateway/bin/src/service/common/responses/mod.rs
  catalyst-gateway/bin/src/service/mod.rs
  catalyst-gateway/bin/src/service/poem_service.rs
  catalyst-gateway/bin/src/service/utilities/health/mod.rs
  catalyst-gateway/bin/src/service/utilities/health/ready.rs
  catalyst-gateway/bin/src/service/utilities/health/start.rs
  catalyst-gateway/bin/src/service/utilities/middleware/db_check.rs
  catalyst-gateway/bin/src/service/utilities/middleware/mod.rs
Labels: enhancement, review me

#2232 fix(cat-gateway): Fix hypothesis.HealthCheck.nested_given error
  catalyst-gateway/tests/schemathesis_tests/hooks/hooks.py
Labels: review me

#2162 feat(cat-voices): Integrate proposals list - Part 1
  catalyst_voices/apps/voices/lib/dependency/dependencies.dart
  catalyst_voices/apps/voices/lib/pages/proposals/proposal_pagination_tabview.dart
  catalyst_voices/apps/voices/lib/pages/proposals/proposals_page.dart
  catalyst_voices/apps/voices/lib/pages/proposals/proposals_pagination.dart
  catalyst_voices/apps/voices/lib/pages/proposals/widgets/category_selector.dart
  catalyst_voices/apps/voices/lib/pages/proposals/widgets/proposals_campaign_details_button.dart
  catalyst_voices/apps/voices/lib/pages/proposals/widgets/proposals_controls.dart
  catalyst_voices/apps/voices/lib/pages/proposals/widgets/proposals_fund_info.dart
  catalyst_voices/apps/voices/lib/pages/proposals/widgets/proposals_header.dart
  catalyst_voices/apps/voices/lib/pages/proposals/widgets/proposals_pagination.dart
  catalyst_voices/apps/voices/lib/pages/proposals/widgets/proposals_pagination_empty_state.dart
  catalyst_voices/apps/voices/lib/pages/proposals/widgets/proposals_pagination_tile.dart
  catalyst_voices/apps/voices/lib/pages/proposals/widgets/proposals_search.dart
  catalyst_voices/apps/voices/lib/pages/proposals/widgets/proposals_tabs.dart
  catalyst_voices/apps/voices/lib/pages/proposals/widgets/proposals_tabs_divider.dart
  catalyst_voices/apps/voices/lib/routes/routing/spaces_route.dart
  catalyst_voices/apps/voices/lib/widgets/cards/campaign_category_card.dart
  catalyst_voices/apps/voices/lib/widgets/pagination/paging_state.dart
  catalyst_voices/melos.yaml
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposals/proposals.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposals/proposals_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposals/proposals_cubit_cache.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposals/proposals_signal.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposals/proposals_state.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/test/proposals/proposals_cubit_test.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/catalyst_voices_models.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/data/proposal_document_data.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/pagination/page.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/pagination/page_request.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/pagination/pagination_page.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/proposal/proposal_pagination_items.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/proposal/proposal_pagination_request.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/proposals/proposals_count.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/proposals/proposals_count_filters.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/proposals/proposals_filters.dart
  catalyst_voices/packages/internal/catalyst_voices_models/test/proposal/proposal_pagination_items_test.dart
  catalyst_voices/packages/internal/catalyst_voices_models/test/proposal/proposal_pagination_request_test.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/database/catalyst_database.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/database/dao/documents_dao.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/database/dao/proposals_dao.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/database/database.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/database/model/joined_proposal_entity.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/database/query/jsonb_expressions.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/document/document_repository.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/document/source/database_documents_data_source.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/document/source/document_data_local_source.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/document/source/proposal_document_data_local_source.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/proposal/proposal_submission_action_dto.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/proposal/proposal_repository.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/database/dao/documents_dao_test.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/database/dao/proposals_dao_test.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/proposal/proposal_service.dart
  catalyst_voices/packages/internal/catalyst_voices_services/test/src/proposal/proposal_service_test.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/catalyst_voices_view_models.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/proposal/proposal_pagination_view_model.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/proposals/proposals_category_selector_item.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/proposals/proposals_filter_type_ext.dart
Labels: review me, dart, F14

#2139 feat(cat-gateway): `cardano/assets` integration test
  catalyst-gateway/tests/api_tests/Earthfile
  catalyst-gateway/tests/api_tests/api/v1/cardano.py
  catalyst-gateway/tests/api_tests/integration/test_assets.py
  catalyst-gateway/tests/api_tests/integration/test_utxo.py
  catalyst-gateway/tests/api_tests/snapshot_tool-56364174.json
  catalyst-gateway/tests/api_tests/utils/snapshot.py
Labels: review me

#2239 test(cat-gateway): use bip32ed25519 instead of normal ed25519 for RBAC auth token
  .config/dictionaries/project.dic
  catalyst-gateway/tests/api_tests/poetry.lock
  catalyst-gateway/tests/api_tests/pyproject.toml
  catalyst-gateway/tests/api_tests/utils/auth_token.py
Labels: bug, python

#2227 feat(cat-voices): integrate proposals list - Part 2
  catalyst_voices/apps/voices/lib/pages/proposals/proposals_page.dart
  catalyst_voices/apps/voices/lib/widgets/cards/pending_proposal_card.dart
  catalyst_voices/apps/voices/lib/widgets/cards/proposal_card.dart
  catalyst_voices/apps/voices/lib/widgets/pagination/layouts/paginated_grid_view.dart.dart
  catalyst_voices/apps/voices/lib/widgets/pagination/paging_state.dart
  catalyst_voices/melos.yaml
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/discovery/discovery_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposals/proposals_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposals/proposals_cubit_cache.dart
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/data/proposal_document_data.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/pagination/page.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/proposal/proposal_data.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/proposals/proposals_count.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/campaign/campaign_repository.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/database/dao/favorites_dao.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/database/dao/proposals_dao.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/database/model/joined_proposal_entity.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/document/source/database_documents_data_source.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/proposal/proposal_repository.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/database/dao/proposals_dao_test.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/proposal/proposal_service.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/proposal/proposal_view_model.dart
Labels: review me, dart, F14

#2173 chore(cat-voices): Ui changes in workspace page/ disable stream when user is not login
  catalyst_voices/apps/voices/lib/pages/discovery/sections/stay_involved.dart
  catalyst_voices/apps/voices/lib/pages/workspace/header/workspace_header.dart
  catalyst_voices/apps/voices/lib/widgets/campaign_timeline/campaign_timeline.dart
  catalyst_voices/apps/voices/lib/widgets/campaign_timeline/campaign_timeline_card.dart
  catalyst_voices/apps/voices/test/widgets/campaign_timeline/campaign_timeline_card_test.dart
  catalyst_voices/apps/voices/test/widgets/campaign_timeline/campaign_timeline_test.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/workspace/workspace_bloc.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/specialized/proposal_document.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/proposal/proposal_service.dart
Labels: review me, F14

#2255 fix(cat-voices): When user locks app should be redirected to Discovery Page
  catalyst_voices/apps/voices/lib/app/view/app_content.dart
  catalyst_voices/apps/voices/lib/app/view/app_session_listener.dart
  catalyst_voices/apps/voices/lib/routes/app_router.dart
Labels: bug, review me, dart

#2229 fix(cat-gateway): Update Document references
  catalyst-gateway/bin/Cargo.toml
  catalyst-gateway/bin/src/service/api/documents/get_document.rs
  catalyst-gateway/bin/src/service/api/documents/templates/mod.rs
  catalyst-gateway/bin/src/service/common/auth/rbac/token.rs
  catalyst-gateway/bin/src/service/common/types/document/doc_ref.rs
  catalyst-gateway/tests/api_tests/integration/test_signed_doc.py
Labels: enhancement, review me

#2259 fix(cat-voices): password not updating after account recovery
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/user/user_service.dart
  catalyst_voices/packages/internal/catalyst_voices_services/test/src/user/user_service_test.dart
Labels: bug, review me, dart, F14

#2261 fix(cat-voices): cancel button text
  catalyst_voices/apps/voices/lib/pages/registration/widgets/export_catalyst_key_confirm_dialog.dart
Labels: bug, review me, ux/ui, dart, F14

#2258 fix(cat-voices): better validation error for checkbox in proposal builder
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/document/validation/localized_document_validation_result.dart
Labels: bug, review me, ux/ui, dart, F14

#2267 fix(cat-voices): update keychain seed phrase confirmation message for clarity in instructions
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
Labels: bug, review me, ux/ui, dart

#2260 fix(cat-voices): hide the button to add roles if all of them are added
  catalyst_voices/apps/voices/lib/pages/account/widgets/account_roles_tile.dart
Labels: bug, review me, dart, F14

#2262 fix(cat-voices): create new proposal dialog - handle missing proposer role
  catalyst_voices/apps/voices/lib/dependency/dependencies.dart
  catalyst_voices/apps/voices/lib/widgets/modals/proposals/create_new_proposal_dialog.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/new_proposal/new_proposal_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/new_proposal/new_proposal_state.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/user/account.dart
Labels: bug, review me, dart, F14

#2270 fix(cat-voices): proper cancel workflow for update keychain
  catalyst_voices/apps/voices/lib/pages/registration/create_keychain/stage/seed_phrase_check_panel.dart
  catalyst_voices/apps/voices/lib/pages/registration/recover/seed_phrase/seed_phrase_input_panel.dart
  catalyst_voices/apps/voices/lib/pages/registration/upload_seed_phrase_dialog.dart
Labels: bug, review me, dart, F14

#2268 refactor(cat-voices): adding onSubmitted method on confirm password in registration dialog
  catalyst_voices/apps/voices/lib/pages/registration/create_keychain/stage/unlock_password_panel.dart
  catalyst_voices/apps/voices/lib/pages/registration/recover/seed_phrase/unlock_password_panel.dart
  catalyst_voices/apps/voices/lib/pages/registration/widgets/unlock_password_form.dart
Labels: bug, review me, ux/ui, dart, F14

#2271 chore(cat-voices): change localize text about ideascale account to more clear one
  catalyst_voices/apps/voices/integration_test/pageobject/onboarding/create_flow/step_3_setup_base_profile.dart
  catalyst_voices/apps/voices/lib/pages/registration/create_base_profile/stage/setup_panel.dart
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
Labels: bug, review me, ux/ui, dart, F14

#2256 feat(cat-voices): share dialog in proposal view
  catalyst_voices/apps/voices/lib/pages/proposal/widget/proposal_share_button.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal/proposal_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/proposal/proposal_view_header.dart
Labels: bug, review me, dart, F14

#2277 feat(cat-gateway): Make `rbac/registration` `v1`
  catalyst-gateway/bin/src/service/api/cardano/rbac/mod.rs
Labels: review me

#2274 chore(cat-voices): Update icons in sidebar of proposal builder
  catalyst_voices/apps/voices/lib/pages/proposal_builder/proposal_builder_navigation_panel.dart
  catalyst_voices/apps/voices/lib/pages/proposal_builder/proposal_builder_page.dart
  catalyst_voices/apps/voices/lib/pages/proposal_builder/proposal_builder_setup_panel.dart
  catalyst_voices/apps/voices/lib/pages/treasury/treasury_details_panel.dart
  catalyst_voices/apps/voices/lib/pages/treasury/treasury_navigation_panel.dart
  catalyst_voices/apps/voices/lib/pages/workspace/page/workspace_page.dart
  catalyst_voices/apps/voices/lib/widgets/containers/sidebar/space_side_panel.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/campaign/campaign_timeline.dart
Labels: bug, review me, dart, F14

#2247 feat(cat-voices): add ScrollbarVisibilityWidget for enhanced scrolling experience in registration setup panel
  catalyst_voices/apps/voices/lib/pages/registration/create_base_profile/stage/setup_panel.dart
Labels: bug, review me, ux/ui, dart, F14

#2231 fix(cat-gateway): Additionally query a Catalyst ID in the persistent dabase when indexing volatile RBAC registrations
  catalyst-gateway/bin/src/db/index/block/mod.rs
  catalyst-gateway/bin/src/db/index/block/rbac509/mod.rs
Labels: review me, rust

#2278 chore(cat-voices): update go_router to 14.8.0 in melos
  catalyst_voices/apps/voices/pubspec.yaml
  catalyst_voices/melos.yaml
  catalyst_voices/utilities/poc_local_storage/pubspec.yaml
Labels: dart, F14

#2235 fix(cat-voices): forget proposal - loading and success/failure state
  catalyst_voices/apps/voices/lib/pages/overall_spaces/space/user_proposal_selectors/workspace_overview_proposal_selector.dart
  catalyst_voices/apps/voices/lib/pages/workspace/page/workspace_loading.dart
  catalyst_voices/apps/voices/lib/pages/workspace/page/workspace_page.dart
  catalyst_voices/apps/voices/lib/widgets/indicators/voices_loading_overlay.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/workspace/workspace_bloc.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/workspace/workspace_signal.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/workspace/workspace_state.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/test/workspace/workspace_bloc_test.dart
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
Labels: bug, review me, ux/ui, dart, F14

#2281 feat(cat-gateway): dynamic postgres config
  catalyst-gateway/bin/src/db/event/mod.rs
  catalyst-gateway/bin/src/settings/event_db.rs
  catalyst-gateway/bin/src/settings/mod.rs
  catalyst-gateway/blueprint.cue
Labels: F14

#2282 fix(cat-voices): Splash screen should be above mobile restriction widget
  catalyst_voices/apps/voices/lib/app/view/app_content.dart
  catalyst_voices/apps/voices/lib/app/view/app_mobile_access_restriction.dart
Labels: bug, ux/ui, dart, F14

#2291 fix(cat-voices): Lock analyzer version to prevent migration issues
  catalyst_voices/apps/voices/pubspec.yaml
  catalyst_voices/melos.yaml
  catalyst_voices/packages/internal/catalyst_voices_assets/example/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_assets/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_blocs/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_brands/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_driver/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_localization/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_models/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_services/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_shared/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_view_models/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_analysis/example/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_analysis/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/example/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano_platform_interface/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano_web/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cardano_serialization/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_compression/catalyst_compression/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_compression/catalyst_compression_platform_interface/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_compression/catalyst_compression_web/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cose/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_key_derivation/cargokit/build_tool/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_key_derivation/example/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_key_derivation/pubspec.yaml
  catalyst_voices/utilities/poc_local_storage/pubspec.yaml
  catalyst_voices/utilities/remote_widgets/example/pubspec.yaml
  catalyst_voices/utilities/remote_widgets/pubspec.yaml
  catalyst_voices/utilities/uikit_example/pubspec.yaml
Labels: bug, dependencies, dart

#2269 feat(cat-gateway): Signed Documents signature validation test
  catalyst-gateway/bin/src/service/api/documents/put_document/mod.rs
  catalyst-gateway/tests/api_tests/Earthfile
  catalyst-gateway/tests/api_tests/Readme.md
  catalyst-gateway/tests/api_tests/api/v1/document.py
  catalyst-gateway/tests/api_tests/integration/test_signed_doc.py
  catalyst-gateway/tests/api_tests/pyproject.toml
  catalyst-gateway/tests/api_tests/test_data/rbac_regs/only_role_0.jsonc
  catalyst-gateway/tests/api_tests/test_data/rbac_regs/role_3.jsonc
  catalyst-gateway/tests/api_tests/utils/auth_token.py
  catalyst-gateway/tests/api_tests/utils/rbac_chain.py
  catalyst-gateway/tests/api_tests/utils/signed_doc.py
Labels: review me

#2294 fix(cat-gateway): Fix processing of `NoneOrRBAC` auth
  catalyst-gateway/bin/src/service/common/auth/mod.rs
  catalyst-gateway/bin/src/service/common/auth/none.rs
  catalyst-gateway/bin/src/service/common/auth/none_or_api_key.rs
  catalyst-gateway/bin/src/service/common/auth/none_or_rbac.rs
Labels: review me

#2177 feat(cat-gateway): Catalyst Signed Docs signature validation
  catalyst-gateway/bin/src/db/event/signed_docs/signed_doc_body.rs
  catalyst-gateway/bin/src/db/index/queries/rbac/get_rbac_registrations.rs
  catalyst-gateway/bin/src/db/index/session.rs
  catalyst-gateway/bin/src/service/api/cardano/rbac/mod.rs
  catalyst-gateway/bin/src/service/api/cardano/rbac/registrations_get/mod.rs
  catalyst-gateway/bin/src/service/api/documents/common/mod.rs
  catalyst-gateway/bin/src/service/api/documents/get_document.rs
  catalyst-gateway/bin/src/service/api/documents/mod.rs
  catalyst-gateway/bin/src/service/api/documents/put_document/mod.rs
  catalyst-gateway/bin/src/service/common/auth/none_or_rbac.rs
  catalyst-gateway/bin/src/service/common/auth/rbac/scheme.rs
  catalyst-gateway/bin/src/service/common/auth/rbac/token.rs
  catalyst-gateway/tests/api_tests/Earthfile
  catalyst-gateway/tests/api_tests/Readme.md
  catalyst-gateway/tests/api_tests/api/v1/document.py
  catalyst-gateway/tests/api_tests/integration/test_signed_doc.py
  catalyst-gateway/tests/api_tests/pyproject.toml
  catalyst-gateway/tests/api_tests/test_data/rbac_regs/only_role_0.jsonc
  catalyst-gateway/tests/api_tests/test_data/rbac_regs/role_3.jsonc
  catalyst-gateway/tests/api_tests/utils/auth_token.py
  catalyst-gateway/tests/api_tests/utils/rbac_chain.py
  catalyst-gateway/tests/api_tests/utils/signed_doc.py
Labels: review me

#2298 feat(cat-voices): Tests for validating proposal node ids
  catalyst_voices/Earthfile
  catalyst_voices/packages/internal/catalyst_voices_assets/assets/document_templates/proposal/F14-Generic/0ce8ab38-9258-4fbc-a62e-7faa6e58318f.schema.json
  catalyst_voices/packages/internal/catalyst_voices_assets/assets/document_templates/proposal/F14-Generic/example.proposal.json
  catalyst_voices/packages/internal/catalyst_voices_assets/lib/src/catalyst_voices_assets.dart
  catalyst_voices/packages/internal/catalyst_voices_assets/lib/src/voices_documents_templates.dart
  catalyst_voices/packages/internal/catalyst_voices_assets/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_assets/test/src/voices_documents_templates_test.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/specialized/proposal_document.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/fixture/comment_template.json
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/fixture/voices_document_templates.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/document/document_dto_test.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/document/document_repository_test.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/document/schema/document_schema_dto_test.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/proposal/proposal_document_test.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/utils/fixture_reader.dart
  docs/src/architecture/08_concepts/document_templates/proposal/F14-Generic/example.proposal.json
Labels: review me, dart

#2299 feat(cat-voices): view all proposals in discovery page when we dont have most recent
  catalyst_voices/apps/voices/lib/pages/discovery/sections/most_recent_proposals.dart
  catalyst_voices/apps/voices/lib/pages/discovery/state_selectors/most_recent_proposals_selector.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/discovery/discovery_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/proposal/proposal_service.dart
Labels: review me, ux/ui, F14

#2300 fix(cat-gateway): Fix test_assets.py
  catalyst-gateway/tests/api_tests/Earthfile
  catalyst-gateway/tests/api_tests/api/v1/document.py
  catalyst-gateway/tests/api_tests/integration/test_assets.py
  catalyst-gateway/tests/api_tests/integration/test_signed_doc.py
  catalyst-gateway/tests/schemathesis_tests/Earthfile
Labels: review me

#2119 feat(cat-gateway): Fixing indexing, assets and cip36 endpoints.
  catalyst-gateway/bin/src/cardano/mod.rs
  catalyst-gateway/bin/src/cli.rs
  catalyst-gateway/bin/src/db/event/mod.rs
  catalyst-gateway/bin/src/db/index/block/certs.rs
  catalyst-gateway/bin/src/db/index/block/cip36/mod.rs
  catalyst-gateway/bin/src/db/index/block/cql/insert_stake_registration.cql
  catalyst-gateway/bin/src/db/index/block/mod.rs
  catalyst-gateway/bin/src/db/index/queries/mod.rs
  catalyst-gateway/bin/src/db/index/schema/cql/stake_registration.cql
  catalyst-gateway/bin/src/db/index/schema/mod.rs
  catalyst-gateway/bin/src/db/index/session.rs
  catalyst-gateway/bin/src/db/index/tests/scylla_purge.rs
  catalyst-gateway/bin/src/db/types/slot.rs
  catalyst-gateway/bin/src/service/api/cardano/staking/assets_get.rs
  catalyst-gateway/bin/src/service/api/cardano/staking/mod.rs
  catalyst-gateway/bin/src/service/api/health/live_get.rs
  catalyst-gateway/bin/src/service/api/health/mod.rs
  catalyst-gateway/bin/src/service/api/health/ready_get.rs
  catalyst-gateway/bin/src/service/api/health/started_get.rs
  catalyst-gateway/bin/src/service/api/mod.rs
  catalyst-gateway/bin/src/service/common/objects/cardano/stake_info.rs
  catalyst-gateway/bin/src/service/common/responses/mod.rs
  catalyst-gateway/bin/src/service/common/types/cardano/slot_no.rs
  catalyst-gateway/bin/src/service/mod.rs
  catalyst-gateway/bin/src/service/poem_service.rs
  catalyst-gateway/bin/src/service/utilities/health/mod.rs
  catalyst-gateway/bin/src/service/utilities/health/ready.rs
  catalyst-gateway/bin/src/service/utilities/health/start.rs
  catalyst-gateway/bin/src/service/utilities/middleware/db_check.rs
  catalyst-gateway/bin/src/service/utilities/middleware/mod.rs
  catalyst-gateway/tests/api_tests/Earthfile
  catalyst-gateway/tests/api_tests/api/v1/cardano.py
  catalyst-gateway/tests/api_tests/api/v1/document.py
  catalyst-gateway/tests/api_tests/integration/test_assets.py
  catalyst-gateway/tests/api_tests/integration/test_signed_doc.py
  catalyst-gateway/tests/api_tests/integration/test_utxo.py
  catalyst-gateway/tests/api_tests/snapshot_tool-56364174.json
  catalyst-gateway/tests/api_tests/utils/snapshot.py
  catalyst-gateway/tests/schemathesis_tests/Earthfile
Labels: review me

#2307 feat(cat-voices): adding missing urls part 1
  catalyst_voices/apps/voices/lib/app/view/app_mobile_access_restriction.dart
  catalyst_voices/apps/voices/lib/common/constants/constants.dart
  catalyst_voices/apps/voices/lib/pages/account/widgets/account_page_title.dart
  catalyst_voices/apps/voices/lib/pages/campaign/stage/after_proposal_submission_page.dart
  catalyst_voices/apps/voices/lib/pages/campaign/stage/pre_proposal_submission_page.dart
  catalyst_voices/apps/voices/lib/pages/discovery/sections/stay_involved.dart
  catalyst_voices/apps/voices/lib/pages/registration/no_wallet_found_dialog.dart
  catalyst_voices/apps/voices/lib/pages/registration/registration_info_panel.dart
  catalyst_voices/apps/voices/lib/pages/registration/wallet_link/stage/select_wallet_panel.dart
  catalyst_voices/apps/voices/lib/pages/registration/widgets/information_panel.dart
  catalyst_voices/apps/voices/lib/pages/spaces/appbar/account_popup/session_account_popup_menu.dart
  catalyst_voices/apps/voices/lib/pages/spaces/drawer/opportunities_drawer.dart
  catalyst_voices/apps/voices/lib/pages/workspace/user_proposals/user_proposals.dart
  catalyst_voices/apps/voices/lib/widgets/buttons/learn_more_button.dart
  catalyst_voices/apps/voices/lib/widgets/headers/section_learn_more_header.dart
  catalyst_voices/apps/voices/lib/widgets/rich_text/insert_new_image_dialog_body.dart
Labels: review me, ux/ui, dart, F14

#2320 fix(cat-voices): Proposal builder UI fixes
  catalyst_voices/apps/voices/lib/pages/proposal_builder/proposal_builder_setup_panel.dart
  catalyst_voices/apps/voices/lib/pages/proposals/widgets/proposals_pagination.dart
  catalyst_voices/apps/voices/lib/widgets/containers/sidebar/space_side_panel.dart
  catalyst_voices/apps/voices/lib/widgets/document_builder/value/document_builder_value_widget.dart
  catalyst_voices/apps/voices/lib/widgets/document_builder/value/single_line_https_url_widget.dart
  catalyst_voices/apps/voices/lib/widgets/pagination/layouts/paginated_grid_view.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/proposal_builder_bloc.dart
Labels: bug, review me, ux/ui, dart, F14

#2313 feat(cat-voices): search proposals by author name
  catalyst_voices/apps/voices/lib/pages/discovery/sections/most_recent_proposals.dart
  catalyst_voices/apps/voices/lib/pages/overall_spaces/space/user_proposal_selectors/user_proposal_selectors.dart
  catalyst_voices/apps/voices/lib/pages/proposals/widgets/proposals_pagination_tile.dart
  catalyst_voices/apps/voices/lib/pages/voting/voting_page.dart
  catalyst_voices/apps/voices/lib/pages/workspace/user_proposals/user_proposals.dart
  catalyst_voices/apps/voices/lib/widgets/cards/proposal/pending_proposal_card.dart
  catalyst_voices/apps/voices/lib/widgets/cards/proposal/proposal_border.dart
  catalyst_voices/apps/voices/lib/widgets/cards/proposal/proposal_card.dart
  catalyst_voices/apps/voices/lib/widgets/cards/proposal/proposal_card_widgets.dart
  catalyst_voices/apps/voices/lib/widgets/cards/proposal/small_proposal_card.dart
  catalyst_voices/apps/voices/lib/widgets/cards/proposal/workspace_proposal_card.dart
  catalyst_voices/apps/voices/lib/widgets/modals/proposals/forget_proposal_dialog.dart
  catalyst_voices/apps/voices/lib/widgets/modals/proposals/publish_proposal_iteration_dialog.dart
  catalyst_voices/apps/voices/lib/widgets/modals/proposals/submit_proposal_for_review_dialog.dart
  catalyst_voices/apps/voices/lib/widgets/modals/proposals/unlock_edit_proposal.dart
  catalyst_voices/apps/voices/lib/widgets/widgets.dart
  catalyst_voices/apps/voices/test/widgets/cards/small_proposal_card_test.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/specialized/proposal_document.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/database/dao/proposals_dao.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/database/query/jsonb_expressions.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/database/dao/proposals_dao_test.dart
  catalyst_voices/utilities/uikit_example/lib/examples/voices_proposal_card_example.dart
Labels: review me, dart, F14

#2324 fix(cat-gateway): Fix `rbac/registration` `500` response
  catalyst-gateway/bin/Cargo.toml
  catalyst-gateway/bin/src/cardano/mod.rs
  catalyst-gateway/bin/src/db/index/queries/rbac/get_rbac_registrations.rs
  catalyst-gateway/bin/src/service/api/cardano/rbac/registrations_get/chain_info.rs
  catalyst-gateway/bin/src/service/api/documents/templates/mod.rs
Labels: review me

#2332 feat(cat-gateway): Update RBAC auth validation
  catalyst-gateway/bin/src/service/common/auth/rbac/scheme.rs
Labels: review me

#2310 feat(cat-gateway): Hide some non public endpoints in the OpenAPI specs.
  catalyst-gateway/bin/src/service/api/cardano/cip36/mod.rs
  catalyst-gateway/bin/src/service/api/cardano/cip36/response.rs
  catalyst-gateway/bin/src/service/api/config/mod.rs
  catalyst-gateway/bin/src/service/api/health/mod.rs
  catalyst-gateway/bin/src/service/common/types/cardano/query/stake_or_voter.rs
Labels: review me

#2327 feat(cat-voices): adding collapseable feature to list of user proposal
  catalyst_voices/apps/voices/lib/pages/workspace/user_proposals/user_proposal_section.dart
  catalyst_voices/apps/voices/lib/pages/workspace/user_proposals/user_proposals.dart
  catalyst_voices/apps/voices/lib/widgets/headers/section_learn_more_header.dart
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
Labels: review me, dart, F14

#2336 feat(general): Add config directory structure
  config/dev/.keep
  config/preprod/.keep
  config/prod/.keep
  config/qa/.keep
Labels: review me

#2335 fix(cat-voices): handling correctly show all categories
  catalyst_voices/apps/voices/lib/pages/category/change_category_button.dart
  catalyst_voices/apps/voices/lib/pages/proposals/widgets/category_selector.dart
  catalyst_voices/apps/voices/lib/widgets/dropdown/category_dropdown.dart
  catalyst_voices/apps/voices/test/widgets/dropdown/category_dropdown_test.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/catalyst_voices_view_models.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/category/dropdown_menu_view_model.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/proposals/proposals_category_filter.dart
Labels: bug, review me, dart, F14

#2344 fix(cat-gateway): lock local-ip-address to `0.6.3`
  catalyst-gateway/bin/Cargo.toml
Labels: review me

#2334 fix(cat-voices): pool concurrent documents sync
  catalyst_voices/melos.yaml
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/document/source/document_data_remote_source.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/document/source/document_data_remote_source_test.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/documents/documents_service.dart
  catalyst_voices/packages/internal/catalyst_voices_services/pubspec.yaml
Labels: bug, review me, dart, F14

#2333 feat(cat-gateway): Bumping a cat-gateway version
  catalyst-gateway/bin/Cargo.toml
  catalyst-gateway/bin/src/service/api/documents/templates/mod.rs
  catalyst-gateway/tests/api_tests/Earthfile
Labels: do not merge yet

#2329 chore(cat-voices): upgrade flutter to 3.29.3
  .github/workflows/flutter-publish-packages.yml
  Earthfile
  catalyst-gateway/Earthfile
  catalyst-gateway/event-db/Earthfile
  catalyst-gateway/tests/Earthfile
  catalyst-gateway/tests/api_tests/Earthfile
  catalyst_voices/Earthfile
  catalyst_voices/README.md
  catalyst_voices/apps/voices/pubspec.yaml
  catalyst_voices/melos.yaml
  catalyst_voices/packages/internal/catalyst_voices_assets/example/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_assets/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_blocs/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_brands/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_driver/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_localization/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_models/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_repositories/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_services/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_shared/pubspec.yaml
  catalyst_voices/packages/internal/catalyst_voices_view_models/pubspec.yaml
  catalyst_voices/packages/libs/README.md
  catalyst_voices/packages/libs/catalyst_analysis/example/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_analysis/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/README.md
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/example/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/wallet-automation/Earthfile
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano_platform_interface/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano_web/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cardano_serialization/README.md
  catalyst_voices/packages/libs/catalyst_cardano_serialization/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_compression/catalyst_compression/README.md
  catalyst_voices/packages/libs/catalyst_compression/catalyst_compression/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_compression/catalyst_compression_platform_interface/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_compression/catalyst_compression_web/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_cose/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_key_derivation/Earthfile
  catalyst_voices/packages/libs/catalyst_key_derivation/README.md
  catalyst_voices/packages/libs/catalyst_key_derivation/cargokit/build_tool/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_key_derivation/example/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_key_derivation/pubspec.yaml
  catalyst_voices/packages/libs/catalyst_key_derivation/rust/Earthfile
  catalyst_voices/utilities/poc_local_storage/pubspec.yaml
  catalyst_voices/utilities/remote_widgets/example/pubspec.yaml
  catalyst_voices/utilities/remote_widgets/pubspec.yaml
  catalyst_voices/utilities/uikit_example/Earthfile
  catalyst_voices/utilities/uikit_example/pubspec.yaml
  docs/Earthfile
  utilities/docs-preview/Earthfile
Labels: bug, review me, dart

#2337 feat(cat-voices): Proposal Viewer show proper Proposal publish state
  catalyst_voices/apps/voices/lib/pages/proposal/tiles/proposal_metadata_tile.dart
  catalyst_voices/apps/voices/lib/widgets/cards/proposal/proposal_card_widgets.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal/proposal_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
  catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/formatter/cryptocurrency_formatter.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/proposal/proposal_view_metadata.dart
Labels: bug, review me, ux/ui, dart, F14

#2347 chore(cat-voices): Add role info, remove phrases text
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
Labels: dart, F14

#2353 fix(cat-gateway): Fix CI
  catalyst-gateway/bin/Cargo.toml
Labels: review me

#2354 fix(cat-voices): Two lines helper text
  catalyst_voices/apps/voices/lib/widgets/text_field/voices_text_field.dart
Labels: bug, review me, dart, F14

#2357 feat(cat-voices): cant edit when new local iteration is created
  catalyst_voices/apps/voices/lib/pages/workspace/proposal_menu_action_button.dart
  catalyst_voices/apps/voices/lib/widgets/cards/proposal/workspace_proposal_card.dart
  catalyst_voices/apps/voices/lib/widgets/cards/proposal_iteration_history_card.dart
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/proposal/proposal.dart
Labels: review me, ux/ui, dart, F14

#2371 fix(cat-gateway): Fix cat-id generation for the signed docs tests
  catalyst-gateway/tests/api_tests/integration/__init__.py
  catalyst-gateway/tests/api_tests/utils/rbac_chain.py
Labels: review me

#2358 fix(cat-voices): enable unit web tests for catalyst_voices_assets
  catalyst_voices/melos.yaml
  catalyst_voices/packages/internal/catalyst_voices_brands/test/src/catalyst_voices_brands_test.dart
Labels: dart

#2343 feat(cat-gateway): Cleanup config endpoints
  catalyst-gateway/bin/Cargo.toml
  catalyst-gateway/bin/src/db/event/config/default/frontend.json
  catalyst-gateway/bin/src/db/event/config/default/frontend_ip.json
  catalyst-gateway/bin/src/db/event/config/key.rs
  catalyst-gateway/bin/src/db/event/config/mod.rs
  catalyst-gateway/bin/src/service/api/config/mod.rs
  catalyst-gateway/bin/src/service/common/objects/config/environment.rs
  catalyst-gateway/bin/src/service/common/objects/config/frontend_config.rs
  catalyst-gateway/bin/src/service/common/objects/config/mod.rs
  catalyst-gateway/bin/src/service/common/objects/config/version.rs
  catalyst-gateway/bin/src/service/common/objects/generic/json_object.rs
  catalyst-gateway/bin/src/service/common/objects/mod.rs
  catalyst-gateway/bin/src/service/common/types/generic/ip_addr.rs
  catalyst-gateway/bin/src/service/common/types/generic/json_object.rs
  catalyst-gateway/bin/src/service/common/types/generic/mod.rs
  catalyst-gateway/bin/src/service/utilities/json.rs
  catalyst-gateway/bin/src/service/utilities/mod.rs
  catalyst-gateway/bin/src/utils/schema.rs
  catalyst-gateway/tests/api_tests/Earthfile
  catalyst-gateway/tests/api_tests/api/__init__.py
  catalyst-gateway/tests/api_tests/api/v1/config_frontend.py
  catalyst-gateway/tests/api_tests/integration/test_config_frontend.py
  catalyst-gateway/tests/docker-compose.yml
Labels: review me

#2374 fix(cat-voices): enable unit web tests in catalyst_voices_repositories
  catalyst_voices/melos.yaml
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/database/catalyst_database_test.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/database/connection/test_connection.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/database/dao/documents_dao_test.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/database/dao/drafts_dao_test.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/database/dao/proposals_dao_test.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/database/drift_test_platforms.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/database/executor/native.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/database/executor/unsupported.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/database/executor/web.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/database/open/native.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/database/open/unsupported.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/database/open/web.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/document/document_dto_test.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/document/document_repository_test.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/document/schema/document_schema_dto_test.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/flutter_test_config.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/proposal/proposal_document_test.dart
Labels: dart

#2378 fix(cat-voices): recover account scrollable panel
  catalyst_voices/apps/voices/lib/pages/registration/recover/recover_method_panel.dart
Labels: bug, review me, dart, F14

#2380 chore(cat-voices): cleanup static docs references
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/campaign/campaign_category.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/catalyst_voices_models.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/constant_documents_refs.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/data/static_document_data.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/catalyst_voices_repositories.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/document/document_repository.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/database/dao/proposals_dao_test.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/document/document_repository_test.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/comment/comment_service.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/campaign/campaign_category_view_model.dart
Labels: review me, dart

#2383 fix(cat-voices): sorting alfabeticaly language list
  catalyst_voices/apps/voices/lib/widgets/document_builder/value/language_code_widget.dart
Labels: review me, ux/ui, dart, F14

#2386 chore(cat-voices): remove m4 from routing
  catalyst_voices/apps/voices/lib/configs/bootstrap.dart
  catalyst_voices/apps/voices/lib/routes/guards/milestone_guard.dart
  catalyst_voices/apps/voices/lib/routes/routing/account_route.dart
  catalyst_voices/apps/voices/lib/routes/routing/campaign_stage_route.dart
  catalyst_voices/apps/voices/lib/routes/routing/overall_spaces_route.dart
  catalyst_voices/apps/voices/lib/routes/routing/proposal_builder_route.dart
  catalyst_voices/apps/voices/lib/routes/routing/proposal_route.dart
  catalyst_voices/apps/voices/lib/routes/routing/routes.dart
  catalyst_voices/apps/voices/lib/routes/routing/spaces_route.dart
  catalyst_voices/blueprint.cue
  catalyst_voices/nginx.conf
  catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/wallet-automation/nginx.conf
Labels: review me, dart, F14, F14-RC1

#2391 feat(cat-voices): limit final proposals per user
  catalyst_voices/apps/voices/lib/pages/overall_spaces/space/user_proposal_selectors/discovery_overview_proposal_selector.dart
  catalyst_voices/apps/voices/lib/pages/proposal_builder/appbar/proposal_builder_status_action.dart
  catalyst_voices/apps/voices/lib/pages/proposal_builder/proposal_builder_page.dart
  catalyst_voices/apps/voices/lib/pages/workspace/header/workspace_header.dart
  catalyst_voices/apps/voices/lib/pages/workspace/user_proposals/user_proposals.dart
  catalyst_voices/apps/voices/lib/widgets/modals/proposals/proposal_limit_reached_dialog.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/proposal_builder_bloc.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/proposal_builder_bloc_cache.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/proposal_builder_event.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/proposal_builder_signal.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/proposal_builder_state.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/workspace/workspace_bloc.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/workspace/workspace_state.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/catalyst_voices_models.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/specialized/proposal_document.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/proposal/exception/proposal_limit_reached_exception.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/proposal/proposal_service.dart
  catalyst_voices/packages/internal/catalyst_voices_services/test/src/proposal/proposal_service_test.dart
Labels: review me, ux/ui, dart, F14

#2397 fix(cat-voices): comment failed dialog spacing
  catalyst_voices/apps/voices/lib/widgets/modals/comment/submit_comment_error_dialog.dart
  catalyst_voices/apps/voices/lib/widgets/modals/voices_desktop_dialog.dart
  catalyst_voices/apps/voices/lib/widgets/modals/voices_info_dialog.dart
Labels: bug, review me, dart, F14, F14-RC1

#2301 test(cat-gateway): Add integration test for auth token
  catalyst-gateway/bin/src/service/common/auth/rbac/scheme.rs
  catalyst-gateway/bin/src/service/common/auth/rbac/token.rs
  catalyst-gateway/bin/src/service/common/responses/mod.rs
  catalyst-gateway/tests/api_tests/api/v1/rbac.py
  catalyst-gateway/tests/api_tests/integration/test_rbac_auth_token.py
  catalyst-gateway/tests/api_tests/utils/rbac_chain.py
Labels: review me, rust, python, testcase

#2382 feat(cat-voices): retriving non static data for campaign
  catalyst_voices/apps/voices/lib/common/formatters/amount_formatter.dart
  catalyst_voices/apps/voices/lib/dependency/dependencies.dart
  catalyst_voices/apps/voices/lib/pages/category/category_detail_view.dart
  catalyst_voices/apps/voices/lib/widgets/cards/funds_detail_card.dart
  catalyst_voices/apps/voices/test/widgets/cards/funds_detail_card_test.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/campaign/campaign_category.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/campaign/current_campaign.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/proposal/proposal.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/campaign/campaign_repository.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/database/dao/proposals_dao.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/document/source/database_documents_data_source.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/document/source/proposal_document_data_local_source.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/proposal/proposal_repository.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/database/dao/proposals_dao_test.dart
  catalyst_voices/packages/internal/catalyst_voices_services/lib/src/campaign/campaign_service.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/campaign/current_campaign_info_view_model.dart
Labels: review me, dart, F14

#2398 fix(cat-voices): exclude hidden proposals from count query
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/proposals/proposals_count.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/database/dao/proposals_dao.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/database/dao/proposals_dao_test.dart
Labels: bug, review me, dart, F14, F14-RC1

#2396 fix(cat-voices): proposals list layout fix
  catalyst_voices/apps/voices/lib/widgets/pagination/layouts/paginated_grid_view.dart
  catalyst_voices/apps/voices/lib/widgets/pagination/paging_state.dart
  catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
Labels: bug, review me, F14, F14-RC1
