Repository input-output-hk/catalyst-voices, pull requests merged in 2025-10, with the labels that each got.

#3481 feat(general): Disable FE `earthly` targets
  catalyst_voices/Earthfile
  catalyst_voices/blueprint.cue
  catalyst_voices/packages/libs/catalyst_key_derivation/rust/Earthfile
Labels: review me, squad: gatekeepers, fyi: face

#3468 chore(cat-voices): comments category_id
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal/proposal_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/proposal_builder_bloc.dart
  catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/specialized/comment_document.dart
  catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/comment/comment_repository.dart
Labels: squad: face, a: proposal, no-track

#3487 fix(cat-voices): sentry auth token in docker target
  catalyst_voices/blueprint.cue
Labels: squad: face

#3491 feat(cat-gateway): Latest Catalyst Signed Documents validation rules from `catalyst-signed-doc/v0.0.4-f15-rc-2`
  catalyst-gateway/Cargo.lock
  catalyst-gateway/bin/Cargo.toml
  catalyst-gateway/tests/api_tests/integration/test_signed_doc.py
Labels: review me, squad: gatekeepers

#3460 feat(cat-voices): discovery widget optimization
  catalyst_voices/apps/voices/lib/pages/category/category_page.dart
  catalyst_voices/apps/voices/lib/pages/discovery/discovery_page.dart
  catalyst_voices/apps/voices/lib/pages/discovery/sections/campaign_details/campaign_details.dart
  catalyst_voices/apps/voices/lib/pages/discovery/sections/campaign_details/widgets/campaign_categories.dart
  catalyst_voices/apps/voices/lib/pages/discovery/sections/campaign_details/widgets/current_campaign.dart
  catalyst_voices/apps/voices/lib/pages/discovery/sections/most_recent_proposals.dart
  catalyst_voices/apps/voices/lib/pages/discovery/sections/most_recent_proposals/most_recent_proposals.dart
  catalyst_voices/apps/voices/lib/pages/discovery/sections/most_recent_proposals/recent_proposals.dart
  catalyst_voices/apps/voices/lib/pages/discovery/sections/stay_involved.dart
  catalyst_voices/apps/voices/lib/pages/discovery/sections/stay_involved/stay_involved.dart
  catalyst_voices/apps/voices/lib/pages/discovery/sections/stay_involved/widgets/copy_catalyst_id_tip.dart
  catalyst_voices/apps/voices/lib/pages/discovery/sections/stay_involved/widgets/reviewer_card.dart
  catalyst_voices/apps/voices/lib/pages/discovery/sections/stay_involved/widgets/stay_involved_action_button.dart
  catalyst_voices/apps/voices/lib/pages/discovery/sections/stay_involved/widgets/stay_involved_card.dart
  catalyst_voices/apps/voices/lib/pages/discovery/sections/stay_involved/widgets/timeline_card.dart
  catalyst_voices/apps/voices/lib/pages/discovery/sections/stay_involved/widgets/voter_card.dart
  catalyst_voices/apps/voices/lib/pages/discovery/state_selectors/campaign_categories_state_selector.dart
  catalyst_voices/apps/voices/lib/pages/discovery/state_selectors/current_campaign_selector.dart
  catalyst_voices/apps/voices/lib/pages/discovery/state_selectors/most_recent_proposals_selector.dart
  catalyst_voices/apps/voices/lib/pages/discovery/toggle_state_text.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/category/category_detail_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/discovery/discovery_cubit.dart
  catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/discovery/discovery_state.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/campaign/campaign_category_view_model.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/campaign/campaign_timeline_event_with_title.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/catalyst_voices_view_models.dart
  catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/proposal/proposal_brief.dart
Labels: review me, squad: face, no-track
